export function globalContextTemplate(): string {
  return [
    "# Project / Delivery Context",
    "",
    "## Project Goal",
    "",
    "- Describe the user-visible goal this project is trying to achieve.",
    "",
    "## Non-goals / Boundaries",
    "",
    "- List what this project intentionally does not do.",
    "",
    "## Background",
    "",
    "- Capture the minimum background a fresh agent needs before changing code.",
    "",
    "## Design Rationale",
    "",
    "- Record only durable choices that are hard to infer from code or tests.",
    "",
    "## Architecture Context",
    "",
    "- Link to `project_context/architecture.md`; keep architecture notes minimal and focused on boundaries, components and constraints that are not obvious from code.",
    "",
    "## Context Graph",
    "",
    "- Link to `project_context/context.toml` and keep its default area, role, trigger, read policy and boundary metadata aligned with this Context.",
    "",
    "## Product / Delivery Brief",
    "",
    "- Capture durable product goals, users, core flows, acceptance signals and non-goals.",
    "",
    "## UX / Screen Brief",
    "",
    "- Capture durable screen, flow, interaction, responsive and accessibility facts. Use `DESIGN.md` for visual identity and design tokens when needed.",
    "",
    "## Verification Entry Points",
    "",
    "- `npm test` or the project-specific command that proves product behavior.",
    "",
    "## Current State",
    "",
    "- Summarize what is currently implemented or intentionally blocked.",
    "",
    "## Next Safe Action",
    "",
    "- State the safest next step for a fresh agent.",
    "",
    "## Context Index",
    "",
    "- [main](areas/main.md)",
    ""
  ].join("\n");
}

export function architectureContextTemplate(): string {
  return [
    "# Architecture Context",
    "",
    "This is the restrained architecture context. Keep only facts that help a fresh agent recover system shape, boundaries and durable constraints quickly.",
    "",
    "## System Boundary",
    "",
    "- Describe what is inside this project and what external systems, providers or runtime assumptions sit outside it.",
    "",
    "## Component Map",
    "",
    "- List the smallest useful set of components, areas or context units and how they relate.",
    "",
    "## Data / Control Flow",
    "",
    "- Summarize only the durable request, event, state or data flow that is hard to infer from code alone.",
    "",
    "## Design Rationale",
    "",
    "- Record architecture-level choices that still constrain future work.",
    "",
    "## Constraints And Tradeoffs",
    "",
    "- Capture performance, safety, integration, deployment or maintainability constraints that matter for future changes.",
    "",
    "## Verification Implications",
    "",
    "- List project-specific verification entry points affected by architectural changes; do not claim tests already passed.",
    "",
    "## Open Risks",
    "",
    "- List unresolved architectural risks or unknowns.",
    ""
  ].join("\n");
}

export function areaContextTemplate(areaName: string): string {
  return [
    `# Area Context: ${areaName}`,
    "",
    "## Responsibility",
    "",
    "- Describe this area or context unit's responsibility.",
    "",
    "## User / System Contract",
    "",
    "- Describe the external behavior, API, CLI, UI, screen state, interaction or data contract.",
    "",
    "## Core Data / API / State",
    "",
    "- Summarize the important data structures, APIs, state transitions, or rules.",
    "",
    "## Key Constraints",
    "",
    "- List constraints that are not obvious from code alone, including product rules, responsive/a11y needs or visual boundaries.",
    "",
    "## Code Entry Points",
    "",
    "- `src/` or the concrete file/function entry points.",
    "",
    "## Test Entry Points",
    "",
    "- `npm test` or focused test commands for this area.",
    "",
    "## Open Risks",
    "",
    "- List unresolved risks or blockers.",
    ""
  ].join("\n");
}
