import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { readConfig } from "./config.js";
import { shouldIncludeCodeFile, toPosix } from "./source-files.js";
import type { ModularityWaiverConfig } from "./types.js";

const execFileAsync = promisify(execFile);
const GIT_MAX_BUFFER = 16 * 1024 * 1024;
const DEFAULT_LINE_LIMIT = 300;
const DEFAULT_MODULARITY_POLICY = "scoped_waivers";
const MODULARITY_POLICIES = new Set([DEFAULT_MODULARITY_POLICY, "strict_except_generated"]);

const GENERATED_FILE_PATTERNS = [
  /^\s*(?:\/\/|#|--|;)\s*@generated\b/im,
  /^\s*(?:\/\/|#|--|;)\s*code generated .*do not edit\.?\s*$/im,
  /^\s*(?:\/\/|#|--|;)\s*do not edit\.?\s*$/im,
  /^\s*(?:\/\/|#|--|;|<!--)\s*<auto-generated\b/im,
  /^\s*(?:\/\/|#|--|;)\s*this file was generated\b/im,
  /^\s*(?:\/\/|#|--|;)\s*generated by\b/im
];

const WAIVER_CATEGORIES = new Set([
  "generated",
  "third_party_reference",
  "legacy_migration",
  "aggregate_styles",
  "fixture_snapshot"
]);

export interface ModularityCheckOptions {
  touched?: boolean;
  base?: string;
  files?: string[];
  limit?: number;
}

export interface ModularityFileReport {
  relativePath: string;
  lines: number;
  overLimit: boolean;
  waived?: ModularityWaiver;
}

export interface ModularityCheckReport {
  limit: number;
  files: ModularityFileReport[];
  warnings: string[];
  waivedWarnings: string[];
  errors: string[];
}

export interface ModularityWaiver {
  relativePath: string;
  category: string;
  reason: string;
  futureSplitBoundary: string;
}

export async function runModularityCheck(
  projectRoot: string,
  options: ModularityCheckOptions
): Promise<ModularityCheckReport> {
  const config = await readConfig(projectRoot);
  const { limit: configuredLimit, waiverValues, errors: configErrors } = validateModularityConfig(config.modularity);
  const { waivers, errors: waiverErrors } = validateWaivers(projectRoot, waiverValues);
  const limit = options.limit ?? configuredLimit ?? DEFAULT_LINE_LIMIT;
  const candidates = new Set<string>();

  for (const file of options.files ?? []) {
    candidates.add(normalizeExplicitPath(projectRoot, file));
  }
  if (options.touched) {
    for (const relative of await gitTouchedFiles(projectRoot)) {
      candidates.add(normalizeGitPath(relative));
    }
  }
  if (options.base) {
    for (const relative of await gitDiffFiles(projectRoot, options.base)) {
      candidates.add(normalizeGitPath(relative));
    }
  }

  const files: ModularityFileReport[] = [];
  for (const relativePath of [...candidates].sort()) {
    if (!shouldIncludeCodeFile(relativePath)) {
      continue;
    }
    const absolutePath = path.join(projectRoot, ...relativePath.split("/"));
    if (!(await isRegularFile(absolutePath)) || (await isLikelyGeneratedFile(absolutePath))) {
      continue;
    }
    const lines = countPhysicalLines(await fs.readFile(absolutePath, "utf8"));
    const waiver = waivers.get(relativePath);
    files.push({ relativePath, lines, overLimit: lines > limit, waived: waiver });
  }

  const warnings = files
    .filter((file) => file.overLimit && !file.waived)
    .map((file) => `${file.relativePath}: ${file.lines} physical lines exceeds limit ${limit}`);
  const waivedWarnings = files
    .filter((file) => file.overLimit && file.waived)
    .map(
      (file) =>
        `${file.relativePath}: ${file.lines} physical lines exceeds limit ${limit} but is waived as ${file.waived?.category}`
    );
  return { limit, files, warnings, waivedWarnings, errors: [...configErrors, ...waiverErrors] };
}

export function countPhysicalLines(content: string): number {
  if (content.length === 0) {
    return 0;
  }
  const lines = content.split(/\r\n|\n|\r/);
  if (lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines.length;
}

async function gitTouchedFiles(projectRoot: string): Promise<string[]> {
  let result: { stdout: string };
  try {
    result = await execFileAsync("git", ["-C", projectRoot, "status", "--porcelain", "-z"], {
      encoding: "utf8",
      maxBuffer: GIT_MAX_BUFFER
    });
  } catch (error) {
    if (isNotGitRepositoryError(error)) {
      return [];
    }
    throw error;
  }
  const records = result.stdout.split("\0").filter(Boolean);
  const files: string[] = [];
  for (let index = 0; index < records.length; index += 1) {
    const record = records[index];
    const status = record.slice(0, 2);
    const relative = record.slice(3);
    if (relative) {
      files.push(relative);
    }
    if (status.includes("R") || status.includes("C")) {
      index += 1;
    }
  }
  return files;
}

async function gitDiffFiles(projectRoot: string, base: string): Promise<string[]> {
  const result = await execFileAsync("git", ["-C", projectRoot, "diff", "--name-only", "-z", base, "--"], {
    encoding: "utf8",
    maxBuffer: GIT_MAX_BUFFER
  });
  return result.stdout.split("\0").filter(Boolean);
}

function isNotGitRepositoryError(error: unknown): boolean {
  if (!error || typeof error !== "object") {
    return false;
  }
  const stderr = "stderr" in error && typeof error.stderr === "string" ? error.stderr : "";
  return /not a git repository/i.test(stderr);
}

function normalizeExplicitPath(projectRoot: string, value: string): string {
  const absolute = path.isAbsolute(value) ? path.resolve(value) : path.resolve(projectRoot, value);
  const relative = toPosix(path.relative(projectRoot, absolute));
  if (relative.startsWith("../") || relative === ".." || path.isAbsolute(relative)) {
    throw new Error(`check-modularity --file must stay inside the project root: ${value}`);
  }
  return normalizeGitPath(relative);
}

function normalizeGitPath(value: string): string {
  return toPosix(value).replace(/^\.\//, "");
}

function validateModularityConfig(
  modularity: unknown
): { limit?: number; waiverValues?: ModularityWaiverConfig[]; errors: string[] } {
  const errors: string[] = [];
  if (modularity === undefined) {
    return { errors };
  }
  if (!modularity || typeof modularity !== "object" || Array.isArray(modularity)) {
    errors.push("<harnessRoot>/config.yaml modularity must be an object");
    return { errors };
  }
  const value = modularity as { limit?: unknown; policy?: unknown; waivers?: ModularityWaiverConfig[] };
  let limit: number | undefined;
  let policy = DEFAULT_MODULARITY_POLICY;
  if (value.limit !== undefined) {
    if (!Number.isInteger(value.limit) || Number(value.limit) <= 0) {
      errors.push("<harnessRoot>/config.yaml modularity.limit must be a positive integer");
    } else {
      limit = Number(value.limit);
    }
  }
  if (value.policy !== undefined) {
    if (typeof value.policy !== "string" || !MODULARITY_POLICIES.has(value.policy)) {
      errors.push(
        "<harnessRoot>/config.yaml modularity.policy must be one of scoped_waivers, strict_except_generated"
      );
    } else {
      policy = value.policy;
    }
  }
  if (policy === "strict_except_generated" && value.waivers !== undefined) {
    errors.push(
      "<harnessRoot>/config.yaml modularity.waivers is not allowed when modularity.policy is strict_except_generated"
    );
  }
  return { limit, waiverValues: policy === "scoped_waivers" ? value.waivers : undefined, errors };
}

function validateWaivers(
  projectRoot: string,
  waiverValues: ModularityWaiverConfig[] | undefined
): { waivers: Map<string, ModularityWaiver>; errors: string[] } {
  const waivers = new Map<string, ModularityWaiver>();
  const errors: string[] = [];
  if (waiverValues === undefined) {
    return { waivers, errors };
  }
  if (!Array.isArray(waiverValues)) {
    errors.push("<harnessRoot>/config.yaml modularity.waivers must be an array");
    return { waivers, errors };
  }

  for (const [index, waiver] of waiverValues.entries()) {
    const label = `<harnessRoot>/config.yaml modularity.waivers[${index}]`;
    if (!waiver || typeof waiver !== "object") {
      errors.push(`${label} must be an object`);
      continue;
    }
    const relativePath = requiredWaiverString(waiver, "path", label, errors);
    const category = requiredWaiverString(waiver, "category", label, errors);
    const reason = requiredWaiverString(waiver, "reason", label, errors);
    const futureSplitBoundary = requiredWaiverString(waiver, "future_split_boundary", label, errors);
    if (!relativePath || !category || !reason || !futureSplitBoundary) {
      continue;
    }
    if (!WAIVER_CATEGORIES.has(category)) {
      errors.push(
        `${label}.category must be one of generated, third_party_reference, legacy_migration, aggregate_styles, fixture_snapshot`
      );
      continue;
    }
    let normalized: string;
    try {
      normalized = normalizeExplicitPath(projectRoot, relativePath);
    } catch {
      errors.push(`${label}.path must stay inside the project root: ${relativePath}`);
      continue;
    }
    const existing = waivers.get(normalized);
    if (existing) {
      errors.push(`${label}.path duplicates an existing modularity waiver for ${normalized}`);
      continue;
    }
    waivers.set(normalized, {
      relativePath: normalized,
      category,
      reason,
      futureSplitBoundary
    });
  }
  return { waivers, errors };
}

function requiredWaiverString(
  waiver: ModularityWaiverConfig,
  field: keyof ModularityWaiverConfig,
  label: string,
  errors: string[]
): string | undefined {
  const value = waiver[field];
  if (typeof value !== "string" || value.trim().length === 0) {
    errors.push(`${label}.${field} must be a non-empty string`);
    return undefined;
  }
  return value.trim();
}

async function isRegularFile(target: string): Promise<boolean> {
  try {
    return (await fs.stat(target)).isFile();
  } catch {
    return false;
  }
}

async function isLikelyGeneratedFile(target: string): Promise<boolean> {
  const content = await fs.readFile(target, "utf8");
  const sample = content.slice(0, 8192);
  return GENERATED_FILE_PATTERNS.some((pattern) => pattern.test(sample));
}
