import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { shouldIncludeCodeFile, toPosix } from "./source-files.js";

const execFileAsync = promisify(execFile);
const GIT_MAX_BUFFER = 16 * 1024 * 1024;

const GENERATED_FILE_PATTERNS = [
  /^\s*(?:\/\/|#|--|;)\s*@generated\b/im,
  /^\s*(?:\/\/|#|--|;)\s*code generated .*do not edit\.?\s*$/im,
  /^\s*(?:\/\/|#|--|;)\s*do not edit\.?\s*$/im,
  /^\s*(?:\/\/|#|--|;|<!--)\s*<auto-generated\b/im,
  /^\s*(?:\/\/|#|--|;)\s*this file was generated\b/im,
  /^\s*(?:\/\/|#|--|;)\s*generated by\b/im
];

export interface ModularityCheckOptions {
  touched?: boolean;
  base?: string;
  files?: string[];
  limit?: number;
}

export interface ModularityFileReport {
  relativePath: string;
  lines: number;
  overLimit: boolean;
}

export interface ModularityCheckReport {
  limit: number;
  files: ModularityFileReport[];
  warnings: string[];
}

export async function runModularityCheck(
  projectRoot: string,
  options: ModularityCheckOptions
): Promise<ModularityCheckReport> {
  const limit = options.limit ?? 300;
  const candidates = new Set<string>();

  for (const file of options.files ?? []) {
    candidates.add(normalizeExplicitPath(projectRoot, file));
  }
  if (options.touched) {
    for (const relative of await gitTouchedFiles(projectRoot)) {
      candidates.add(normalizeGitPath(relative));
    }
  }
  if (options.base) {
    for (const relative of await gitDiffFiles(projectRoot, options.base)) {
      candidates.add(normalizeGitPath(relative));
    }
  }

  const files: ModularityFileReport[] = [];
  for (const relativePath of [...candidates].sort()) {
    if (!shouldIncludeCodeFile(relativePath)) {
      continue;
    }
    const absolutePath = path.join(projectRoot, ...relativePath.split("/"));
    if (!(await isRegularFile(absolutePath)) || (await isLikelyGeneratedFile(absolutePath))) {
      continue;
    }
    const lines = countPhysicalLines(await fs.readFile(absolutePath, "utf8"));
    files.push({ relativePath, lines, overLimit: lines > limit });
  }

  const warnings = files
    .filter((file) => file.overLimit)
    .map((file) => `${file.relativePath}: ${file.lines} physical lines exceeds limit ${limit}`);
  return { limit, files, warnings };
}

export function countPhysicalLines(content: string): number {
  if (content.length === 0) {
    return 0;
  }
  const lines = content.split(/\r\n|\n|\r/);
  if (lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines.length;
}

async function gitTouchedFiles(projectRoot: string): Promise<string[]> {
  const result = await execFileAsync("git", ["-C", projectRoot, "status", "--porcelain", "-z"], {
    encoding: "utf8",
    maxBuffer: GIT_MAX_BUFFER
  });
  const records = result.stdout.split("\0").filter(Boolean);
  const files: string[] = [];
  for (let index = 0; index < records.length; index += 1) {
    const record = records[index];
    const status = record.slice(0, 2);
    const relative = record.slice(3);
    if (relative) {
      files.push(relative);
    }
    if (status.includes("R") || status.includes("C")) {
      index += 1;
    }
  }
  return files;
}

async function gitDiffFiles(projectRoot: string, base: string): Promise<string[]> {
  const result = await execFileAsync("git", ["-C", projectRoot, "diff", "--name-only", "-z", base, "--"], {
    encoding: "utf8",
    maxBuffer: GIT_MAX_BUFFER
  });
  return result.stdout.split("\0").filter(Boolean);
}

function normalizeExplicitPath(projectRoot: string, value: string): string {
  const absolute = path.isAbsolute(value) ? path.resolve(value) : path.resolve(projectRoot, value);
  const relative = toPosix(path.relative(projectRoot, absolute));
  if (relative.startsWith("../") || relative === ".." || path.isAbsolute(relative)) {
    throw new Error(`check-modularity --file must stay inside the project root: ${value}`);
  }
  return normalizeGitPath(relative);
}

function normalizeGitPath(value: string): string {
  return toPosix(value).replace(/^\.\//, "");
}

async function isRegularFile(target: string): Promise<boolean> {
  try {
    return (await fs.stat(target)).isFile();
  } catch {
    return false;
  }
}

async function isLikelyGeneratedFile(target: string): Promise<boolean> {
  const content = await fs.readFile(target, "utf8");
  const sample = content.slice(0, 8192);
  return GENERATED_FILE_PATTERNS.some((pattern) => pattern.test(sample));
}
