import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { checkLongTaskCompletionGate } from "../../packages/ty-context/dist/lib/long-task-hook-preflight.js";

const repoRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const source=path.join(repoRoot,".codex/ty-context-managed/hooks/long-task-hook.mjs");
const hookSource=readFileSync(source);
// Contract V3 regression identity: ordinary_question_hook_noop.
test("ordinary hook invocation is a state-free no-op",async()=>{ const root=await repo(); const result=runHook(root,{hook_event_name:"Stop",cwd:root,last_assistant_message:"ordinary answer"}); assert.deepEqual(result,{}); await assert.rejects(readFile(path.join(root,".codex","ty-context-long-task-hook-heartbeat.json"),"utf8"),/ENOENT/); assert.equal((await checkLongTaskCompletionGate(root)).status,"available"); });
test("missing Hook capability fails closed",async()=>{ const root=await mkdtemp(path.join(os.tmpdir(),"ltw-hook-missing-")); assert.equal((await checkLongTaskCompletionGate(root)).status,"completion_gate_unavailable"); });
test("Stop delegates the real last assistant message to the project gate",async()=>{ const root=await repo(); const cli=path.join(root,"fake-cli.mjs"); await writeFile(cli,`console.log(JSON.stringify(process.argv.includes("DONE")?{decision:"block",reason:"continue"}:{}))\n`); const workdir=path.join(root,"task"); await mkdir(workdir); const config=await readFile(path.join(root,".codex","hooks.json")); const script=await readFile(path.join(root,".codex","hooks","long-task-hook.mjs")); const hash=(v)=>createHash("sha256").update(v).digest("hex"); const contractHash="a".repeat(64); await writeFile(path.join(workdir,"compiled-contract.json"),JSON.stringify({repository_root:root,workdir,contract_sha256:contractHash})); const gitDir=git(root,["rev-parse","--absolute-git-dir"]); const active={schema_version:"active-long-task-binding-v4",campaign_id:null,slice_id:null,worktree_id:worktreeId(gitDir),repository_root:root,workdir,contract_sha256:contractHash,hook_bundle_sha256:hash(`${hash(config)}:${hash(script)}`),verifier:{cli_path:cli,cli_sha256:hash(await readFile(cli))}}; await writeFile(path.join(root,".codex","ty-context-active-long-task.json"),JSON.stringify(active)); await writeFile(git(root,["rev-parse","--path-format=absolute","--git-path","ty-context-active-long-task.json"]),JSON.stringify(active)); assert.deepEqual(runHook(root,{hook_event_name:"Stop",cwd:root,last_assistant_message:"DONE"}),{decision:"block",reason:"continue"}); });
test("active_pointer_deleted_or_retargeted",async()=>{const root=await repo();await writeFile(path.join(root,".git","ty-context-active-long-task.json"),JSON.stringify({repository_root:root}));const result=runHook(root,{hook_event_name:"Stop",cwd:root});assert.equal(result.decision,"block");});
test("a nested linked-worktree Hook clears only that worktree binding",async()=>{const root=await repo();const linked=await mkdtemp(path.join(os.tmpdir(),"ltw hook linked "));try{git(root,["worktree","add","--detach",linked,"HEAD"]);const nested=path.join(linked,"src","nested");await mkdir(nested,{recursive:true});const main=await writeActive(root,"CMP-001","SFC-MAIN");const child=await writeActive(linked,"CMP-001","SFC-CHILD");assert.deepEqual(runHook(linked,{hook_event_name:"Stop",cwd:nested,last_assistant_message:"done"}),{});await assert.rejects(readFile(child.project,"utf8"),/ENOENT/);await assert.rejects(readFile(child.git,"utf8"),/ENOENT/);assert.equal(JSON.parse(await readFile(main.git,"utf8")).slice_id,"SFC-MAIN");}finally{git(root,["worktree","remove","--force",linked],true);}});
async function repo(){ const root=await mkdtemp(path.join(os.tmpdir(),"ltw-hook-")); git(root,["init","-q"]); await mkdir(path.join(root,".codex","hooks"),{recursive:true}); await mkdir(path.join(root,"packages/ty-context/dist"),{recursive:true}); await writeFile(path.join(root,"packages/ty-context/dist/cli.js"),"console.log('{}')\n"); await writeFile(path.join(root,".codex","hooks","long-task-hook.mjs"),hookSource); await writeConfig(root); git(root,["config","user.email","hook-fixture@example.invalid"]);git(root,["config","user.name","Hook Fixture"]);git(root,["add","."]);git(root,["commit","-m","fixture baseline"]);return root; }
function runHook(root,input){ const result=spawnSync(process.execPath,[path.join(root,".codex","hooks","long-task-hook.mjs")],{cwd:root,input:JSON.stringify(input),encoding:"utf8"}); assert.equal(result.status,0,result.stderr); return JSON.parse(result.stdout.trim()); }
async function writeConfig(root){ const handler={type:"command",command:'node "$(git rev-parse --show-toplevel)/.codex/hooks/long-task-hook.mjs"',commandWindows:"powershell -NoProfile -Command \"$r=(git rev-parse --show-toplevel); node (Join-Path $r '.codex/hooks/long-task-hook.mjs')\""}; await writeFile(path.join(root,".codex","hooks.json"),JSON.stringify({hooks:{SessionStart:[{hooks:[handler]}],PostCompact:[{hooks:[handler]}],Stop:[{hooks:[handler]}]}})); }
async function writeActive(root,campaignId,sliceId){const hash=(value)=>createHash("sha256").update(value).digest("hex");const cli=path.join(root,"packages","ty-context","dist","cli.js");const workdir=path.join(root,"task");await mkdir(workdir,{recursive:true});const contractHash=hash(`${campaignId}:${sliceId}`);await writeFile(path.join(workdir,"compiled-contract.json"),JSON.stringify({repository_root:root,workdir,contract_sha256:contractHash}));const config=await readFile(path.join(root,".codex","hooks.json"));const script=await readFile(path.join(root,".codex","hooks","long-task-hook.mjs"));const gitDir=git(root,["rev-parse","--absolute-git-dir"]);const active={schema_version:"active-long-task-binding-v4",campaign_id:campaignId,slice_id:sliceId,worktree_id:worktreeId(gitDir),repository_root:root,workdir,contract_sha256:contractHash,hook_bundle_sha256:hash(`${hash(config)}:${hash(script)}`),verifier:{cli_path:cli,cli_sha256:hash(await readFile(cli))}};const project=path.join(root,".codex","ty-context-active-long-task.json");const gitPointer=git(root,["rev-parse","--path-format=absolute","--git-path","ty-context-active-long-task.json"]);await writeFile(project,JSON.stringify(active));await writeFile(gitPointer,JSON.stringify(active));return {project,git:gitPointer};}
function git(cwd,args,allowFailure=false){const result=spawnSync("git",args,{cwd,encoding:"utf8",windowsHide:true});if(!allowFailure)assert.equal(result.status,0,result.stderr);return result.stdout.trim();}
function worktreeId(gitDir){let identity=path.resolve(gitDir).replace(/\\/g,"/");if(process.platform==="win32")identity=identity.toLowerCase();return createHash("sha256").update(identity).digest("hex");}
