import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import YAML from "yaml";
import { writeHappyV3Contract } from "./long-task-v3-fixtures.mjs";
import { applyPacketV3, applyScopeV3, bindCampaignGoalV3, createCampaignV3, handoffCampaignV3, preflightCampaignV3, recordCampaignResultV3 } from "../../packages/ty-context/dist/lib/composite-campaign-v3.js";
import { getActiveLongTask } from "../../packages/ty-context/dist/lib/long-task-host-client.js";
import { runLongTaskFinalGate } from "./long-task-test-runtime.mjs";

test("clean-start V3 campaign projects YAML and hands off without legacy state", async () => { const root=await mkdtemp(path.join(os.tmpdir(),"campaign-v3-")); const authored=await writeHappyV3Contract(root); await writeFile(path.join(root,"request.md"),"Build the capability\n"); const campaign=await createCampaignV3(root,"campaign-1","request.md"); const campaignPath=path.join(root,".codex","composite-long-task","campaigns",campaign.campaign_id); await writeFile(path.join(root,"scope.json"),JSON.stringify({schema_version:"scope-fit-result-v2",selected_slice_id:"SFC-001"})); await applyScopeV3(root,campaignPath,"scope.json"); const packet={schema_version:"composite-authoring-packet-v3",campaign_id:"campaign-1",slice_id:"SFC-001",revision:1,previous_packet_sha256:null,authorities:{product_architecture_source:YAML.parse(await readFile(path.join(authored,"product-architecture-source.yaml"),"utf8")),technical_realization_plan:YAML.parse(await readFile(path.join(authored,"technical-realization-plan.yaml"),"utf8")),acceptance_checklist:YAML.parse(await readFile(path.join(authored,"acceptance-checklist.yaml"),"utf8"))}}; await writeFile(path.join(root,"packet.json"),JSON.stringify(packet)); await applyPacketV3(root,campaignPath,"SFC-001","packet.json"); assert.equal((await preflightCampaignV3(root,campaignPath,"SFC-001")).handoff_ready,true); const handoff=await handoffCampaignV3(root,campaignPath,"SFC-001"); assert.ok(handoff.contract_sha256); assert.equal(await getActiveLongTask(root),null,"handoff without a created Goal must not strand Stop enforcement"); await bindCampaignGoalV3(root,campaignPath,"SFC-001","goal-001"); assert.equal((await getActiveLongTask(root)).contract_sha256,handoff.contract_sha256); await assert.rejects(readFile(path.join(handoff.workdir,"task-state.json")),/ENOENT/); assert.match(await readFile(path.join(handoff.workdir,"product-architecture-source.yaml"),"utf8"),/product-source-v3/); await runLongTaskFinalGate(handoff.workdir); const projected=await recordCampaignResultV3(root,campaignPath,"SFC-001",path.relative(root,handoff.workdir),runLongTaskFinalGate); assert.equal(projected.workflow_status,"accepted"); });

test("legacy packet is rejected without compatibility parsing", async () => { const root=await mkdtemp(path.join(os.tmpdir(),"campaign-legacy-")); await writeHappyV3Contract(root); await writeFile(path.join(root,"request.md"),"Build\n"); await createCampaignV3(root,"campaign-2","request.md"); const campaignPath=path.join(root,".codex","composite-long-task","campaigns","campaign-2"); await writeFile(path.join(root,"scope.json"),JSON.stringify({schema_version:"scope-fit-result-v2",selected_slice_id:"SFC-001"})); await applyScopeV3(root,campaignPath,"scope.json"); await writeFile(path.join(root,"packet.json"),JSON.stringify({schema_version:"composite-authoring-packet-v2"})); await assert.rejects(applyPacketV3(root,campaignPath,"SFC-001","packet.json"),/Legacy packets are not supported/); });
test("campaign inputs cannot escape the repository",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"campaign-path-"));const outside=path.join(path.dirname(root),"outside-request.md");await writeFile(outside,"escape");await assert.rejects(()=>createCampaignV3(root,"campaign-escape",outside),/safe repository-relative path|outside repository|escapes/i);});
test("campaign request rejects raw credentials before creating state",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"campaign-secret-"));await writeFile(path.join(root,"request.md"),"api_key = abcdefghijklmnop");await assert.rejects(()=>createCampaignV3(root,"campaign-secret","request.md"),/raw credential/);await assert.rejects(readFile(path.join(root,".codex/composite-long-task/campaigns/campaign-secret/campaign.yaml")),/ENOENT/);});
