import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import YAML from "yaml";
import { writeHappyContract } from "./long-task-v2-fixtures.mjs";
import { applyPacketV2, applyScopeV2, createCampaignV2, handoffCampaignV2, preflightCampaignV2, recordCampaignResultV2 } from "../../packages/ty-context/dist/lib/composite-campaign-v2.js";
import { runLongTaskFinalGate } from "../../packages/ty-context/dist/lib/long-task-final-gate.js";

test("clean-start V2 campaign projects YAML and hands off without legacy state", async () => { const root=await mkdtemp(path.join(os.tmpdir(),"campaign-v2-")); const authored=await writeHappyContract(root); await writeFile(path.join(root,"request.md"),"Build the capability\n"); const campaign=await createCampaignV2(root,"campaign-1","request.md"); const campaignPath=path.join(root,".codex","composite-long-task","campaigns",campaign.campaign_id); await writeFile(path.join(root,"scope.json"),JSON.stringify({schema_version:"scope-fit-result-v2",selected_slice_id:"SFC-001"})); await applyScopeV2(root,campaignPath,"scope.json"); const packet={schema_version:"composite-authoring-packet-v2",campaign_id:"campaign-1",slice_id:"SFC-001",revision:1,previous_packet_sha256:null,authorities:{product_architecture_source:YAML.parse(await readFile(path.join(authored,"product-architecture-source.yaml"),"utf8")),technical_realization_plan:YAML.parse(await readFile(path.join(authored,"technical-realization-plan.yaml"),"utf8")),acceptance_checklist:YAML.parse(await readFile(path.join(authored,"acceptance-checklist.yaml"),"utf8"))}}; await writeFile(path.join(root,"packet.json"),JSON.stringify(packet)); await applyPacketV2(root,campaignPath,"SFC-001","packet.json"); assert.equal((await preflightCampaignV2(root,campaignPath,"SFC-001")).handoff_ready,true); const handoff=await handoffCampaignV2(root,campaignPath,"SFC-001"); assert.ok(handoff.contract_sha256); await assert.rejects(readFile(path.join(handoff.workdir,"task-state.json")),/ENOENT/); assert.match(await readFile(path.join(handoff.workdir,"product-architecture-source.yaml"),"utf8"),/product-source-v2/); await runLongTaskFinalGate(handoff.workdir); const projected=await recordCampaignResultV2(root,campaignPath,"SFC-001",path.relative(root,handoff.workdir)); assert.equal(projected.workflow_status,"accepted"); });

test("V1 packet is rejected without compatibility parsing", async () => { const root=await mkdtemp(path.join(os.tmpdir(),"campaign-v1-")); await writeHappyContract(root); await writeFile(path.join(root,"request.md"),"Build\n"); await createCampaignV2(root,"campaign-2","request.md"); const campaignPath=path.join(root,".codex","composite-long-task","campaigns","campaign-2"); await writeFile(path.join(root,"scope.json"),JSON.stringify({schema_version:"scope-fit-result-v2",selected_slice_id:"SFC-001"})); await applyScopeV2(root,campaignPath,"scope.json"); await writeFile(path.join(root,"packet.json"),JSON.stringify({schema_version:"composite-authoring-packet-v1"})); await assert.rejects(applyPacketV2(root,campaignPath,"SFC-001","packet.json"),/V1 packets are not supported/); });
test("campaign inputs cannot escape the repository",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"campaign-path-"));const outside=path.join(path.dirname(root),"outside-request.md");await writeFile(outside,"escape");await assert.rejects(()=>createCampaignV2(root,"campaign-escape",outside),/safe repository-relative path|outside repository|escapes/i);});
test("campaign request rejects raw credentials before creating state",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"campaign-secret-"));await writeFile(path.join(root,"request.md"),"api_key = abcdefghijklmnop");await assert.rejects(()=>createCampaignV2(root,"campaign-secret","request.md"),/raw credential/);await assert.rejects(readFile(path.join(root,".codex/composite-long-task/campaigns/campaign-secret/campaign.yaml")),/ENOENT/);});
