import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { addSecondRequirementBranch, observationV2OracleScript, writeHappyV3Contract } from "./long-task-v3-fixtures.mjs";
import { compileLongTaskContract } from "../../packages/ty-context/dist/lib/long-task-contract-compiler.js";
import { verifyLongTask } from "../../packages/ty-context/dist/lib/long-task-verifier.js";
import { runLongTaskFinalGate } from "../../packages/ty-context/dist/lib/long-task-final-gate.js";

test("active verifier executes only frozen argv and happy final uses one snapshot", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "ltw-verify-")); const workdir = await writeHappyV3Contract(root); await compileLongTaskContract(workdir, root); const run = await verifyLongTask(workdir); assert.equal(run.findings.length, 0); assert.deepEqual(run.spec_results[0].assertion_results, { "PA-001": true, "NA-001": true }); const final = await runLongTaskFinalGate(workdir); assert.equal(final.workflow_status, "accepted"); assert.equal(final.workspace_hash_before, final.final_snapshot_sha256); });
test("oracle drift invalidates the compiled contract", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "ltw-drift-")); const workdir = await writeHappyV3Contract(root); await compileLongTaskContract(workdir, root); await writeFile(path.join(root, "tests", "acceptance", "oracle.mjs"), "console.log('changed')\n"); await assert.rejects(verifyLongTask(workdir), /oracle_changed_after_compile/); });
test("command_exit_zero_but_assertion_failed", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "ltw-fail-")); const workdir = await writeHappyV3Contract(root); await writeFile(path.join(root, "tests", "acceptance", "oracle.mjs"),observationV2OracleScript("wrong")); await compileLongTaskContract(workdir, root); const run = await verifyLongTask(workdir); assert.equal(run.spec_results[0].status, "failed"); const final = await runLongTaskFinalGate(workdir); assert.equal(final.workflow_status, "needs_work"); });
test("negative_evidence_hit is attributed through the frozen negative assertion", async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-negative-"));const workdir=await writeHappyV3Contract(root);await writeFile(path.join(root,"tests/acceptance/oracle.mjs"),observationV2OracleScript("forbidden"));await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.ok(run.findings.some((f)=>f.category==="assertion_failed"&&f.forbidden_shortcut==="FS-001"));});
test("handwritten_assertion_result is not read",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-handwritten-"));const workdir=await writeHappyV3Contract(root);await writeFile(path.join(workdir,"assertion-result.json"),JSON.stringify({passed:true}));await writeFile(path.join(root,"tests/acceptance/oracle.mjs"),observationV2OracleScript("wrong"));await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.equal(run.spec_results[0].status,"failed");});
test("one concrete finding is emitted for every obligation binding",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-findings-"));const workdir=await writeHappyV3Contract(root,addSecondRequirementBranch);await writeFile(path.join(root,"tests/acceptance/oracle.mjs"),observationV2OracleScript("wrong"));await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.deepEqual([...new Set(run.findings.filter((f)=>f.category==="assertion_failed").map((f)=>f.obligation_id))].sort(),["PI-001-OB-001","PI-002-OB-001"]);});
