import test from "node:test";
import assert from "node:assert/strict";
import { access, cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileLongTaskContract } from "../../packages/ty-context/dist/lib/long-task-contract-compiler.js";
import { runLongTaskFinalGate } from "../../packages/ty-context/dist/lib/long-task-final-gate.js";
import { verifyLongTask } from "../../packages/ty-context/dist/lib/long-task-verifier.js";
import { writeHappyV3Contract } from "./long-task-v3-fixtures.mjs";

const fixtures=path.join(path.dirname(fileURLToPath(import.meta.url)),"fixtures","hfc009");
const artifactOracle=`import {readFile} from "node:fs/promises";import path from "node:path";export async function observe(input){const value=await readFile(path.join(input.artifact_root,"product-result.json"),"utf8").then(v=>JSON.parse(v).value,()=>null);return {schema_version:"ty-context-observation-v2",observations:{works:{kind:"runtime_behavior",actual:{binding_id:"IB-002",capability:"value.read",value},artifact_refs:[]},forbidden:{kind:"scalar",actual:value,artifact_refs:[]}}};}`;
const observation=(value)=>({schema_version:"ty-context-observation-v2",observations:{works:{kind:"runtime_behavior",actual:{binding_id:"IB-002",capability:"value.read",value},artifact_refs:[]},forbidden:{kind:"scalar",actual:value,artifact_refs:[]}}});
function step(id,tool,target,argv=[]){return {id,tool,target,argv,cwd:".",timeout_ms:120000,environment_refs:[],output_artifact_ids:[]};}
async function consumer(name,kind){const root=await mkdtemp(path.join(os.tmpdir(),`ltw-real-${name}-`));const workdir=await writeHappyV3Contract(root,(data)=>{const spec=data.checklist.verification_specs[0];spec.timeout_ms=180000;spec.input_paths=["src/**","package.json","package-lock.json","scripts/**","tests/**","playwright.config.mjs","vitest.config.mjs"];spec.artifact_globs=["product-result.json","dist/**",".last-run.json","**/trace.zip"];if(kind==="npm")spec.command_steps=[step("CMD-NPM","package_script","verify:npm")];if(kind==="build")spec.command_steps=[step("CMD-BUILD","package_script","verify:build")];if(kind==="vitest")spec.command_steps=[step("CMD-VITEST","project_binary","vitest",["run","tests/vitest.test.mjs","--config=vitest.config.mjs","--pool=forks","--fileParallelism=false"]),step("CMD-MARK","node_script","scripts/mark-success.mjs")];if(kind==="jest")spec.command_steps=[step("CMD-JEST","project_binary","jest",["--runInBand","tests/jest.test.cjs"]),step("CMD-MARK","node_script","scripts/mark-success.mjs")];if(kind==="playwright")spec.command_steps=[step("CMD-PLAYWRIGHT","playwright_test","tests/playwright.spec.mjs",["--config=playwright.config.mjs","--project=chromium"])];if(kind==="workspace")spec.command_steps=[step("CMD-WORKSPACE","package_script","verify:workspace")];});await cp(path.join(fixtures,kind==="workspace"?"npm-workspace":"real-consumer"),root,{recursive:true});await writeFile(path.join(root,"tests","acceptance","oracle.mjs"),artifactOracle);return {root,workdir};}

for(const [name,kind] of [["real npm dependency import","npm"],["real project build artifact","build"],["current compatible Vitest","vitest"],["current compatible Jest","jest"],["real Playwright Chromium route","playwright"],["npm workspace cross-package execution","workspace"]])test(name,async()=>{const x=await consumer(kind,kind);const contract=await compileLongTaskContract(x.workdir,x.root);const result=await runLongTaskFinalGate(x.workdir);assert.equal(result.workflow_status,"accepted");assert.equal(contract.dependency_plan.required,true);assert.ok(result.dependency_layer_keys.length>0);if(kind==="playwright"){assert.equal(result.browser_layer_keys.length,1);const key=result.browser_layer_keys[0];const browserRoot=path.join(os.tmpdir(),"project-tiny-context-harness-host-v3","browsers","layers",key);const manifest=JSON.parse(await readFile(path.join(browserRoot,"layer-manifest.json"),"utf8"));assert.equal(manifest.key,key);assert.equal(manifest.playwright_package.version,"1.61.1");assert.ok(manifest.browser_components.some((item)=>item.name==="chromium"&&item.revision));assert.ok(manifest.executables.length>0);assert.ok(manifest.executables.every((item)=>item.sha256&&item.path&&!path.isAbsolute(item.path)));const artifacts=JSON.parse(await readFile(path.join(x.workdir,"runs",result.run_id,"command-runs","VS-AC-001","artifacts.json"),"utf8"));assert.ok(artifacts.artifacts.some((item)=>item.path.endsWith("/trace.zip")));}});

test("dependency-requiring specs fail compilation without a lockfile",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-no-lock-"));const workdir=await writeHappyV3Contract(root,(data)=>{data.checklist.verification_specs[0].command_steps=[step("CMD-BIN","project_binary","vitest",["run"])];});await assert.rejects(()=>compileLongTaskContract(workdir,root),/dependency_lockfile_missing/);});
test("manager priority cannot contradict packageManager",async()=>{const x=await consumer("manager-conflict","npm");const packageFile=path.join(x.root,"package.json");const value=JSON.parse(await readFile(packageFile,"utf8"));value.packageManager="npm@11.0.0";await writeFile(packageFile,JSON.stringify(value));await writeFile(path.join(x.root,"pnpm-lock.yaml"),"lockfileVersion: '9.0'\n");await assert.rejects(()=>compileLongTaskContract(x.workdir,x.root),/dependency_manager_conflict/);});
test("sealed environment variables cannot be declared or overridden",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-reserved-env-"));const workdir=await writeHappyV3Contract(root,(data)=>{data.checklist.verification_specs[0].environment_refs=["PLAYWRIGHT_BROWSERS_PATH"];});await assert.rejects(()=>compileLongTaskContract(workdir,root),/undeclared_environment_ref:reserved/);});
test("Playwright proof without a current trace is rejected",async()=>{const x=await consumer("playwright-no-trace","playwright");const config=path.join(x.root,"playwright.config.mjs");await writeFile(config,(await readFile(config,"utf8")).replace('trace: "on"','trace: "off"'));await compileLongTaskContract(x.workdir,x.root);const result=await runLongTaskFinalGate(x.workdir);assert.equal(result.workflow_status,"needs_work");assert.ok(Object.values(result.spec_results).includes("failed"));const verification=JSON.parse(await readFile(path.join(x.workdir,"runs",result.run_id,"verification-result.json"),"utf8"));assert.ok(verification.findings.some((item)=>item.category==="playwright_browser_unsealed"));});

test("Oracle cannot read undeclared host files under the sealed permission policy",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-sandbox-read-"));const secret=path.join(os.tmpdir(),`host-secret-${Date.now()}.txt`);await writeFile(secret,"outside");const workdir=await writeHappyV3Contract(root,(data)=>{data.checklist.verification_specs[0].positive_assertions[0].expected={binding_id:"IB-002",capability:"value.read",value:true};});const oracle=`import {readFile} from "node:fs/promises";export async function observe(){const value=(await readFile(${JSON.stringify(secret)},"utf8")).length>0;return {schema_version:"ty-context-observation-v2",observations:{works:{kind:"runtime_behavior",actual:{binding_id:"IB-002",capability:"value.read",value},artifact_refs:[]},forbidden:{kind:"scalar",actual:value,artifact_refs:[]}}};}`;await writeFile(path.join(root,"tests","acceptance","oracle.mjs"),oracle);await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.equal(run.spec_results[0].status,"failed");assert.ok(run.findings.some((item)=>item.category==="sandbox_access_denied"));await rm(secret,{force:true});});
test("Oracle cannot modify the original workspace or active workdir",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-sandbox-write-"));const marker=path.join(root,"ORACLE-ESCAPE.txt");const workdir=await writeHappyV3Contract(root);const oracle=`import {writeFile} from "node:fs/promises";export async function observe(){await writeFile(${JSON.stringify(marker)},"escaped");return ${JSON.stringify(observation("good"))};}`;await writeFile(path.join(root,"tests","acceptance","oracle.mjs"),oracle);await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.equal(run.spec_results[0].status,"failed");await assert.rejects(()=>access(marker));assert.ok(run.findings.some((item)=>item.category==="sandbox_access_denied"));});
