import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, readFile, writeFile, mkdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { compileLongTaskContract } from "../../packages/ty-context/dist/lib/long-task-contract-compiler.js";
import { runLongTaskFinalGate, stopCheckLongTask } from "./long-task-test-runtime.mjs";
import { addSecondRequirementBranch, observationV2OracleScript, writeHappyV3Contract } from "./long-task-v3-fixtures.mjs";

async function setup(mutate=()=>{},prepare=async()=>{}) { const root=await mkdtemp(path.join(os.tmpdir(),"ltw-final-")); const workdir=await writeHappyV3Contract(root,mutate); await prepare(root,workdir); const contract=await compileLongTaskContract(workdir,root); return {root,workdir,contract}; }
// Regression identity: blocked_message_contains_completed is exercised by the rejected blocked reply below.
test("old passed + new failed cannot be accepted",async()=>{const x=await setup(); assert.equal((await runLongTaskFinalGate(x.workdir)).workflow_status,"accepted"); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),observationV2OracleScript("wrong")); const result=await runLongTaskFinalGate(x.workdir);assert.equal(result.workflow_status,"needs_work");assert.ok(result.findings.some((item)=>item.code==="oracle_changed"));for(const map of [result.requirement_results,result.plan_item_results,result.obligation_results,result.acceptance_criterion_results,result.proof_requirement_results,result.binding_results,result.counterfactual_results])assert.ok(Object.values(map).every((item)=>item.status==="failed"));const trace=JSON.parse(await readFile(path.join(x.workdir,"runs",result.run_id,"final-trace.json"),"utf8"));assert.equal(trace.steps.length,20);assert.equal(trace.steps.find((item)=>item.step_id==="oracle_closure_freshness").status,"failed");assert.ok(trace.steps.every((item)=>item.status!=="skipped"));});
test("forged_externally_blocked",async()=>{const x=await setup(); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),`export async function observe(){return {schema_version:"ty-context-observation-v2",observations:{},external_blocker:{environment_requirement_id:"ER-FAKE"}};}\n`); await compileLongTaskContract(x.workdir,x.root); const result=await runLongTaskFinalGate(x.workdir); assert.equal(result.workflow_status,"needs_work"); assert.ok(result.findings.some((f)=>f.category==="observation_protocol_invalid"));});
test("an environment requirement cannot make Oracle-authored blocker data authoritative",async()=>{const x=await setup((d)=>{d.checklist.environment_probes.push({id:"ENV-PROBE-PRIMARY",kind:"permission",adapter:"filesystem_permission",target:"read:src/value.txt",timeout_ms:1000,expected:{exit_codes:[0],error_codes:[]},artifact_globs:[],environment_refs:[]});d.checklist.verification_specs[0].environment_requirements=[{id:"ER-001",reason_code:"mfa_required",probe_spec_id:"ENV-PROBE-PRIMARY",local_alternative_probe_ids:[],minimal_user_action:"Approve MFA challenge"}];}); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),`export async function observe(){return {schema_version:"ty-context-observation-v2",observations:{},external_blocker:{environment_requirement_id:"ER-001"}};}\n`); await compileLongTaskContract(x.workdir,x.root); const result=await runLongTaskFinalGate(x.workdir); assert.equal(result.workflow_status,"needs_work");assert.equal((await stopCheckLongTask(x.workdir,"completed")).decision,"block");});
test("handwritten accepted final cannot bypass Stop",async()=>{const x=await setup(); const valid=await runLongTaskFinalGate(x.workdir); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),observationV2OracleScript("wrong")); const forged={...valid,workflow_status:"accepted"}; await writeFile(path.join(x.workdir,"final-result.json"),JSON.stringify(forged)); const stop=await stopCheckLongTask(x.workdir,"done"); assert.equal(stop.decision,"block");});
test("final_result_copied_from_other_task",async()=>{const a=await setup();const b=await setup();const result=await runLongTaskFinalGate(a.workdir);const envelope=await readFile(path.join(a.workdir,"final-result.json"));const trace=await readFile(path.join(a.workdir,"runs",result.run_id,"final-trace.json"));await mkdir(path.join(b.workdir,"runs",result.run_id),{recursive:true});await writeFile(path.join(b.workdir,"final-result.json"),envelope);await writeFile(path.join(b.workdir,"runs",result.run_id,"final-trace.json"),trace);const stop=await stopCheckLongTask(b.workdir,"done");assert.equal(stop.decision,"block");assert.match(stop.reason,/copied_result_rejected|final_result_hash_mismatch/);});
test("worktree_changed_during_final",async()=>{const x=await setup();await mkdir(path.join(x.root,"src"),{recursive:true});const live=path.join(x.root,"src/live.txt");await writeFile(live,"before");await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),observationV2OracleScript("good","IB-002","value.read",4000));await compileLongTaskContract(x.workdir,x.root);const gate=runLongTaskFinalGate(x.workdir);await mutateAfterFinalSnapshot(x.workdir,live);const result=await gate;assert.equal(result.workflow_status,"needs_work");assert.ok(result.findings.some((f)=>f.code==="workspace_changed_during_final"));});
test("partial AC pass cannot be accepted",async()=>{const x=await setup((d)=>{addSecondRequirementBranch(d);const second=d.checklist.verification_specs.find((spec)=>spec.id==="VS-AC-002");second.oracle.entrypoint="tests/acceptance/oracle-2.mjs";second.command_steps[0].target="tests/acceptance/oracle-2.mjs";},async(root)=>writeFile(path.join(root,"tests/acceptance/oracle-2.mjs"),observationV2OracleScript("wrong","IB-004","value.secondary")));const result=await runLongTaskFinalGate(x.workdir);assert.equal(result.workflow_status,"needs_work");assert.equal(result.acceptance_criterion_results["AC-001"].status,"passed");assert.equal(result.acceptance_criterion_results["AC-002"].status,"failed");});

function mutateAfterFinalSnapshot(workdir,file){const source=String.raw`const fs=require("node:fs"),path=require("node:path");const [workdir,file]=process.argv.slice(1);const runs=path.join(workdir,"runs"),deadline=Date.now()+30000,wait=new Int32Array(new SharedArrayBuffer(4));while(Date.now()<deadline){try{for(const name of fs.readdirSync(runs)){if(fs.existsSync(path.join(runs,name,"snapshot-manifest.json"))){fs.writeFileSync(file,"during");process.exit(0)}}}catch{}Atomics.wait(wait,0,0,10)}process.exit(2);`;return new Promise((resolve,reject)=>{const child=spawn(process.execPath,["-e",source,workdir,file],{stdio:"ignore",windowsHide:true});child.once("error",reject);child.once("exit",(code)=>code===0?resolve():reject(new Error(`snapshot mutation helper exited ${code}`)));});}
