import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { compileLongTaskContract } from "../../packages/ty-context/dist/lib/long-task-contract-compiler.js";
import { verifyLongTask } from "../../packages/ty-context/dist/lib/long-task-verifier.js";
import { LongTaskRedactorV3 } from "../../packages/ty-context/dist/lib/long-task-redaction.js";
import { __deleteWindowsCredentialForTest, __writeWindowsCredentialForTest, repositorySecretId, resolveLongTaskSecrets, windowsCredentialTarget } from "../../packages/ty-context/dist/lib/long-task-secret-provider.js";
import { writeHappyV3Contract } from "./long-task-v3-fixtures.mjs";

test("redactor covers raw and encoded variants across chunk boundaries",()=>{const secret=`fixture ${randomUUID()}/+?\"`;const ref="HFC009_SECRET";const redactor=new LongTaskRedactorV3({[ref]:secret});const bytes=Buffer.from(secret);const variants=[secret,encodeURIComponent(secret),encodeURIComponent(secret).replace(/%20/gu,"+"),JSON.stringify(secret).slice(1,-1),bytes.toString("base64"),bytes.toString("base64url"),bytes.toString("hex"),`${ref}=${secret}`];for(const variant of variants)assert.doesNotMatch(redactor.redactText(`before:${variant}:after`),new RegExp(escapeRegExp(variant),"u"));const stream=redactor.stream();const raw=Buffer.from(`left-${secret}-right`);const pieces=[];for(let offset=0;offset<raw.length;offset+=3)pieces.push(stream.push(raw.subarray(offset,offset+3)));pieces.push(stream.finish());const output=Buffer.concat(pieces).toString("utf8");assert.equal(output,`left-[REDACTED:${ref}]-right`);});

test("Windows Credential Manager provider resolves a real generic credential",{skip:process.platform!=="win32"},async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-secret-provider-"));await writeHappyV3Contract(root);const repositoryId=await repositorySecretId(root);const target=windowsCredentialTarget(repositoryId,"HFC009_SECRET");const secret=`provider-${randomUUID()}`;await __writeWindowsCredentialForTest(target,secret);try{const resolved=await resolveLongTaskSecrets(root,["HFC009_SECRET"],"salt");assert.equal(resolved.values.HFC009_SECRET,secret);assert.deepEqual(resolved.refs.map(({name,provider,present})=>({name,provider,present})),[{name:"HFC009_SECRET",provider:"windows-credential-manager",present:true}]);assert.ok(resolved.refs[0].fingerprint);assert.doesNotMatch(JSON.stringify(resolved.refs),new RegExp(escapeRegExp(secret),"u"));}finally{await __deleteWindowsCredentialForTest(target);}});

test("declared secret is step-scoped and every retained text/log rendering is redacted",{skip:process.platform!=="win32"},async()=>{const fixture=await secretFixture("text");try{const run=await verifyWithoutHostLeak(fixture.workdir);assert.equal(run.spec_results[0].status,"passed");assert.equal(run.environment.secret_refs?.[0].name,"HFC009_SECRET");assert.equal(run.environment.secret_refs?.[0].present,true);const runRoot=path.join(fixture.workdir,"runs",run.run_id);const retained=await readTree(runRoot);for(const variant of fixture.variants)assert.equal(retained.includes(variant),false);assert.match(retained,/\[REDACTED:HFC009_SECRET\]/u);assert.match(await readFile(path.join(runRoot,"artifacts","VS-AC-001","redacted.txt"),"utf8"),/\[REDACTED:HFC009_SECRET\]/u);}finally{await __deleteWindowsCredentialForTest(fixture.target);}});

test("binary secret leak is destroyed and fails closed",{skip:process.platform!=="win32"},async()=>{const fixture=await secretFixture("binary");try{const run=await verifyWithoutHostLeak(fixture.workdir);assert.equal(run.spec_results[0].status,"failed");assert.ok(run.findings.some((item)=>item.category==="secret_leak_detected"));const runRoot=path.join(fixture.workdir,"runs",run.run_id);const retained=await readTree(runRoot);for(const variant of fixture.variants)assert.equal(retained.includes(variant),false);assert.match(retained,/destroyed_after_detection/u);}finally{await __deleteWindowsCredentialForTest(fixture.target);}});

async function secretFixture(kind){const root=await mkdtemp(path.join(os.tmpdir(),`ltw-secret-${kind}-`));const workdir=await writeHappyV3Contract(root,(data)=>{const spec=data.checklist.verification_specs[0];spec.input_paths=["src/**","scripts/**","tests/acceptance/**"];spec.artifact_globs=["product-result.json",kind==="text"?"redacted.txt":"binary.bin"];spec.environment_refs=["HFC009_SECRET"];spec.command_steps=[{id:"CMD-NO-SECRET",tool:"node_script",target:"scripts/no-secret.mjs",argv:[],cwd:".",timeout_ms:10000,environment_refs:[],output_artifact_ids:[]},{id:"CMD-SECRET",tool:"node_script",target:`scripts/secret-${kind}.mjs`,argv:[],cwd:".",timeout_ms:10000,environment_refs:["HFC009_SECRET"],output_artifact_ids:[]}];data.checklist.environment_probes.push({id:"ENV-PROBE-SECRET",kind:"secret_ref",adapter:"credential_store",target:"HFC009_SECRET",timeout_ms:10000,expected:{exit_codes:[0],error_codes:[]},artifact_globs:[],environment_refs:["HFC009_SECRET"]});});await mkdir(path.join(root,"scripts"),{recursive:true});await writeFile(path.join(root,"scripts","no-secret.mjs"),`if(process.env.HFC009_SECRET)throw new Error("undeclared secret injected");`);const oracle=`import {readFile} from "node:fs/promises";import path from "node:path";export async function observe(input){const value=await readFile(path.join(input.artifact_root,"product-result.json"),"utf8").then(item=>JSON.parse(item).value,()=>null);return {schema_version:"ty-context-observation-v2",observations:{works:{kind:"runtime_behavior",actual:{binding_id:"IB-002",capability:"value.read",value},artifact_refs:[]},forbidden:{kind:"scalar",actual:value,artifact_refs:[]}}};}`;await writeFile(path.join(root,"tests","acceptance","oracle.mjs"),oracle);const secret=`Secret ${randomUUID()}/+?\"`;const bytes=Buffer.from(secret);const variants=[secret,encodeURIComponent(secret),encodeURIComponent(secret).replace(/%20/gu,"+"),JSON.stringify(secret).slice(1,-1),bytes.toString("base64"),bytes.toString("base64url"),bytes.toString("hex"),`HFC009_SECRET=${secret}`];const common=`import {mkdir,writeFile} from "node:fs/promises";import path from "node:path";const secret=process.env.HFC009_SECRET;if(!secret)throw new Error("missing declared secret");const raw=Buffer.from(secret);const variants=[secret,encodeURIComponent(secret),encodeURIComponent(secret).replace(/%20/gu,"+"),JSON.stringify(secret).slice(1,-1),raw.toString("base64"),raw.toString("base64url"),raw.toString("hex"),\`HFC009_SECRET=\${secret}\`];console.log(variants.slice(0,4).join("\\n"));console.error(variants.slice(4).join("\\n"));await mkdir(process.env.TY_CONTEXT_ARTIFACT_DIR,{recursive:true});await writeFile(path.join(process.env.TY_CONTEXT_ARTIFACT_DIR,"product-result.json"),JSON.stringify({value:"good"}));`;
  await writeFile(path.join(root,"scripts",`secret-${kind}.mjs`),kind==="text"?`${common}await writeFile(path.join(process.env.TY_CONTEXT_ARTIFACT_DIR,"redacted.txt"),variants.join("\\n"));`:`${common}await writeFile(path.join(process.env.TY_CONTEXT_ARTIFACT_DIR,"binary.bin"),Buffer.concat([Buffer.from([0,1,2]),raw]));`);await compileLongTaskContract(workdir,root);const repositoryId=await repositorySecretId(root);const target=windowsCredentialTarget(repositoryId,"HFC009_SECRET");await __writeWindowsCredentialForTest(target,secret);return {root,workdir,target,variants};}
async function readTree(root){const chunks=[];async function visit(directory){for(const entry of await readdir(directory,{withFileTypes:true})){const file=path.join(directory,entry.name);if(entry.isDirectory())await visit(file);else if(entry.isFile())chunks.push(await readFile(file).then((value)=>value.toString("utf8")));}}await visit(root);return chunks.join("\n");}
async function verifyWithoutHostLeak(workdir){const previous=process.env.HFC009_UNDECLARED_HOST;const hostValue=`host-${randomUUID()}`;process.env.HFC009_UNDECLARED_HOST=hostValue;try{const run=await verifyLongTask(workdir);assert.equal(run.environment.environment_keys.includes("HFC009_UNDECLARED_HOST"),false);assert.equal((await readTree(path.join(workdir,"runs",run.run_id))).includes(hostValue),false);return run;}finally{if(previous===undefined)delete process.env.HFC009_UNDECLARED_HOST;else process.env.HFC009_UNDECLARED_HOST=previous;}}
function escapeRegExp(value){return value.replace(/[.*+?^${}()|[\]\\]/gu,"\\$&");}
