import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { writeHappyContract } from "./long-task-v2-fixtures.mjs";
import { compileLongTaskContract } from "../../packages/ty-context/dist/lib/long-task-contract-compiler.js";
import { verifyLongTask } from "../../packages/ty-context/dist/lib/long-task-verifier.js";
import { runLongTaskFinalGate } from "../../packages/ty-context/dist/lib/long-task-final-gate.js";

test("active verifier executes only frozen argv and happy final uses one snapshot", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "ltw-verify-")); const workdir = await writeHappyContract(root); await compileLongTaskContract(workdir, root); const run = await verifyLongTask(workdir); assert.equal(run.findings.length, 0); assert.deepEqual(run.spec_results[0].assertion_results, { "PA-001": true, "NA-001": true }); const final = await runLongTaskFinalGate(workdir); assert.equal(final.workflow_status, "accepted"); assert.equal(final.workspace_hash_before, final.final_snapshot_sha256); });
test("oracle drift invalidates the compiled contract", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "ltw-drift-")); const workdir = await writeHappyContract(root); await compileLongTaskContract(workdir, root); await writeFile(path.join(root, "tests", "acceptance", "oracle.mjs"), "console.log('changed')\n"); await assert.rejects(verifyLongTask(workdir), /oracle_changed_after_compile/); });
test("command_exit_zero_but_assertion_failed", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "ltw-fail-")); const workdir = await writeHappyContract(root); await writeFile(path.join(root, "tests", "acceptance", "oracle.mjs"), `console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:false},forbidden:{passed:true}}}))\n`); await compileLongTaskContract(workdir, root); const run = await verifyLongTask(workdir); assert.equal(run.spec_results[0].status, "failed"); const final = await runLongTaskFinalGate(workdir); assert.equal(final.workflow_status, "needs_work"); });
test("negative_evidence_hit", async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-negative-"));const workdir=await writeHappyContract(root);await writeFile(path.join(root,"tests/acceptance/oracle.mjs"),`console.log("file exists");console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:true},forbidden:{passed:true}}}))\n`);await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.ok(run.findings.some((f)=>f.category==="negative_evidence_hit"));});
test("handwritten_assertion_result is not read",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-handwritten-"));const workdir=await writeHappyContract(root);await writeFile(path.join(workdir,"assertion-result.json"),JSON.stringify({passed:true}));await writeFile(path.join(root,"tests/acceptance/oracle.mjs"),`console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:false},forbidden:{passed:true}}}))\n`);await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.equal(run.spec_results[0].status,"failed");});
test("one concrete finding is emitted for every obligation binding",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-findings-"));const workdir=await writeHappyContract(root,(d)=>{d.product.requirements.push({...structuredClone(d.product.requirements[0]),id:"PR-002",statement:"Second requirement"});const original=structuredClone(d.plan.plan_items[0].obligations[0]);d.plan.plan_items[0].obligations.push({...original,id:"PI-001-OB-002",source_requirement_ids:["PR-002"],forbidden_shortcuts:[]});d.checklist.acceptance_criteria[0].obligation_refs.push("PI-001-OB-002");});await writeFile(path.join(root,"tests/acceptance/oracle.mjs"),`console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:false},forbidden:{passed:true}}}))\n`);await compileLongTaskContract(workdir,root);const run=await verifyLongTask(workdir);assert.deepEqual([...new Set(run.findings.filter((f)=>f.category==="runtime_behavior_failed").map((f)=>f.obligation_id))].sort(),["PI-001-OB-001","PI-001-OB-002"]);});
