import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { chmod, cp, lstat, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileDependencyPlan, detectDependencyLock } from "../../packages/ty-context/dist/lib/long-task-dependency-key.js";
import { prepareDependencyLayer } from "../../packages/ty-context/dist/lib/long-task-dependency-layer.js";
import { dependencyInstallArgv } from "../../packages/ty-context/dist/lib/long-task-package-manager.js";
import { nodePermissionPathVariants } from "../../packages/ty-context/dist/lib/long-task-sandbox-node.js";
import { LONG_TASK_BROWSER_INSTALL_POLICY_SHA256, verifyBrowserLayerAtPath } from "../../packages/ty-context/dist/lib/long-task-browser-layer.js";
import { canonicalJson, sha256Hex } from "../../packages/ty-context/dist/lib/composite-campaign-codec.js";

const fixture=path.join(path.dirname(fileURLToPath(import.meta.url)),"fixtures","hfc009","layer-unit");
const command=(tool,target)=>({command_steps:[{tool,target,cwd:"."}]});

test("manager priority and exact immutable install argv are frozen",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-manager-priority-"));for(const file of ["pnpm-lock.yaml","yarn.lock","package-lock.json","bun.lock","bun.lockb"])await writeFile(path.join(root,file),"");assert.equal((await detectDependencyLock(root,"pnpm@10.0.0")).selected.name,"pnpm");await rm(path.join(root,"pnpm-lock.yaml"));assert.equal((await detectDependencyLock(root,"yarn@4.0.0")).selected.name,"yarn");await rm(path.join(root,"yarn.lock"));assert.equal((await detectDependencyLock(root,"npm@11.0.0")).selected.name,"npm");await rm(path.join(root,"package-lock.json"));assert.equal((await detectDependencyLock(root,"bun@1.0.0")).selected.file,"bun.lock");assert.deepEqual(dependencyInstallArgv("pnpm"),["install","--frozen-lockfile"]);assert.deepEqual(dependencyInstallArgv("yarn"),["install","--immutable"]);assert.deepEqual(dependencyInstallArgv("npm"),["ci"]);assert.deepEqual(dependencyInstallArgv("bun"),["install","--frozen-lockfile"]);});

test("macOS Node permission paths cover the equivalent private system alias",()=>{assert.deepEqual(nodePermissionPathVariants("/var/folders/example","darwin"),["/private/var/folders/example","/var/folders/example"]);assert.deepEqual(nodePermissionPathVariants("/private/tmp/example","darwin"),["/private/tmp/example","/tmp/example"]);assert.deepEqual(nodePermissionPathVariants("/Users/example","darwin"),["/Users/example"]);});

test("dependency key follows Appendix inputs and ignores selected consumer binary",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-dependency-key-"));await cp(fixture,root,{recursive:true});const vitest=await compileDependencyPlan(root,[command("project_binary","vitest")]);const jest=await compileDependencyPlan(root,[command("project_binary","jest")]);assert.equal(vitest.key,jest.key);assert.notDeepEqual(vitest.required_project_binaries,jest.required_project_binaries);const packageFile=path.join(root,"package.json");const manifest=JSON.parse(await readFile(packageFile,"utf8"));manifest.description="key-changing manifest input";await writeFile(packageFile,JSON.stringify(manifest));const changed=await compileDependencyPlan(root,[command("project_binary","jest")]);assert.notEqual(changed.key,jest.key);});

test("one create-only builder serves concurrent consumers and a corrupt layer is quarantined then rebuilt",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-layer-cache-"));await cp(fixture,root,{recursive:true});const plan=await compileDependencyPlan(root,[command("package_script","verify")]);const cache=path.join(os.tmpdir(),"project-tiny-context-harness-host-v3","dependencies");const layerRoot=path.join(cache,"layers",plan.key);const lock=path.join(cache,"locks",`${plan.key}.lock`);await rm(layerRoot,{recursive:true,force:true});await rm(lock,{force:true});const [first,second]=await Promise.all([prepareDependencyLayer(root,plan),prepareDependencyLayer(root,plan)]);assert.ok(first&&second);assert.equal(first.key,second.key);assert.equal(first.manifest.created_at,second.manifest.created_at);assert.equal(first.manifest.packages.some((item)=>item.name==="lodash-es"&&item.version==="4.18.1"),true);const file=path.join(first.root,"payload","node_modules","lodash-es","chunk.js");const original=await readFile(file);assert.equal((await lstat(file)).mode&0o222,0);const privileged=typeof process.getuid==="function"&&process.getuid()===0;if(!privileged)await assert.rejects(()=>writeFile(file,Buffer.concat([original,Buffer.from("corrupt")])));await chmod(file,0o666);await writeFile(file,Buffer.concat([original,Buffer.from("corrupt")]));const rebuilt=await prepareDependencyLayer(root,plan);assert.ok(rebuilt);assert.deepEqual(await readFile(file),original);assert.equal((await lstat(file)).mode&0o222,0);if(!privileged)await assert.rejects(()=>writeFile(file,Buffer.concat([original,Buffer.from("write")])));const quarantined=await readdir(path.join(cache,"quarantine"));assert.ok(quarantined.some((name)=>name.startsWith(`${plan.key}.`)));});

test("a first dependency install creates its manager cache before Node permission enforcement",{timeout:120_000},async()=>{const isolated=await mkdtemp(path.join(os.tmpdir(),"ltw-cold-manager-cache-"));const helper=path.join(path.dirname(fileURLToPath(import.meta.url)),"fixtures","hfc009","cold-dependency-cache.mjs");try{const result=await runChild(helper,{...process.env,TMPDIR:isolated,TMP:isolated,TEMP:isolated});assert.equal(result.code,0,`${result.stdout}\n${result.stderr}`);}finally{await makeWritable(isolated);await rm(isolated,{recursive:true,force:true});}});

test("browser layer verifies executable content identity and rejects corruption",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ltw-browser-corrupt-"));const payload=path.join(root,"payload");await mkdir(payload,{recursive:true});const executable=path.join(payload,"browser.exe");const bytes=Buffer.from("sealed-browser-binary");await writeFile(executable,bytes);await chmod(executable,0o444);const info=await lstat(executable);const requestKey=sha256Hex("browser-request");const executableHashes=[{path:"browser.exe",sha256:sha256Hex(bytes)}];const key=sha256Hex(canonicalJson({request_key:requestKey,executable_hashes:executableHashes}));const manifest={schema_version:"long-task-browser-layer-v3",key,request_key:requestKey,dependency_layer_key:"dependency",playwright_package:{name:"playwright",version:"1.61.1",integrity:"sha512-fixture",browsers_json_sha256:sha256Hex("browsers")},browser_components:[{name:"chromium",revision:"fixture",browser_version:null,descriptor_sha256:sha256Hex("descriptor")}],platform:{platform:process.platform,release:os.release(),arch:process.arch,libc_abi:"fixture"},install_policy_sha256:LONG_TASK_BROWSER_INSTALL_POLICY_SHA256,executables:[{...executableHashes[0],size:bytes.length}],files:[{path:"browser.exe",type:"file",mode:info.mode,size:bytes.length,sha256:sha256Hex(bytes)}],install:{exit_code:0,stdout_sha256:sha256Hex(""),stderr_sha256:sha256Hex("")},created_at:new Date().toISOString()};await writeFile(path.join(root,"layer-manifest.json"),canonicalJson(manifest));await verifyBrowserLayerAtPath(root,key,requestKey);await chmod(executable,0o666);await writeFile(executable,Buffer.from("corrupt"));await assert.rejects(()=>verifyBrowserLayerAtPath(root,key,requestKey),/browser_layer_corrupt:.*:merkle/);});

function runChild(script,env){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[script],{env,stdio:["ignore","pipe","pipe"],windowsHide:true});const stdout=[];const stderr=[];child.stdout.on("data",(chunk)=>stdout.push(chunk));child.stderr.on("data",(chunk)=>stderr.push(chunk));child.once("error",reject);child.once("close",(code)=>resolve({code:code??-1,stdout:Buffer.concat(stdout).toString("utf8"),stderr:Buffer.concat(stderr).toString("utf8")}));});}
async function makeWritable(file){let info;try{info=await lstat(file);}catch{return;}if(info.isDirectory()){await chmod(file,0o755);for(const entry of await readdir(file))await makeWritable(path.join(file,entry));}else if(!info.isSymbolicLink())await chmod(file,0o644);}
