import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { applyCounterfactualMutation, hashCounterfactualTree } from "../../packages/ty-context/dist/lib/long-task-counterfactual-mutation.js";

async function setup(){const root=await mkdtemp(path.join(os.tmpdir(),"ltw-mutation-"));await Promise.all([mkdir(path.join(root,"src","nested"),{recursive:true}),mkdir(path.join(root,"fixtures"),{recursive:true})]);await Promise.all([writeFile(path.join(root,"src","a.txt"),"good"),writeFile(path.join(root,"src","nested","b.ts"),"good"),writeFile(path.join(root,"src","route.ts"),'const route="/old";'),writeFile(path.join(root,"fixtures","bad.txt"),"bad"),writeFile(path.join(root,"fixtures","env.txt"),"counterexample")]);return root;}
function contract(){const implementation_bindings=[{id:"IB-FILE",kind:"file",target:"src/a.txt",verification:{mode:"harness_static"}},{id:"IB-GLOB",kind:"path_glob",target:"src/**/*.ts",verification:{mode:"harness_static"}},{id:"IB-ROUTE",kind:"route",target:"/old",verification:{mode:"oracle_observation",spec_id:"VS",observation_id:"route"}}];return {obligations:[{id:"PI-001-OB-001",implementation_bindings}],counterexample_fixtures:[{id:"FX-BAD",path:"fixtures/bad.txt",non_secret:true},{id:"FX-ENV",path:"fixtures/env.txt",non_secret:true}],verification_specs:[{id:"VS",claims:{obligation_ids:["PI-001-OB-001"],binding_ids:["IB-FILE","IB-GLOB","IB-ROUTE"]},input_paths:["src/**"],environment_refs:["MODE"]}]};}
const control=(mutation)=>({id:"CF-001",obligation_ids:["PI-001-OB-001"],mutation,expected_failed_assertion_ids:["PA-001"]});

test("all five counterfactual mutation tags make byte-recorded effects",async(t)=>{
  await t.test("remove binding targets",async()=>{const root=await setup();const before=await hashCounterfactualTree(root);const value=await applyCounterfactualMutation(contract(),control({type:"remove_binding_targets",binding_ids:["IB-FILE"]}),root);assert.equal(value.finding_codes.length,0);assert.equal(value.mutation_effects[0].after,"deleted");assert.notEqual(await hashCounterfactualTree(root),before);});
  await t.test("replace file with fixture",async()=>{const root=await setup();const value=await applyCounterfactualMutation(contract(),control({type:"replace_file_with_fixture",binding_id:"IB-FILE",target_path:"src/a.txt",fixture_id:"FX-BAD"}),root);assert.equal(value.finding_codes.length,0);assert.equal(await readFile(path.join(root,"src","a.txt"),"utf8"),"bad");});
  await t.test("declared counterexample fixture",async()=>{const root=await setup();const value=await applyCounterfactualMutation(contract(),control({type:"use_declared_counterexample_fixture",binding_id:"IB-FILE",target_path:"src/a.txt",fixture_id:"FX-BAD"}),root);assert.equal(value.finding_codes.length,0);assert.equal(value.mutation_effects.length,1);});
  await t.test("rename one exact route token",async()=>{const root=await setup();const value=await applyCounterfactualMutation(contract(),control({type:"rename_route_fixture",binding_id:"IB-ROUTE",target_path:"src/route.ts",fixture_id:"FX-BAD",from_route:"/old",to_route:"/counterexample"}),root);assert.equal(value.finding_codes.length,0);assert.match(await readFile(path.join(root,"src","route.ts"),"utf8"),/counterexample/);});
  await t.test("override declared non-secret environment ref",async()=>{const root=await setup();const value=await applyCounterfactualMutation(contract(),control({type:"override_environment_fixture",environment_ref:"MODE",fixture_id:"FX-ENV"}),root);assert.equal(value.finding_codes.length,0);assert.equal(value.environment_overrides.MODE,"counterexample");});
});
test("wrong ownership and zero-effect mutation fail closed",async()=>{const root=await setup();const wrong=await applyCounterfactualMutation(contract(),control({type:"remove_binding_targets",binding_ids:["IB-WRONG"]}),root);assert.deepEqual(wrong.finding_codes,["counterfactual_wrong_binding_target"]);await writeFile(path.join(root,"src","a.txt"),"bad");const noEffect=await applyCounterfactualMutation(contract(),control({type:"replace_file_with_fixture",binding_id:"IB-FILE",target_path:"src/a.txt",fixture_id:"FX-BAD"}),root);assert.deepEqual(noEffect.finding_codes,["counterfactual_mutation_no_effect"]);});
