import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile, mkdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { compileLongTaskContract } from "../../packages/ty-context/dist/lib/long-task-contract-compiler.js";
import { runLongTaskFinalGate } from "../../packages/ty-context/dist/lib/long-task-final-gate.js";
import { stopCheckLongTask } from "../../packages/ty-context/dist/lib/long-task-stop-check.js";
import { addSecondRequirementBranch, writeHappyV3Contract } from "./long-task-v3-fixtures.mjs";

async function setup(mutate=()=>{},prepare=async()=>{}) { const root=await mkdtemp(path.join(os.tmpdir(),"ltw-final-")); const workdir=await writeHappyV3Contract(root,mutate); await prepare(root,workdir); const contract=await compileLongTaskContract(workdir,root); return {root,workdir,contract}; }
// Regression identity: blocked_message_contains_completed is exercised by the rejected blocked reply below.
test("old passed + new failed cannot be accepted",async()=>{const x=await setup(); assert.equal((await runLongTaskFinalGate(x.workdir)).workflow_status,"accepted"); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),`console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:false},forbidden:{passed:true}}}))\n`); await assert.rejects(()=>runLongTaskFinalGate(x.workdir),/oracle_changed_after_compile/);});
test("forged_externally_blocked",async()=>{const x=await setup(); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),`console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{},external_blocker:{environment_requirement_id:"ER-FAKE",reason_code:"mfa_required",attempted_local_alternatives:[]}}))\n`); await compileLongTaskContract(x.workdir,x.root); const result=await runLongTaskFinalGate(x.workdir); assert.equal(result.workflow_status,"needs_work"); assert.ok(result.findings.some((f)=>f.category==="forged_externally_blocked"));});
test("trusted externally_blocked requires frozen probe evidence",async()=>{const x=await setup((d)=>{d.checklist.environment_probes.push({id:"ENV-PROBE-PRIMARY",kind:"host_capability",adapter:"cli_auth",target:"fixture",timeout_ms:1000,expected:{exit_codes:[0],error_codes:[]},artifact_globs:[],environment_refs:[]},{id:"ENV-PROBE-ALT",kind:"host_capability",adapter:"cli_auth",target:"fixture-alt",timeout_ms:1000,expected:{exit_codes:[0],error_codes:[]},artifact_globs:[],environment_refs:[]});d.checklist.verification_specs[0].environment_requirements=[{id:"ER-001",reason_code:"mfa_required",probe_spec_id:"ENV-PROBE-PRIMARY",local_alternative_probe_ids:["ENV-PROBE-ALT"],minimal_user_action:"Approve MFA challenge"}];}); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),`console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{},external_blocker:{environment_requirement_id:"ER-001",reason_code:"mfa_required",actual:"challenge pending",attempted_local_alternatives:["ENV-PROBE-ALT"]}}))\n`); await compileLongTaskContract(x.workdir,x.root); const result=await runLongTaskFinalGate(x.workdir); assert.equal(result.workflow_status,"externally_blocked"); assert.equal(result.external_blocker.minimal_user_action,"Approve MFA challenge"); const allowed=await stopCheckLongTask(x.workdir,"任务阻塞，需要用户 Approve MFA challenge"); assert.equal(allowed.decision,undefined); const rejected=await stopCheckLongTask(x.workdir,"已完成，但阻塞，需要用户 Approve MFA challenge"); assert.equal(rejected.decision,"block");});
test("handwritten accepted final cannot bypass Stop",async()=>{const x=await setup(); const valid=await runLongTaskFinalGate(x.workdir); await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),`console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:false},forbidden:{passed:true}}}))\n`); const forged={...valid,workflow_status:"accepted"}; await writeFile(path.join(x.workdir,"final-result.json"),JSON.stringify(forged)); const stop=await stopCheckLongTask(x.workdir,"done"); assert.equal(stop.decision,"block");});
test("final_result_copied_from_other_task",async()=>{const a=await setup();const b=await setup();const result=await runLongTaskFinalGate(a.workdir);await writeFile(path.join(b.workdir,"final-result.json"),JSON.stringify(result));const stop=await stopCheckLongTask(b.workdir,"done");assert.equal(stop.decision,"block");});
test("worktree_changed_during_final",async()=>{const x=await setup();await mkdir(path.join(x.root,"src"),{recursive:true});await writeFile(path.join(x.root,"src/live.txt"),"before");await writeFile(path.join(x.root,"tests/acceptance/oracle.mjs"),`await new Promise(r=>setTimeout(r,1200));console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:true},forbidden:{passed:true}}}))\n`);await compileLongTaskContract(x.workdir,x.root);const gate=runLongTaskFinalGate(x.workdir);setTimeout(()=>void writeFile(path.join(x.root,"src/live.txt"),"during"),400);const result=await gate;assert.equal(result.workflow_status,"needs_work");assert.ok(result.findings.some((f)=>/worktree_changed|workspace_changed/.test(f.category)));});
test("partial AC pass cannot be accepted",async()=>{const x=await setup((d)=>{addSecondRequirementBranch(d);const second=d.checklist.verification_specs.find((spec)=>spec.id==="VS-AC-002");second.oracle.entrypoint="tests/acceptance/oracle-2.mjs";second.command_steps[0].target="tests/acceptance/oracle-2.mjs";},async(root)=>writeFile(path.join(root,"tests/acceptance/oracle-2.mjs"),`console.log(JSON.stringify({schema_version:"ty-context-observation-v1",checks:{works:{passed:false},forbidden:{passed:true}}}))\n`));const result=await runLongTaskFinalGate(x.workdir);assert.equal(result.workflow_status,"needs_work");assert.equal(result.acceptance_results["AC-001"],"passed");assert.equal(result.acceptance_results["AC-002"],"failed");});
