import test from "node:test";
import assert from "node:assert/strict";
import { appendFile, chmod, link, mkdtemp, mkdir, symlink, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
const exec=promisify(execFile);
import os from "node:os";
import path from "node:path";
import { compileLongTaskContract } from "../../packages/ty-context/dist/lib/long-task-contract-compiler.js";
import { createLongTaskSnapshot } from "../../packages/ty-context/dist/lib/long-task-snapshot.js";
import { writeHappyContract } from "./long-task-v2-fixtures.mjs";

async function ready() { const root=await mkdtemp(path.join(os.tmpdir(),"ltw-snapshot-")); const workdir=await writeHappyContract(root); const contract=await compileLongTaskContract(workdir,root); return {root,contract}; }
test("tracked and untracked content affect snapshot identity", async () => { const x=await ready(); await mkdir(path.join(x.root,"src")); await writeFile(path.join(x.root,"src/tracked.txt"),"one"); const a=await createLongTaskSnapshot(x.root,x.contract,"a"); await appendFile(path.join(x.root,"src/tracked.txt"),"two"); await writeFile(path.join(x.root,"src/untracked.txt"),"u"); const b=await createLongTaskSnapshot(x.root,x.contract,"b"); assert.notEqual(a.manifest.snapshot_sha256,b.manifest.snapshot_sha256); assert.ok(b.manifest.files.some((f)=>f.path==="src/untracked.txt")); await a.dispose(); await b.dispose(); });
test("ignored_runtime_input_changed", async () => { const x=await ready(); await writeFile(path.join(x.root,".gitignore"),"runtime.secret\n"); await writeFile(path.join(x.root,"runtime.secret"),"a"); const a=await createLongTaskSnapshot(x.root,x.contract,"a"); await writeFile(path.join(x.root,"runtime.secret"),"b"); const b=await createLongTaskSnapshot(x.root,x.contract,"b"); assert.notEqual(a.manifest.snapshot_sha256,b.manifest.snapshot_sha256); await a.dispose(); await b.dispose(); });
test("snapshot symlink escape is rejected", async (t) => { const x=await ready(); try { await symlink(os.tmpdir(),path.join(x.root,"escape-link"),"dir"); } catch (e) { t.skip(`symlink unavailable: ${e.code}`); return; } await assert.rejects(()=>createLongTaskSnapshot(x.root,x.contract,"symlink"),/snapshot_symlink_rejected/); });
test("snapshot hardlink escape is rejected", async () => { const x=await ready(); await writeFile(path.join(x.root,"original.txt"),"x"); await link(path.join(x.root,"original.txt"),path.join(x.root,"hard.txt")); await assert.rejects(()=>createLongTaskSnapshot(x.root,x.contract,"hard"),/snapshot_hardlink_rejected/); });
test("staged plus unstaged content uses final bytes and records Git HEAD",async()=>{const x=await ready();await mkdir(path.join(x.root,"src"));const file=path.join(x.root,"src/staged.txt");await writeFile(file,"staged");await exec("git",["add","src/staged.txt"],{cwd:x.root});await appendFile(file,"+unstaged");const snapshot=await createLongTaskSnapshot(x.root,x.contract,"index-worktree");assert.equal(snapshot.manifest.git_head?.length,40);assert.equal(snapshot.manifest.files.find((item)=>item.path==="src/staged.txt")?.size,15);await snapshot.dispose();});
test("file modes are part of snapshot identity",async(t)=>{if(process.platform==="win32"){t.skip("Windows does not expose POSIX executable mode semantics");return;}const x=await ready();const file=path.join(x.root,"mode.sh");await writeFile(file,"echo ok\n");await chmod(file,0o644);const a=await createLongTaskSnapshot(x.root,x.contract,"mode-a");await chmod(file,0o755);const b=await createLongTaskSnapshot(x.root,x.contract,"mode-b");assert.notEqual(a.manifest.snapshot_sha256,b.manifest.snapshot_sha256);await a.dispose();await b.dispose();});
test("Windows junctions are rejected",async(t)=>{if(process.platform!=="win32"){t.skip("Windows junction case");return;}const x=await ready();const outside=await mkdtemp(path.join(os.tmpdir(),"ltw-junction-out-"));try{await symlink(outside,path.join(x.root,"junction"),"junction");}catch(e){t.skip(`junction unavailable: ${e.code}`);return;}await assert.rejects(()=>createLongTaskSnapshot(x.root,x.contract,"junction"),/snapshot_symlink_rejected/);});
test("submodule identity is captured",async()=>{const x=await ready();const upstream=await mkdtemp(path.join(os.tmpdir(),"ltw-submodule-"));await exec("git",["init"],{cwd:upstream});await exec("git",["config","user.email","fixture@example.invalid"],{cwd:upstream});await exec("git",["config","user.name","Fixture"],{cwd:upstream});await writeFile(path.join(upstream,"value.txt"),"submodule");await exec("git",["add","."],{cwd:upstream});await exec("git",["commit","-m","baseline"],{cwd:upstream});await exec("git",["-c","protocol.file.allow=always","submodule","add",upstream,"vendor/sub"],{cwd:x.root});const snapshot=await createLongTaskSnapshot(x.root,x.contract,"submodule");assert.match(snapshot.manifest.submodules["vendor/sub"],/^[a-f0-9]{40}$/);await snapshot.dispose();});
