import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const read=(file)=>readFile(path.join(root,file),"utf8");
test("ordinary long-task remains separate from strict composite V2",async()=>{ const skills=await Promise.all([".codex/ty-context-managed/skills/normal-long-task/SKILL.md",".codex/skills/normal-long-task/SKILL.md","packages/ty-context/assets/skills/normal-long-task/SKILL.md"].map(read)); for(const content of skills){ assert.match(content,/name:\s*normal-long-task/); assert.match(content,/ordinary long-running task acceptance planning/); assert.match(content,/acceptance checklist/i); assert.doesNotMatch(content,/task-state\.json|validate-superpowers-state|superpowers:/i); } });
test("public design surfaces describe the V2 verifier boundary",async()=>{ const paths=["README.md","README.zh-CN.md","packages/ty-context/README.md","PROJECT_SPEC.md","project_context/areas/harness-package/contracts/workflow-contract.md"]; const surfaces=await Promise.all(paths.map(read)); for(const content of surfaces){ assert.match(content,/composite-long-task-workflow/i); assert.match(content,/three (?:strict )?(?:V2 YAML )?(?:inputs|authorities)|三份 V2 YAML|three-input/i); assert.match(content,/compiled-contract\.json|immutable machine contract|不可变.*合同/i); assert.match(content,/final-result\.json|final gate/i); assert.match(content,/Stop Hook|Stop enforcement|Stop 完成门/i); assert.match(content,/needs_work/); assert.match(content,/accepted/); } for(const content of surfaces.slice(0,3)) assert.doesNotMatch(content,/Superpowers-backed (?:composite|execution)|task-state\.json is the only|validate-superpowers-state/i); });
