import { cp, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalJson, canonicalYaml, parseStrictJson, sha256Hex } from "./composite-campaign-codec.js";
import { compileLongTaskContract } from "./long-task-contract-compiler.js";
import { parseLongTaskSources } from "./long-task-contract-parser.js";
import { validateLongTaskCoverage } from "./long-task-contract-coverage.js";
import { LONG_TASK_SOURCE_FILES, type AcceptanceChecklistV2, type ProductSourceV2, type TechnicalPlanV2 } from "./long-task-contract-schema.js";
import { resolveInside } from "./long-task-path-policy.js";
import { runLongTaskFinalGate } from "./long-task-final-gate.js";
import { readCompiledLongTaskContract } from "./long-task-contract-compiler.js";

const CAMPAIGN_SCHEMA = "composite-campaign-v2"; const PACKET_SCHEMA = "composite-authoring-packet-v2";
interface Campaign { schema_version: typeof CAMPAIGN_SCHEMA; campaign_id: string; request_sha256: string; generation: number; selected_slice_id: string | null; slices: Record<string, { current_revision: number; packet_sha256: string; handoff_workdir?: string; goal_id?: string; result?: { workflow_status: string; contract_sha256: string; run_id: string } }> }
interface Packet { schema_version: typeof PACKET_SCHEMA; campaign_id: string; slice_id: string; revision: number; previous_packet_sha256: string | null; authorities: { product_architecture_source: ProductSourceV2; technical_realization_plan: TechnicalPlanV2; acceptance_checklist: AcceptanceChecklistV2 } }

export function compositeCampaignV2Contract() { return { schema_version: PACKET_SCHEMA, authority_schemas: ["product-source-v2", "technical-plan-v2", "acceptance-checklist-v2"], projection_files: LONG_TASK_SOURCE_FILES, compatibility: "none" }; }
export async function createCampaignV2(projectRoot: string, id: string, requestFile: string) { validateId(id, "campaign"); const request = await readFile(resolveInside(projectRoot, requestFile, "request-file"), "utf8"); if (!request.trim()) throw new Error("Composite campaign request must not be empty"); assertNoRawSecret(request,"request"); const root = campaignRoot(projectRoot, id); await mkdir(path.dirname(root), { recursive: true }); const staging=`${root}.tmp-${process.pid}-${Date.now()}`; await mkdir(staging,{recursive:false}); const campaign: Campaign = { schema_version: CAMPAIGN_SCHEMA, campaign_id: id, request_sha256: sha256Hex(request), generation: 1, selected_slice_id: null, slices: {} }; try { await writeFile(path.join(staging, "request.md"), request, { flag: "wx" }); await writeFile(path.join(staging,"campaign.yaml"),canonicalYaml(campaign),{flag:"wx"}); await rename(staging,root); } catch(error) { await rm(staging,{recursive:true,force:true}); throw error; } return campaign;
}
export async function applyScopeV2(projectRoot: string, campaignPath: string, inputFile: string) { const { root, campaign } = await loadCampaign(projectRoot, campaignPath); const input = parseStrictJson(await readFile(resolveInside(projectRoot, inputFile, "scope-input"), "utf8")) as Record<string, unknown>; if (input.schema_version !== "scope-fit-result-v2") throw new Error("V1 scope results are not supported; expected scope-fit-result-v2"); const selected = input.selected_slice_id; if (typeof selected !== "string") throw new Error("scope-fit-result-v2 requires selected_slice_id"); validateId(selected, "slice"); campaign.selected_slice_id = selected; if (!campaign.slices[selected]) campaign.slices[selected] = { current_revision: 0, packet_sha256: "" }; campaign.generation += 1; await atomic(path.join(root, "scope-fit.json"), canonicalJson(input)); await saveCampaign(root, campaign); return campaign; }
export async function applyPacketV2(projectRoot: string, campaignPath: string, sliceId: string, inputFile: string) { validateId(sliceId, "slice"); const { root, campaign } = await loadCampaign(projectRoot, campaignPath); if (campaign.selected_slice_id !== sliceId) throw new Error("Packet slice must equal the selected slice"); const raw=await readFile(resolveInside(projectRoot, inputFile, "packet-input"), "utf8"); assertNoRawSecret(raw,"packet"); const packet = parseStrictJson(raw) as Packet; validatePacket(packet, campaign, sliceId); const prior = campaign.slices[sliceId]; const expectedRevision = prior.current_revision + 1; if (packet.revision !== expectedRevision) throw new Error(`Packet revision must be ${expectedRevision}`); if (expectedRevision > 1 && packet.previous_packet_sha256 !== prior.packet_sha256) throw new Error("Packet previous hash mismatch"); if (expectedRevision === 1 && packet.previous_packet_sha256 !== null) throw new Error("First V2 packet requires previous_packet_sha256=null"); const packetHash = sha256Hex(canonicalJson(packet)); const revision = revisionRoot(root, sliceId, packet.revision); await mkdir(path.dirname(revision), { recursive: true }); const staging=`${revision}.tmp-${process.pid}-${Date.now()}`; await mkdir(staging,{recursive:false}); try { await writeFile(path.join(staging, "authoring-packet.json"), canonicalJson(packet), { flag: "wx" }); await renderPacket(staging, packet); await rename(staging,revision); } catch(error) { await rm(staging,{recursive:true,force:true}); throw error; } campaign.slices[sliceId] = { current_revision: packet.revision, packet_sha256: packetHash }; campaign.generation += 1; await saveCampaign(root, campaign); return { campaign, packet_sha256: packetHash, revision_path: revision }; }
export async function renderCampaignV2(projectRoot: string, campaignPath: string, sliceId: string) { const { root, campaign } = await loadCampaign(projectRoot, campaignPath); const revision = currentRevision(campaign, sliceId); const revisionPath = revisionRoot(root, sliceId, revision); const packet = parseStrictJson(await readFile(path.join(revisionPath, "authoring-packet.json"), "utf8")) as Packet; if(sha256Hex(canonicalJson(packet))!==campaign.slices[sliceId].packet_sha256)throw new Error("Immutable V2 packet revision hash mismatch"); validatePacket(packet,campaign,sliceId); await renderPacket(revisionPath, packet); return { revision_path: revisionPath, files: Object.values(LONG_TASK_SOURCE_FILES) }; }
export async function preflightCampaignV2(projectRoot: string, campaignPath: string, sliceId: string) { const rendered = await renderCampaignV2(projectRoot, campaignPath, sliceId); const bundle = await parseLongTaskSources(rendered.revision_path); const coverage = validateLongTaskCoverage(bundle); if (!coverage.passed) throw new Error(coverage.errors.join("\n")); for (const spec of bundle.checklist.acceptance_criteria.flatMap((ac) => ac.verification_specs)) for (const oracle of spec.oracle_paths) await readFile(path.resolve(projectRoot, oracle)); return { handoff_ready: true, coverage, revision_path: rendered.revision_path }; }
export async function handoffCampaignV2(projectRoot: string, campaignPath: string, sliceId: string) { const { root, campaign } = await loadCampaign(projectRoot, campaignPath); await preflightCampaignV2(projectRoot, campaignPath, sliceId); const revision = currentRevision(campaign, sliceId); const source = revisionRoot(root, sliceId, revision); const workdir = path.join(projectRoot, "tmp", "ty-context", "plan-acceptance", campaign.campaign_id, `${sliceId}-r${revision}`); await rm(workdir, { recursive: true, force: true }); await mkdir(workdir, { recursive: true }); for (const file of Object.values(LONG_TASK_SOURCE_FILES)) await cp(path.join(source, file), path.join(workdir, file)); const contract = await compileLongTaskContract(workdir, projectRoot); campaign.slices[sliceId].handoff_workdir = workdir; campaign.generation += 1; await saveCampaign(root, campaign); return { workdir, contract_sha256: contract.contract_sha256, goal_created: false }; }
export async function bindCampaignGoalV2(projectRoot: string, campaignPath: string, sliceId: string, goalId: string) { const { root, campaign } = await loadCampaign(projectRoot, campaignPath); if (!campaign.slices[sliceId]?.handoff_workdir) throw new Error("Handoff must succeed before binding a Goal"); if (campaign.slices[sliceId].goal_id && campaign.slices[sliceId].goal_id !== goalId) throw new Error("Slice is already bound to a different Goal"); campaign.slices[sliceId].goal_id = goalId; campaign.generation += 1; await saveCampaign(root, campaign); return campaign; }
export async function recordCampaignResultV2(projectRoot: string, campaignPath: string, sliceId: string, workdir: string) { const { root, campaign } = await loadCampaign(projectRoot, campaignPath); const slice = campaign.slices[sliceId]; if (path.resolve(slice?.handoff_workdir ?? "") !== path.resolve(projectRoot, workdir)) throw new Error("Result workdir does not match the frozen handoff"); const contract=await readCompiledLongTaskContract(slice.handoff_workdir!); const result=await runLongTaskFinalGate(slice.handoff_workdir!); if (result.contract_sha256!==contract.contract_sha256 || !["accepted","externally_blocked"].includes(result.workflow_status)) throw new Error("Only a freshly recomputed accepted or externally_blocked V2 final result can be projected"); slice.result = { workflow_status: result.workflow_status, contract_sha256: result.contract_sha256, run_id: result.run_id }; campaign.generation += 1; await saveCampaign(root, campaign); return slice.result; }
export async function nextCampaignSliceV2(projectRoot: string, campaignPath: string) { const { campaign } = await loadCampaign(projectRoot, campaignPath); return { selected_slice_id: campaign.selected_slice_id, next_action: campaign.selected_slice_id ? (campaign.slices[campaign.selected_slice_id]?.current_revision ? "handoff_or_execute" : "apply_packet") : "apply_scope" }; }

async function renderPacket(root: string, packet: Packet): Promise<void> { const values = { [LONG_TASK_SOURCE_FILES.product]: packet.authorities.product_architecture_source, [LONG_TASK_SOURCE_FILES.plan]: packet.authorities.technical_realization_plan, [LONG_TASK_SOURCE_FILES.checklist]: packet.authorities.acceptance_checklist }; for (const [file, value] of Object.entries(values)) await atomic(path.join(root, file), canonicalYaml(value)); }
function validatePacket(packet: Packet, campaign: Campaign, slice: string): void { if (packet.schema_version !== PACKET_SCHEMA) throw new Error("V1 packets are not supported; expected composite-authoring-packet-v2"); if (packet.campaign_id !== campaign.campaign_id || packet.slice_id !== slice) throw new Error("Packet campaign/slice identity mismatch"); if (packet.authorities?.product_architecture_source?.schema_version !== "product-source-v2" || packet.authorities?.technical_realization_plan?.schema_version !== "technical-plan-v2" || packet.authorities?.acceptance_checklist?.schema_version !== "acceptance-checklist-v2") throw new Error("Packet authorities must use the three V2 schemas"); }
async function loadCampaign(projectRoot: string, supplied: string) { const root = path.resolve(projectRoot, supplied); const base = path.join(path.resolve(projectRoot), ".codex", "composite-long-task", "campaigns"); if (root !== base && !root.startsWith(`${base}${path.sep}`)) throw new Error("Campaign path escapes the V2 campaign root"); const { parseStrictYaml } = await import("./composite-campaign-codec.js"); const campaign = parseStrictYaml(await readFile(path.join(root, "campaign.yaml"), "utf8")) as Campaign; if (campaign.schema_version !== CAMPAIGN_SCHEMA) throw new Error("Legacy campaigns are audit-only and cannot be loaded by V2"); return { root, campaign }; }
function campaignRoot(projectRoot: string, id: string) { return path.join(path.resolve(projectRoot), ".codex", "composite-long-task", "campaigns", id); }
function revisionRoot(root: string, slice: string, revision: number) { return path.join(root, "slices", slice, "revisions", String(revision).padStart(4, "0")); }
function currentRevision(campaign: Campaign, slice: string) { const value = campaign.slices[slice]?.current_revision; if (!value) throw new Error("Slice has no V2 packet revision"); return value; }
async function saveCampaign(root: string, campaign: Campaign) { await atomic(path.join(root, "campaign.yaml"), canonicalYaml(campaign)); }
async function atomic(file: string, content: string) { await mkdir(path.dirname(file), { recursive: true }); const temp = `${file}.tmp-${process.pid}-${Date.now()}`; await writeFile(temp, content, { flag: "wx" }); await rename(temp, file); }
function validateId(value: string, label: string) { if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(value)) throw new Error(`${label} id is not portable`); }
function assertNoRawSecret(value:string,label:string){if(/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|\b(?:api[_-]?key|access[_-]?token|secret|password)\s*[:=]\s*["']?[A-Za-z0-9_./+=-]{12,}/i.test(value))throw new Error(`${label} contains a raw credential or private key`);}
