export function globalContextTemplate(): string {
  return [
    "# Project / Delivery Context",
    "",
    "## Project Goal",
    "",
    "- Describe the user-visible goal this project is trying to achieve.",
    "",
    "## Non-goals / Boundaries",
    "",
    "- List what this project intentionally does not do.",
    "",
    "## Background",
    "",
    "- Capture the minimum background a fresh agent needs before changing code.",
    "",
    "## Design Rationale",
    "",
    "- Record only durable choices that are hard to infer from code or tests. Classify changes before implementation; if a change alters product ownership/plans, module responsibilities, information architecture, API/Schema, state/scheduler semantics, cross-area boundaries, verification role paths or deployment role paths, update Context before code with enough durable context to guide implementation.",
    "",
    "## Architecture Context",
    "",
    "- Link to `project_context/architecture.md`; keep architecture notes minimal and focused on boundaries, components and constraints that are not obvious from code.",
    "",
    "## Context Graph",
    "",
    "- Link to `project_context/context.toml` and keep its default area, role, trigger, read policy and boundary metadata aligned with this Context.",
    "- When adding or reorganizing files under `project_context/areas/**`, run a soft role placement scan before registering every Markdown file as an area: product ownership stays in `area` / `domain` / `subdomain`; contracts, foundations, verification, deployment, implementation indexes, decision rationale and archives should use role Context when that better fits the reading purpose.",
    "",
    "## Product / Delivery Brief",
    "",
    "- Capture durable product goals, users, core flows, acceptance signals and non-goals.",
    "",
    "## UX / Screen Brief",
    "",
    "- Capture durable screen, flow, interaction, responsive and accessibility facts. Use `DESIGN.md` for visual identity and design tokens when needed.",
    "",
    "## Verification Entry Points",
    "",
    "- Point to the default verification context for repeatable test, smoke, CI or validation paths.",
    "- Project-level cross-domain verification may live here only as a short index; execution details belong in `verification` role Context.",
    "",
    "## Current State",
    "",
    "- Summarize what is currently implemented or intentionally blocked.",
    "",
    "## Next Safe Action",
    "",
    "- State the safest next step for a fresh agent, including whether the next change should update Context before code.",
    "",
    "## Context Index",
    "",
    "- [main](areas/main.md)",
    "- [main verification](areas/main/verification.md)",
    "",
  ].join("\n");
}

export function architectureContextTemplate(): string {
  return [
    "# Architecture Context",
    "",
    "This is the restrained architecture context. Keep only facts that help a fresh agent recover system shape, boundaries and durable constraints quickly.",
    "",
    "## System Boundary",
    "",
    "- Describe what is inside this project and what external systems, providers or runtime assumptions sit outside it.",
    "",
    "## Component Map",
    "",
    "- List the smallest useful set of components, areas or context units and how they relate.",
    "",
    "## Data / Control Flow",
    "",
    "- Summarize only the durable request, event, state or data flow that is hard to infer from code alone.",
    "",
    "## Design Rationale",
    "",
    "- Record architecture-level choices that still constrain future work; architecture boundary changes should be captured here before implementation alignment.",
    "",
    "## Constraints And Tradeoffs",
    "",
    "- Capture performance, safety, integration, deployment or maintainability constraints that matter for future changes.",
    "",
    "## Verification Implications",
    "",
    "- List project-specific verification entry points affected by architectural changes; do not claim tests already passed.",
    "",
    "## Open Risks",
    "",
    "- List unresolved architectural risks or unknowns.",
    "",
  ].join("\n");
}

export function areaContextTemplate(areaName: string): string {
  return [
    `# Area Context: ${areaName}`,
    "",
    "## Responsibility",
    "",
    "- Describe this product/domain area or context unit's responsibility.",
    "",
    "## User / System Contract",
    "",
    "- Describe the external behavior, API, CLI, UI, screen state, interaction or data contract. Contract changes should be captured here before implementation alignment.",
    "",
    "## Core Data / API / State",
    "",
    "- Summarize the important data structures, APIs, state transitions, or rules.",
    "",
    "## Module Design Capsule",
    "",
    "- Principles: stable execution constraints that should affect future module work.",
    "- Design Logic: the minimum logic for choosing, rejecting, degrading or composing module behavior.",
    "- Design Rationale: only durable reasons that change later implementation or verification decisions.",
    "- Current standards, thresholds and commands belong in the relevant contract or verification Context, not as permanent principles.",
    "",
    "## Key Constraints",
    "",
    "- List constraints that are not obvious from code alone, including product rules, responsive/a11y needs or visual boundaries.",
    "",
    "## Code Entry Points",
    "",
    "- `src/` or the concrete file/function entry points.",
    "",
    "## Related Role Context",
    "",
    "- Verification paths live in this area's `verification` role Context, such as `project_context/areas/main/verification.md`.",
    "- Deployment/runtime/bootstrap paths live in this area's optional `deployment` role Context when those facts exist.",
    "",
    "## Open Risks",
    "",
    "- List unresolved risks or blockers.",
    "",
  ].join("\n");
}

export function verificationContextTemplate(areaName: string): string {
  return [
    `# Verification Context: ${areaName}`,
    "",
    "This role Context records critical repeat-execution paths for the owning area. Keep it minimal: enough for a future agent to rerun verification without rediscovering setup, not a test report.",
    "",
    "## Owner",
    "",
    `- Owning area: \`${areaName}\`.`,
    "",
    "## Verification Paths",
    "",
    "- `npm test` or the shortest project-specific test, smoke, CI, probe or validation command.",
    "- Verification paths are reusable execution instances, not independent definitions of the verification target. For capability, metric or acceptance claims, first use the owning module's design Context to decide what claim should be proven, then choose the command or probe.",
    "",
    "## Required Preparation",
    "",
    "- List only durable setup such as services, env files, fixtures, local runtimes or external dependencies needed before rerun.",
    "",
    "## Expected Signals",
    "",
    "- Name the stage, health check, status, artifact shape or observable signal that means the path reached the intended point.",
    "",
    "## Acceptable Warnings",
    "",
    "- List warnings that are expected and should not trigger repeated investigation.",
    "",
    "## Excluded Dead Ends",
    "",
    "- List previously ruled-out commands, providers, endpoints or setup paths only when remembering them prevents repeated wasted work.",
    "",
    "## Forbidden Content",
    "",
    "- Do not record one-off logs, full command output, temporary JSON, CI artifacts, test reports, secrets, tokens, cookies, device ids, raw payloads or pass/fail claims.",
    "",
  ].join("\n");
}

export function deploymentContextTemplate(areaName: string): string {
  return [
    `# Deployment Context: ${areaName}`,
    "",
    "This optional role Context records critical repeat-execution paths for deploy, runtime bootstrap, cloud initialization and operational recovery. Keep it minimal and durable.",
    "",
    "## Owner",
    "",
    `- Owning area: \`${areaName}\`.`,
    "",
    "## Runtime Topology",
    "",
    "- List durable service distribution only when it matters for rerunning deploy or bootstrap, such as Web/API/worker/Redis/DB/Docker/cloud instance boundaries.",
    "",
    "## Deployment Paths",
    "",
    "- List the shortest deploy, CI/CD, bootstrap, migration, health-check or rollback/degradation command/path.",
    "",
    "## Required Preparation",
    "",
    "- List only durable setup such as cloud resources, env files, compose profiles, secret mounting names or database initialization steps. Do not store secret values.",
    "",
    "## Expected Signals",
    "",
    "- Name health checks, status transitions, URLs, queues, containers or logs-at-a-glance that show the path reached the intended stage.",
    "",
    "## Acceptable Warnings",
    "",
    "- List known benign warnings or slow-start states.",
    "",
    "## Excluded Dead Ends",
    "",
    "- List previously ruled-out deploy/bootstrap paths only when remembering them prevents repeated wasted work.",
    "",
    "## Forbidden Content",
    "",
    "- Do not record one-off logs, full command output, CI artifacts, release ledgers, secrets, tokens, cookies, device ids, raw payloads or claims that deployment already succeeded.",
    "",
  ].join("\n");
}
