import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import type { FrozenVerificationSpecV3, CommandStepV3, DependencyPlanV3 } from "./long-task-contract-schema.js";
import type { DependencyLayerHandleV3 } from "./long-task-dependency-layer.js";
import { dependencyBinary } from "./long-task-dependency-layer.js";
import { nodePermissionArgv, nodePermissionOptions } from "./long-task-sandbox-node.js";
import { sha256Hex } from "./composite-campaign-codec.js";
import { isSandboxAccessError } from "./long-task-sandbox-node.js";
import { declaredLongTaskEnvironment } from "./long-task-environment.js";
import type { LongTaskRedactorV3 } from "./long-task-redaction.js";

export interface CommandStepRunV3 { id:string; tool:CommandStepV3["tool"]; executable:string; argv:string[]; exit_code:number; sandbox_denied:boolean; stdout_path:string; stdout_sha256:string; stderr_path:string; stderr_sha256:string; started_at:string; completed_at:string }
export interface CommandStepsResultV3 { steps:CommandStepRunV3[]; exit_code:number }
export async function runLongTaskCommandSteps(spec:FrozenVerificationSpecV3,specRoot:string,artifactRoot:string,commandRoot:string,tempRoot:string,plan:DependencyPlanV3,layer:DependencyLayerHandleV3|null,browserRoot:string|null,baseEnvironment:NodeJS.ProcessEnv,declaredEnvironment:Readonly<Record<string,string>>,redactor:LongTaskRedactorV3):Promise<CommandStepsResultV3>{const results:CommandStepRunV3[]=[];for(const step of spec.command_steps){const descriptor=resolveStep(step,specRoot,plan,layer);for(const root of descriptor.adapter_write_roots)await mkdir(root,{recursive:true});const profile={read_paths:[specRoot,artifactRoot,tempRoot,...(layer?[layer.root]:[]),...(browserRoot?[browserRoot]:[]),...descriptor.identity_roots],write_paths:[artifactRoot,tempRoot,...descriptor.adapter_write_roots],allow_child_process:step.tool!=="node_script",allow_worker:step.tool==="project_binary"||step.tool==="playwright_test",allow_addons:step.tool!=="node_script"};const permission=nodePermissionArgv(profile);const argv=descriptor.node?[...permission,descriptor.target,...descriptor.argv]:descriptor.argv;const env=declaredLongTaskEnvironment({...baseEnvironment,NODE_OPTIONS:nodePermissionOptions(profile)},step.environment_refs,declaredEnvironment);const output=path.join(commandRoot,"steps",step.id);await mkdir(output,{recursive:true});const started_at=new Date().toISOString();const run=await execute(descriptor.executable,argv,descriptor.cwd,env,Math.min(step.timeout_ms,spec.timeout_ms),redactor);const stdoutPath=path.join(output,"stdout.txt");const stderrPath=path.join(output,"stderr.txt");await writeFile(stdoutPath,run.stdout);await writeFile(stderrPath,run.stderr);results.push({id:step.id,tool:step.tool,executable:descriptor.executable,argv,exit_code:run.code,sandbox_denied:isSandboxAccessError(run.stderr),stdout_path:stdoutPath,stdout_sha256:sha256Hex(run.stdout),stderr_path:stderrPath,stderr_sha256:sha256Hex(run.stderr),started_at,completed_at:new Date().toISOString()});if(run.code!==0)return {steps:results,exit_code:run.code};}return {steps:results,exit_code:0};}
function resolveStep(step:CommandStepV3,specRoot:string,plan:DependencyPlanV3,layer:DependencyLayerHandleV3|null):{executable:string;target:string;argv:string[];cwd:string;node:boolean;identity_roots:string[];adapter_write_roots:string[]}{const cwd=step.cwd==="."?specRoot:inside(specRoot,step.cwd);if(step.tool==="node_script")return {executable:process.execPath,target:inside(specRoot,step.target),argv:[...step.argv],cwd,node:true,identity_roots:[],adapter_write_roots:[]};if(!layer||!plan.manager)throw new Error(`dependency_layer_missing:${step.id}`);if(step.tool==="package_script"){const manager=plan.manager;return {executable:manager.invocation_executable,target:manager.invocation_prefix[0]??"",argv:[...manager.invocation_prefix,"run",step.target,...(step.argv.length?["--",...step.argv]:[])],cwd,node:false,identity_roots:[path.resolve(path.dirname(manager.executable_path),"..")],adapter_write_roots:[]};}const name=step.tool==="playwright_test"?"playwright":step.target;const binary=dependencyBinary(layer,name,specRoot);return {executable:process.execPath,target:binary,argv:step.tool==="playwright_test"?["test",step.target,...step.argv]:[...step.argv],cwd,node:true,identity_roots:name==="vitest"||step.tool==="playwright_test"?workspaceProbeFiles(specRoot):[],adapter_write_roots:name==="vitest"?[path.join(specRoot,"node_modules",".vite-temp")]:[]};}
async function execute(executable:string,argv:string[],cwd:string,env:NodeJS.ProcessEnv,timeout:number,redactor:LongTaskRedactorV3):Promise<{code:number;stdout:Buffer;stderr:Buffer}>{return new Promise((resolve,reject)=>{const child=spawn(executable,argv,{cwd,env,shell:false,windowsHide:true});const stdout:Buffer[]=[];const stderr:Buffer[]=[];const stdoutRedactor=redactor.stream();const stderrRedactor=redactor.stream();let size=0;let settled=false;const fail=(error:Error)=>{if(settled)return;settled=true;clearTimeout(timer);child.kill();reject(error);};const capture=(target:Buffer[],stream:ReturnType<LongTaskRedactorV3["stream"]>)=>(chunk:Buffer)=>{size+=chunk.length;if(size>16*1024*1024){fail(new Error("command_output_limit_exceeded"));return;}const value=stream.push(Buffer.from(chunk));if(value.length)target.push(value);};child.stdout.on("data",capture(stdout,stdoutRedactor));child.stderr.on("data",capture(stderr,stderrRedactor));child.on("error",fail);const timer=setTimeout(()=>fail(new Error("command_timeout")),timeout);child.on("close",(code)=>{if(settled)return;settled=true;clearTimeout(timer);stdout.push(stdoutRedactor.finish());stderr.push(stderrRedactor.finish());resolve({code:code??-1,stdout:Buffer.concat(stdout),stderr:Buffer.concat(stderr)});});});}
function inside(root:string,relative:string):string{const resolved=path.resolve(root,...relative.replace(/\\/g,"/").split("/"));if(resolved!==path.resolve(root)&&!resolved.startsWith(`${path.resolve(root)}${path.sep}`))throw new Error(`wrong_cwd:${relative}`);return resolved;}
function workspaceProbeFiles(root:string):string[]{const values=[];let current=path.resolve(root);while(true){for(const name of ["package.json","pnpm-workspace.yaml","lerna.json","deno.json","deno.jsonc","tsconfig.json","jsconfig.json"])values.push(path.join(current,name));const parent=path.dirname(current);if(parent===current)break;current=parent;}return values;}
