import { createRequire } from "node:module";
import { lstat, readFile, readdir, realpath } from "node:fs/promises";
import path from "node:path";
import { canonicalValueJson, sha256Hex } from "./composite-campaign-codec.js";

export interface ManagedHostRuntimeFileV1 { path:string;sha256:string;size:number }
export interface ManagedHostRuntimeManifestV1 { schema_version:"ty-context-host-cli-runtime-manifest-v1";files:ManagedHostRuntimeFileV1[] }
export interface ManagedSandboxLauncherIdentityV1 { path:string;sha256:string }

export async function createManagedHostRuntimeManifestV1(cliPath:string):Promise<ManagedHostRuntimeManifestV1>{const cli=await realpath(cliPath);const roots=new Set<string>([await realpath(path.dirname(cli))]);const require=createRequire(cli);for(const name of ["yaml","re2js","esbuild",esbuildPlatformPackage()]){let entry:string;try{entry=require.resolve(`${name}/package.json`);}catch{entry=require.resolve(name);}roots.add(await packageRoot(entry,name));}const files=new Map<string,ManagedHostRuntimeFileV1>();for(const root of [...roots].sort(compare))await collect(root,files);const result={schema_version:"ty-context-host-cli-runtime-manifest-v1" as const,files:[...files.values()].sort((a,b)=>compare(a.path,b.path))};if(result.files.length===0||result.files.length>20_000||result.files.reduce((sum,item)=>sum+item.size,0)>512*1024*1024)throw new Error("host_runtime_manifest_limits");return result;}
export function managedHostRuntimeManifestSha256V1(manifest:ManagedHostRuntimeManifestV1):string{return sha256Hex(canonicalValueJson(manifest));}
export function managedHostRuntimeContentSha256V1(manifest:ManagedHostRuntimeManifestV1):string{return sha256Hex(canonicalValueJson(manifest.files.map((item)=>({sha256:item.sha256,size:item.size})).sort((left,right)=>left.sha256.localeCompare(right.sha256)||left.size-right.size)));}
export async function resolveManagedSandboxLauncherV1(helperPath:string,platform:NodeJS.Platform=process.platform):Promise<ManagedSandboxLauncherIdentityV1>{const candidates=platform==="win32"?[helperPath]:platform==="darwin"?["/usr/bin/sandbox-exec"]:["/usr/bin/bwrap","/bin/bwrap"];for(const candidate of candidates){try{const resolved=await realpath(candidate);const info=await lstat(resolved);if(!info.isFile()||info.isSymbolicLink())continue;return {path:resolved,sha256:sha256Hex(await readFile(resolved))};}catch{}}throw new Error(platform==="linux"?"sandbox_capability_unavailable:bubblewrap_missing":"sandbox_capability_unavailable:launcher_missing");}
async function collect(root:string,files:Map<string,ManagedHostRuntimeFileV1>):Promise<void>{for(const entry of (await readdir(root,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){const file=path.join(root,entry.name);const info=await lstat(file);if(info.isSymbolicLink())throw new Error(`host_runtime_symlink_forbidden:${file}`);if(entry.isDirectory()){await collect(file,files);continue;}if(!entry.isFile()||!runtimeFile(entry.name))continue;const canonical=await realpath(file);const bytes=await readFile(canonical);files.set(normalized(canonical),{path:canonical,sha256:sha256Hex(bytes),size:bytes.length});}}
async function packageRoot(entry:string,expected:string):Promise<string>{let current=path.dirname(await realpath(entry));for(let depth=0;depth<12;depth+=1){try{const value=JSON.parse(await readFile(path.join(current,"package.json"),"utf8"));if(value.name===expected)return realpath(current);}catch{}const parent=path.dirname(current);if(parent===current)break;current=parent;}throw new Error(`host_runtime_package_root_missing:${expected}`);}
function esbuildPlatformPackage():string{const map:Record<string,string>={"win32-x64":"@esbuild/win32-x64","win32-arm64":"@esbuild/win32-arm64","linux-x64":"@esbuild/linux-x64","linux-arm64":"@esbuild/linux-arm64","darwin-x64":"@esbuild/darwin-x64","darwin-arm64":"@esbuild/darwin-arm64"};const value=map[`${process.platform}-${process.arch}`];if(!value)throw new Error("host_runtime_platform_unsupported");return value;}
function runtimeFile(name:string):boolean{return /\.(?:c?js|mjs|json|node|wasm|exe)$/iu.test(name)||!name.includes(".");}
function normalized(value:string):string{const result=path.resolve(value).replace(/^\\\\\?\\/u,"");return process.platform==="win32"?result.toLocaleLowerCase("en-US"):result;}
function compare(left:string,right:string):number{return normalized(left).localeCompare(normalized(right));}
