import { cp, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { canonicalJson } from "./composite-campaign-codec.js";
import { sha256Hex } from "./composite-campaign-codec.js";
import { readFile } from "node:fs/promises";
import { collectFrozenArtifacts } from "./long-task-artifact-collector.js";
import { evaluateFrozenAssertions } from "./long-task-assertion-evaluator.js";
import { runFrozenCommand } from "./long-task-command-runner.js";
import { assertLongTaskContractFresh, readCompiledLongTaskContract } from "./long-task-contract-compiler.js";
import { createLongTaskSnapshot, hashLongTaskWorkspace } from "./long-task-snapshot.js";
import type { EnvironmentManifestV2, LongTaskFindingV2, VerificationRunResultV2, VerificationSpecResultV2 } from "./long-task-run-result.js";
import { decideLongTaskImpact } from "./long-task-impact.js";
import { scanLongTaskNegativeEvidence } from "./long-task-negative-evidence.js";

export async function verifyLongTask(workdir: string, specIds?: string[]): Promise<VerificationRunResultV2> {
  const contract = await readCompiledLongTaskContract(workdir); await assertLongTaskContractFresh(contract); const workspaceBefore = await hashLongTaskWorkspace(contract.repository_root, contract); const runId = `RUN-${new Date().toISOString().replace(/[-:.TZ]/g, "")}-${process.pid}-${contract.contract_sha256.slice(0, 8)}`; const runRoot = path.join(workdir, "runs", runId); await mkdir(path.join(runRoot, "command-runs"), { recursive: true }); await mkdir(path.join(runRoot, "artifacts"), { recursive: true }); const source = await createLongTaskSnapshot(contract.repository_root, contract, runId); const startedAt = new Date().toISOString(); const environment = await environmentManifest(source.root);
  try { const automatic = specIds ? undefined : decideLongTaskImpact(contract, await gitChangedPaths(contract.repository_root)); const selectedIds = specIds ?? automatic!.verification_spec_ids; const selected = contract.verification_specs.filter((spec) => selectedIds.includes(spec.id)); if (selected.length === 0) throw new Error("No frozen verification specs selected"); const specResults = [];
    for (const spec of selected) { const specRoot = await mkdtemp(path.join(os.tmpdir(), `ty-context-spec-${spec.id}-`)); const artifactRoot = path.join(runRoot, "artifacts", spec.id); await mkdir(artifactRoot, { recursive: true }); try { await cp(source.root, specRoot, { recursive: true }); const commandRoot = path.join(runRoot, "command-runs", spec.id); try { const command = await runFrozenCommand(spec, specRoot, commandRoot, artifactRoot); const artifacts = await collectFrozenArtifacts(spec, artifactRoot, command.started_at); await writeFile(path.join(commandRoot, "command.json"), canonicalJson(command)); await writeFile(path.join(commandRoot, "artifacts.json"), canonicalJson(artifacts)); const evidence=path.relative(workdir, commandRoot).replace(/\\/g, "/"); const reverify=`ty-context composite-long-task verify ${quote(workdir)} --spec ${spec.id}`; const evaluated=await evaluateFrozenAssertions(spec, command, evidence, reverify); evaluated.findings.push(...await scanLongTaskNegativeEvidence(spec,command,artifacts,artifactRoot,evidence,reverify)); if(evaluated.findings.length>0)evaluated.status="failed"; specResults.push(evaluated); } catch (error) { specResults.push(failedSpec(spec.id, error, path.relative(workdir, commandRoot).replace(/\\/g, "/"), workdir)); } } finally { await rm(specRoot, { recursive: true, force: true }); } }
    const findings = specResults.flatMap((result) => enrichFindings(contract, result.spec_id, result.findings)); try { await assertLongTaskContractFresh(contract); } catch(error) { findings.push({category:"frozen_identity_changed_during_verify",expected:"source, Context, oracle, executable and verifier hashes remain frozen",actual:error instanceof Error?error.message:String(error),evidence_path:`runs/${runId}/snapshot-manifest.json`,next_action:"Restore frozen verifier/oracle/source identities and recompile before continuing",reverify_command:`ty-context composite-long-task verify ${quote(workdir)}`}); } const workspaceAfter = await hashLongTaskWorkspace(contract.repository_root, contract); if (workspaceAfter !== workspaceBefore) findings.push({ category: "worktree_changed_during_verify", expected: workspaceBefore, actual: workspaceAfter, evidence_path: `runs/${runId}/snapshot-manifest.json`, next_action: "Stabilize the product workspace and rerun verification", reverify_command: `ty-context composite-long-task verify ${quote(workdir)}` }); const result: VerificationRunResultV2 = { schema_version: "long-task-verification-run-v2", run_id: runId, contract_sha256: contract.contract_sha256, snapshot: source.manifest, environment, spec_results: specResults, findings, started_at: startedAt, completed_at: new Date().toISOString() }; await writeFile(path.join(runRoot, "snapshot-manifest.json"), canonicalJson(source.manifest)); await writeFile(path.join(runRoot, "environment-manifest.json"), canonicalJson(environment)); await writeFile(path.join(runRoot, "verification-result.json"), canonicalJson(result)); return result;
  } finally { await source.dispose(); }
}
function quote(value: string): string { return /\s/.test(value) ? JSON.stringify(value) : value; }
function enrichFindings(contract: Awaited<ReturnType<typeof readCompiledLongTaskContract>>, specId: string, findings: VerificationRunResultV2["findings"]): VerificationRunResultV2["findings"] { const ac = Object.entries(contract.acceptance_graph).find(([, value]) => value.verification_spec_ids.includes(specId)); if(!ac)return findings; const bindings=ac[1].obligation_ids.flatMap((obligation_id)=>{const requirements=contract.obligation_graph[obligation_id]?.requirement_ids??[];return requirements.length?requirements.map((requirement_id)=>({requirement_id,obligation_id,ac_id:ac[0]})):[{obligation_id,ac_id:ac[0]}];}); return findings.flatMap((finding)=>bindings.map((binding)=>({ ...finding, ...binding }))); }
async function gitChangedPaths(root: string): Promise<string[]> { return new Promise((resolve) => { const child = spawn("git", ["status", "--porcelain=v1", "-z", "--untracked-files=all"], { cwd: root, shell: false, windowsHide: true }); const chunks: Buffer[] = []; child.stdout.on("data", (chunk: Buffer) => chunks.push(chunk)); child.on("error", () => resolve([])); child.on("close", (code) => { if (code !== 0) { resolve([]); return; } const fields = Buffer.concat(chunks).toString("utf8").split("\0").filter(Boolean); resolve(fields.map((field) => field.slice(3).replace(/.* -> /, "").replace(/\\/g, "/"))); }); }); }
function failedSpec(specId: string, error: unknown, evidencePath: string, workdir: string): VerificationSpecResultV2 { const actual = error instanceof Error ? error.message : String(error); const finding: LongTaskFindingV2 = { category: actual.split(":",1)[0] || "verification_execution_failed", verification_spec_id: specId, expected: "frozen verification spec completes and emits trusted observations", actual, evidence_path: evidencePath, next_action: `Fix ${specId} verifier or implementation failure`, reverify_command: `ty-context composite-long-task verify ${quote(workdir)} --spec ${specId}` }; return { spec_id: specId, status: "failed", assertion_results: {}, findings: [finding] }; }
async function environmentManifest(snapshotRoot: string): Promise<EnvironmentManifestV2> { return { node: process.version, platform: process.platform, arch: process.arch, release: os.release(), executable: process.execPath, executable_sha256: sha256Hex(await readFile(process.execPath)), cwd: snapshotRoot, environment_keys: ["PATH","Path","PATHEXT","SYSTEMROOT","WINDIR","HOME","USERPROFILE","TMP","TEMP","CI","LANG","LC_ALL"].filter((key) => process.env[key] !== undefined).sort() }; }
