import { access, lstat, readFile, readdir, realpath, stat } from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import { canonicalValueJson, sha256Hex } from "./composite-campaign-codec.js";
import type { DependencyManagerNameV3, DependencyManagerV3 } from "./long-task-contract-schema.js";

const INSTALL:Record<DependencyManagerNameV3,string[]>={pnpm:["install","--frozen-lockfile"],yarn:["install","--immutable"],npm:["ci"],bun:["install","--frozen-lockfile"]};
export function dependencyInstallArgv(name:DependencyManagerNameV3):string[]{return [...INSTALL[name]];}
export async function resolveDependencyManager(name:DependencyManagerNameV3):Promise<DependencyManagerV3>{
  if(name==="npm"){const tool=await nodeToolPackage("npm","bin/npm-cli.js");return descriptor(name,tool.version,tool.entry,tool.root,process.execPath,[tool.entry]);}
  if(name==="pnpm"||name==="yarn"){const tool=await nodeToolPackage("corepack","dist/corepack.js");const version=(await output(process.execPath,[tool.entry,name,"--version"])).trim();return descriptor(name,version,tool.entry,tool.root,process.execPath,[tool.entry,name]);}
  const executable=await realpath(await findExecutable(process.platform==="win32"?["bun.exe"]:["bun"]));const version=(await output(executable,["--version"])).trim();return descriptor(name,version,executable,executable,executable,[]);
}
async function descriptor(name:DependencyManagerNameV3,version:string,identityPath:string,runtimeRoot:string,invocationExecutable:string,prefix:string[]):Promise<DependencyManagerV3>{const info=await stat(identityPath);if(!info.isFile()||!version)throw new Error(`dependency_manager_unavailable:${name}`);const runtime=await runtimeIdentity(runtimeRoot);return {name,version,executable_path:identityPath,executable_sha256:sha256Hex(await readFile(identityPath)),runtime_root:runtime.root,runtime_sha256:runtime.sha256,invocation_executable:invocationExecutable,invocation_prefix:prefix,install_argv:dependencyInstallArgv(name)};}
async function nodeToolPackage(name:"npm"|"corepack",entryRelative:string):Promise<{entry:string;root:string;version:string}>{
  const nodeDirectory=path.dirname(process.execPath);const prefix=path.dirname(nodeDirectory);const roots=[path.join(nodeDirectory,"node_modules",name),path.join(prefix,"lib","node_modules",name),path.join(prefix,"node_modules",name)];
  try{const command=await findExecutable(process.platform==="win32"?[`${name}.cmd`,name]:[name]);const resolved=await realpath(command);if(resolved.endsWith(".js"))roots.unshift(path.dirname(path.dirname(resolved)));}catch{}
  for(const candidate of [...new Set(roots)])try{const root=await realpath(candidate);const value=JSON.parse(await readFile(path.join(root,"package.json"),"utf8")) as {name?:unknown;version?:unknown};const entry=await realpath(path.join(root,...entryRelative.split("/")));if(value.name===name&&typeof value.version==="string"&&value.version)return {entry,root,version:value.version};}catch{}
  throw new Error(`dependency_manager_unavailable:${name}`);
}
async function runtimeIdentity(requested:string):Promise<{root:string;sha256:string}>{const root=await realpath(requested);const rows:Array<{path:string;sha256:string;size:number}>=[];async function visit(file:string,relative:string):Promise<void>{const info=await lstat(file);if(info.isSymbolicLink())throw new Error(`dependency_manager_runtime_symlink:${relative}`);if(info.isDirectory()){for(const entry of (await readdir(file,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name)))await visit(path.join(file,entry.name),relative?`${relative}/${entry.name}`:entry.name);return;}if(!info.isFile())throw new Error(`dependency_manager_runtime_special:${relative}`);const bytes=await readFile(file);rows.push({path:relative||path.basename(file),sha256:sha256Hex(bytes),size:bytes.length});}await visit(root,"");return {root,sha256:sha256Hex(canonicalValueJson(rows))};}
async function findExecutable(names:string[]):Promise<string>{for(const directory of (process.env.PATH??"").split(path.delimiter))for(const name of names){const candidate=path.resolve(directory||".",name);try{await access(candidate);return candidate;}catch{}}throw new Error(`dependency_manager_unavailable:${names[0]}`);}
async function output(executable:string,argv:string[]):Promise<string>{return new Promise((resolve,reject)=>{const child=spawn(executable,argv,{shell:false,windowsHide:true,env:{PATH:process.env.PATH,Path:process.env.Path,PATHEXT:process.env.PATHEXT,SYSTEMROOT:process.env.SYSTEMROOT,WINDIR:process.env.WINDIR,HOME:process.env.HOME,USERPROFILE:process.env.USERPROFILE}});const chunks:Buffer[]=[];const errors:Buffer[]=[];child.stdout.on("data",(item:Buffer)=>chunks.push(item));child.stderr.on("data",(item:Buffer)=>errors.push(item));child.on("error",reject);child.on("close",(code)=>code===0?resolve(Buffer.concat(chunks).toString("utf8")):reject(new Error(`dependency_manager_unavailable:${Buffer.concat(errors).toString("utf8")}`)));});}
