import { lstat, readFile, readdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import YAML from "yaml";
import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import type { DependencyInputIdentityV3, DependencyManagerNameV3, DependencyPlanV3, VerificationSpecV3 } from "./long-task-contract-schema.js";
import { resolveDependencyManager } from "./long-task-package-manager.js";
import { LONG_TASK_SANDBOX_POLICY_SHA256 } from "./long-task-sandbox-policy.js";

const LOCKS:Array<{name:DependencyManagerNameV3;files:string[]}>= [{name:"pnpm",files:["pnpm-lock.yaml"]},{name:"yarn",files:["yarn.lock"]},{name:"npm",files:["package-lock.json"]},{name:"bun",files:["bun.lock","bun.lockb"]}];
const CONFIGS=[".npmrc",".yarnrc.yml",".pnpmfile.cjs","pnpmfile.cjs","bunfig.toml"];
export async function compileDependencyPlan(root:string,specs:VerificationSpecV3[]):Promise<DependencyPlanV3>{
  const required=specs.some((spec)=>spec.command_steps.some((step)=>step.tool==="package_script"||step.tool==="project_binary"||step.tool==="playwright_test"));const packageFile=path.join(root,"package.json");const packageJson=await optionalJson(packageFile);const detection=await detectDependencyLock(root,packageJson?.packageManager);
  if(required&&!detection.selected)throw new Error("dependency_lockfile_missing");const selected=detection.selected;
  const manager=selected?await resolveDependencyManager(selected.name):null;const lockfile=selected?await identity(root,selected.file):null;const manifests=packageJson?await workspaceManifests(root,packageJson,selected?.name,specs):[];if(required&&!packageJson)throw new Error("dependency_manifest_missing:package.json");
  const workspaceDescriptors:DependencyInputIdentityV3[]=[];if(packageJson?.workspaces!==undefined){const bytes=Buffer.from(canonicalJson(packageJson.workspaces));workspaceDescriptors.push({path:"package.json#workspaces",sha256:sha256Hex(bytes),size:bytes.length});}if(await regular(path.join(root,"pnpm-workspace.yaml")))workspaceDescriptors.push(await identity(root,"pnpm-workspace.yaml"));
  const installConfigs=[];for(const file of CONFIGS)if(await regular(path.join(root,file)))installConfigs.push(await redactedIdentity(root,file));const binaries=[...new Set(specs.flatMap((spec)=>spec.command_steps.flatMap((step)=>step.tool==="project_binary"?[step.target]:step.tool==="playwright_test"?["playwright"]:[])))].sort();
  const playwrightPackages=await playwrightIdentities(root,lockfile,packageJson);const nodeBytes=await readFile(process.execPath);const corepack=manager&&(manager.name==="pnpm"||manager.name==="yarn")?await corepackIdentity():null;
  const unsigned={required,manager,lockfile,package_manifests:manifests,workspace_descriptors:workspaceDescriptors.sort(byPath),install_configs:installConfigs.sort(byPath),required_project_binaries:binaries,playwright_packages:playwrightPackages,node:{version:process.version,executable:process.execPath,sha256:sha256Hex(nodeBytes)},corepack,platform:{platform:process.platform,release:os.release(),arch:process.arch,libc_abi:libcAbi()},normalized_install_configuration:normalizedInstallConfiguration(),sandbox_policy_sha256:LONG_TASK_SANDBOX_POLICY_SHA256};const keyInput={manager,lockfile,package_manifests:unsigned.package_manifests,workspace_descriptors:unsigned.workspace_descriptors,install_configs:unsigned.install_configs,node:unsigned.node,corepack,platform:unsigned.platform,normalized_install_configuration:unsigned.normalized_install_configuration,sandbox_policy_sha256:unsigned.sandbox_policy_sha256};return {...unsigned,key:sha256Hex(canonicalJson(keyInput))};
}
export async function detectDependencyLock(root:string,packageManager:unknown):Promise<{selected:{name:DependencyManagerNameV3;file:string}|null;present:Array<{name:DependencyManagerNameV3;file:string}>}>{const present=[];for(const candidate of LOCKS)for(const file of candidate.files)if(await regular(path.join(root,file))){present.push({name:candidate.name,file});break;}const selected=present[0]??null;const declared=typeof packageManager==="string"?packageManager.split("@")[0]:null;if(selected&&((present.length>1&&!declared)||(declared&&declared!==selected.name)))throw new Error(`dependency_manager_conflict:${selected.name}:${declared??"missing"}`);return {selected,present};}
async function workspaceManifests(root:string,packageJson:Record<string,unknown>,manager:DependencyManagerNameV3|undefined,specs:VerificationSpecV3[]):Promise<DependencyInputIdentityV3[]>{const patterns=workspacePatterns(packageJson);if(manager==="pnpm"&&await regular(path.join(root,"pnpm-workspace.yaml"))){const value=YAML.parse(await readFile(path.join(root,"pnpm-workspace.yaml"),"utf8")) as {packages?:unknown};if(Array.isArray(value?.packages)&&value.packages.every((item)=>typeof item==="string"))patterns.push(...value.packages as string[]);}const all=await packageFiles(root);const selected=new Set(["package.json"]);for(const file of all){if(file==="package.json")continue;const directory=path.posix.dirname(file);if(matchesWorkspace(directory,patterns))selected.add(file);}for(const spec of specs)for(const step of spec.command_steps){const cwd=step.cwd==="."?"":step.cwd.replace(/\\/g,"/").replace(/\/$/u,"");const reachable=all.filter((file)=>cwd===path.posix.dirname(file)||cwd.startsWith(`${path.posix.dirname(file)}/`)).sort((a,b)=>b.length-a.length)[0];if(reachable&&!selected.has(reachable))throw new Error(`dependency_workspace_manifest_omitted:${reachable}`);}return Promise.all([...selected].sort().map((file)=>identity(root,file)));}
function workspacePatterns(packageJson:Record<string,unknown>):string[]{const value=packageJson.workspaces;if(Array.isArray(value)&&value.every((item)=>typeof item==="string"))return [...value] as string[];if(value&&typeof value==="object"&&!Array.isArray(value)&&Array.isArray((value as {packages?:unknown}).packages))return [...((value as {packages:string[]}).packages)];return [];}
function matchesWorkspace(directory:string,patterns:string[]):boolean{const positives=patterns.filter((item)=>!item.startsWith("!"));const negatives=patterns.filter((item)=>item.startsWith("!")).map((item)=>item.slice(1));return positives.some((item)=>path.matchesGlob(directory,item.replace(/\\/g,"/")))&&!negatives.some((item)=>path.matchesGlob(directory,item.replace(/\\/g,"/")));}
async function packageFiles(root:string):Promise<string[]>{const result:string[]=[];async function visit(dir:string,relative=""):Promise<void>{for(const entry of await readdir(dir,{withFileTypes:true})){if(entry.name==="node_modules"||entry.name===".git"||relative.startsWith("tmp/ty-context/plan-acceptance"))continue;const rel=relative?`${relative}/${entry.name}`:entry.name;const file=path.join(dir,entry.name);if(entry.isDirectory())await visit(file,rel);else if(entry.isFile()&&entry.name==="package.json")result.push(rel);}}await visit(root);return result.sort();}
async function playwrightIdentities(root:string,lock:DependencyInputIdentityV3|null,packageJson:Record<string,unknown>|null):Promise<Array<{name:string;version:string;integrity:string|null}>>{const names=["@playwright/test","playwright","playwright-core"];if(lock?.path==="package-lock.json"){const value=JSON.parse(await readFile(path.join(root,lock.path),"utf8")) as {packages?:Record<string,{version?:string;integrity?:string}>};return names.flatMap((name)=>{const row=value.packages?.[`node_modules/${name}`];return row?.version?[{name,version:row.version,integrity:row.integrity??null}]:[];});}const sources=[packageJson?.dependencies,packageJson?.devDependencies].filter((item)=>item&&typeof item==="object") as Record<string,unknown>[];return names.flatMap((name)=>{const version=sources.map((item)=>item[name]).find((item)=>typeof item==="string");return typeof version==="string"?[{name,version,integrity:null}]:[];});}
async function corepackIdentity():Promise<{version:string;executable:string;sha256:string}>{const root=path.join(path.dirname(process.execPath),"node_modules","corepack");const pkg=JSON.parse(await readFile(path.join(root,"package.json"),"utf8")) as {version:string};const executable=path.join(root,"dist","corepack.js");return {version:pkg.version,executable,sha256:sha256Hex(await readFile(executable))};}
async function identity(root:string,relative:string):Promise<DependencyInputIdentityV3>{const bytes=await readFile(path.join(root,...relative.split("/")));return {path:relative,sha256:sha256Hex(bytes),size:bytes.length};}
async function redactedIdentity(root:string,relative:string):Promise<DependencyInputIdentityV3>{const content=await readFile(path.join(root,relative),"utf8");const redacted=content.split(/\r?\n/u).map((line)=>/(?:_auth|token|password|secret)\s*=/iu.test(line)?`${line.split("=")[0]}=[REDACTED]`:line).join("\n");const bytes=Buffer.from(redacted);return {path:relative,sha256:sha256Hex(bytes),size:bytes.length};}
async function optionalJson(file:string):Promise<Record<string,unknown>|null>{try{return JSON.parse(await readFile(file,"utf8")) as Record<string,unknown>;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return null;throw error;}}
async function regular(file:string):Promise<boolean>{try{const info=await lstat(file);return info.isFile()&&!info.isSymbolicLink();}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return false;throw error;}}
function libcAbi():string{if(process.platform==="win32")return "msvc";if(process.platform==="darwin")return "darwin";const header=(process.report?.getReport() as {header?:{glibcVersionRuntime?:string}}).header;return header?.glibcVersionRuntime?`glibc-${header.glibcVersionRuntime}`:"linux-unknown";}
function normalizedInstallConfiguration():Record<string,string>{const result:Record<string,string>={lifecycle_scripts:"disabled",binary_links:"disabled",network:"declared_registry_only",plaintext_credentials:"forbidden"};for(const key of ["HTTP_PROXY","HTTPS_PROXY","NO_PROXY","http_proxy","https_proxy","no_proxy"])if(process.env[key])result[`${key.toLocaleLowerCase("en-US")}_sha256`]=sha256Hex(process.env[key]!);return Object.fromEntries(Object.entries(result).sort(([a],[b])=>a.localeCompare(b)));}
function byPath(a:{path:string},b:{path:string}):number{return a.path.localeCompare(b.path);}
