import { readFile, realpath, stat } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";
import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import type { CompiledContractV3, FrozenVerificationSpecV3, OracleBundleV3, OracleBundlerIdentityV3, OracleInputDependencyV3, VerificationSpecV3 } from "./long-task-contract-schema.js";
import { ORACLE_BUILD_POLICY, ORACLE_BUNDLER_INTEGRITY, ORACLE_BUNDLER_VERSION, ORACLE_POLICY_SHA256, ORACLE_WRAPPER_SOURCE, validateOracleBundlePolicy } from "./long-task-oracle-bundle-policy.js";
import { sealOracleBundle, verifyStoredOracleBundle } from "./long-task-oracle-bundle-store.js";

export interface BuiltOracleBundleV3 { identity:OracleBundleV3; bytes:Uint8Array }
export async function buildLongTaskOracleBundle(root:string,spec:VerificationSpecV3|FrozenVerificationSpecV3,seal=true):Promise<BuiltOracleBundleV3>{
  if(esbuild.version!==ORACLE_BUNDLER_VERSION)throw new Error(`oracle_bundler_identity_mismatch:${esbuild.version}`);const wrapper=wrapperSource(spec.oracle.entrypoint);let built;
  try{built=await esbuild.build({...ORACLE_BUILD_POLICY,conditions:[...ORACLE_BUILD_POLICY.conditions],mainFields:[...ORACLE_BUILD_POLICY.mainFields],logOverride:{...ORACLE_BUILD_POLICY.logOverride},absWorkingDir:path.resolve(root),stdin:{contents:wrapper,resolveDir:path.resolve(root),sourcefile:ORACLE_WRAPPER_SOURCE,loader:"js"}});}catch(error){throw normalizeBuildError(error);}
  const metafile=validateOracleBundlePolicy(built,root);const output=built.outputFiles?.find((item)=>item.path.endsWith("<stdout>"))??built.outputFiles?.[0];if(!output)throw new Error("oracle_bundle_failed:output_missing");
  const bytes=output.contents;const bundleHash=sha256Hex(bytes);const identity:OracleBundleV3={spec_id:spec.id,entrypoint:spec.oracle.entrypoint,bundle_store_key:bundleHash,bundle_sha256:bundleHash,bundle_size:bytes.byteLength,metafile_sha256:sha256Hex(canonicalJson(metafile)),input_dependencies:await inputDependencies(root,metafile.inputs),bundler:await bundlerIdentity(),wrapper_sha256:sha256Hex(wrapper),policy_sha256:await policyIdentity()};
  if(seal)await sealOracleBundle(identity,bytes);return {identity,bytes};
}
export async function assertOracleBundleClosureFresh(contract:CompiledContractV3):Promise<void>{for(const spec of contract.verification_specs){const sealed=contract.oracle_bundles.find((item)=>item.spec_id===spec.id);if(!sealed)throw new Error(`oracle_bundle_missing:${spec.id}`);try{await verifyStoredOracleBundle(sealed);const rebuilt=(await buildLongTaskOracleBundle(contract.repository_root,spec,false)).identity;if(canonicalJson(rebuilt)!==canonicalJson(sealed))throw new Error("identity_mismatch");}catch(error){throw new Error(`oracle_dependency_changed_after_compile:${spec.id}:${message(error)}`);}}}

function wrapperSource(entrypoint:string):string{const imported=`./${entrypoint.replace(/\\/g,"/").replace(/^\.\//u,"")}`;return `import {writeFileSync} from "node:fs";\nimport {observe as oracleObserve} from ${JSON.stringify(imported)};\nconst encoded=process.env.TY_CONTEXT_ORACLE_INPUT_B64;\nif(!encoded)throw new Error("oracle_input_missing");\nconst input=JSON.parse(Buffer.from(encoded,"base64url").toString("utf8"));\nconst output=await oracleObserve(input);\nwriteFileSync(3,JSON.stringify(output));\n`;}
async function inputDependencies(root:string,inputs:Record<string,{bytes:number}>):Promise<OracleInputDependencyV3[]>{const result:OracleInputDependencyV3[]=[];for(const input of Object.keys(inputs).sort()){const normalized=input.replace(/\\/g,"/");if(normalized===ORACLE_WRAPPER_SOURCE)continue;const absolute=path.resolve(root,...normalized.split("/"));const actual=await realpath(absolute);if(actual!==path.resolve(root)&&!actual.startsWith(`${path.resolve(root)}${path.sep}`))throw new Error(`oracle_dependency_outside_layer:${normalized}`);const bytes=await readFile(actual);const npm=await npmIdentity(root,normalized);result.push({logical_id:npm?`npm:${npm.name}@${npm.version}/${npm.relative}`:`repo:${normalized}`,source_kind:npm?"npm":"repository",package_name:npm?.name??null,package_version:npm?.version??null,path:npm?.relative??normalized,sha256:sha256Hex(bytes),size:bytes.byteLength});}return result.sort((a,b)=>a.logical_id.localeCompare(b.logical_id));}
async function npmIdentity(root:string,relative:string):Promise<{name:string;version:string;relative:string}|undefined>{const parts=relative.split("/");const marker=parts.lastIndexOf("node_modules");if(marker<0)return undefined;const scoped=parts[marker+1]?.startsWith("@");const name=scoped?`${parts[marker+1]}/${parts[marker+2]}`:parts[marker+1];if(!name)throw new Error(`oracle_npm_identity_invalid:${relative}`);const packageParts=parts.slice(0,marker+1).concat(name.split("/"));const packageRoot=path.resolve(root,...packageParts);const value=JSON.parse(await readFile(path.join(packageRoot,"package.json"),"utf8")) as {name?:unknown;version?:unknown};if(value.name!==name||typeof value.version!=="string"||!value.version)throw new Error(`oracle_npm_identity_invalid:${relative}`);const packageRelative=path.relative(packageRoot,path.resolve(root,...parts)).replace(/\\/g,"/");return {name,version:value.version,relative:packageRelative};}
async function bundlerIdentity():Promise<OracleBundlerIdentityV3>{const require=createRequire(import.meta.url);const entry=require.resolve("esbuild");const packageFile=require.resolve("esbuild/package.json");const native=nativeBinary(path.dirname(packageFile));return {package_version:ORACLE_BUNDLER_VERSION,package_integrity:ORACLE_BUNDLER_INTEGRITY,js_entry_sha256:await hashFile(entry),native_binary_sha256:await hashFile(native)};}
async function policyIdentity():Promise<string>{const moduleHash=await hashFile(fileURLToPath(new URL("./long-task-oracle-bundle-policy.js",import.meta.url)));return sha256Hex(canonicalJson({declarative_policy_sha256:ORACLE_POLICY_SHA256,module_sha256:moduleHash}));}
function nativeBinary(esbuildPackageRoot:string):string{const names:Record<string,string>={"win32-x64":"win32-x64","win32-arm64":"win32-arm64","darwin-x64":"darwin-x64","darwin-arm64":"darwin-arm64","linux-x64":"linux-x64","linux-arm64":"linux-arm64"};const name=names[`${process.platform}-${process.arch}`];if(!name)throw new Error(`oracle_bundler_platform_unsupported:${process.platform}-${process.arch}`);return path.join(path.dirname(esbuildPackageRoot),"@esbuild",name,process.platform==="win32"?"esbuild.exe":"bin/esbuild");}
async function hashFile(file:string):Promise<string>{const info=await stat(file);if(!info.isFile())throw new Error(`oracle_bundler_identity_missing:${file}`);return sha256Hex(await readFile(file));}
function normalizeBuildError(error:unknown):Error{const rows=error&&typeof error==="object"&&"errors" in error?(error as {errors?:Array<{id?:string}>}).errors??[]:[];if(rows.some((item)=>item.id==="unsupported-dynamic-import"||item.id==="unsupported-require-call"))return new Error(`oracle_dynamic_import_escape:${rows.map((item)=>item.id).join(",")}`);return new Error(`oracle_bundle_failed:${message(error)}`);}
function message(error:unknown):string{return error instanceof Error?error.message:String(error);}
