import { execFile } from "node:child_process";
import { chmod, chown, cp, lstat, mkdir, mkdtemp, open, readFile, readdir, realpath, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { canonicalValueJson, sha256Hex } from "./composite-campaign-codec.js";
import { mergeManagedRequirementsV1, removeManagedRequirementsV1 } from "./long-task-managed-requirements.js";
import type { ManagedHostLayoutV1 } from "./long-task-managed-host-layout.js";
import { verifyHostReleaseDirectoryV1 } from "./long-task-host-release.js";
import { LONG_TASK_HOST_RELEASE_ROOT_PUBLIC_KEY_PEM } from "./long-task-host-release-root.js";
import { createManagedHostRuntimeManifestV1, managedHostRuntimeManifestSha256V1, resolveManagedSandboxLauncherV1 } from "./long-task-host-runtime-identity.js";

const execute=promisify(execFile);
interface InstallOptionsV1 { source:string;layout:ManagedHostLayoutV1;pinned_root_public_key?:string;test_admin?:boolean;cli_path?:string;cli_worker_path?:string;codex_launcher_path?:string;start_service?:boolean }
interface UninstallOptionsV1 { layout:ManagedHostLayoutV1;test_admin?:boolean }

export async function installManagedHostReleaseV1(options:InstallOptionsV1):Promise<{status:"installed";managed_dir:string;service:"started"|"configured_test_namespace"}>{
  await assertAdmin(options.test_admin);const publicKey=options.pinned_root_public_key??(options.test_admin?await readFile(path.join(options.source,"host-release-root-public.pem"),"utf8"):LONG_TASK_HOST_RELEASE_ROOT_PUBLIC_KEY_PEM);await verifyHostReleaseDirectoryV1(options.source,publicKey);const manifestText=await readFile(path.join(options.source,"host-release-manifest.json"),"utf8");
  const cliPath=await realpath(options.cli_path??fileURLToPath(new URL("../cli.js",import.meta.url)));const cliWorkerPath=await realpath(options.cli_worker_path??fileURLToPath(new URL("./long-task-host-worker-runtime.js",import.meta.url)));const nodePath=await realpath(options.layout.node_path);const codexLauncherPath=await realpath(options.codex_launcher_path??(options.test_admin?nodePath:(()=>{throw new Error("managed_codex_launcher_identity_required");})()));const helperName=options.layout.platform==="win32"?"ty-context-host-helper.exe":"ty-context-host-helper";const adminName=options.layout.platform==="win32"?"ty-context-host-admin.exe":"ty-context-host-admin";const installerUiName=options.layout.platform==="win32"?"ty-context-host-installer-ui.exe":"ty-context-host-installer-ui";const sandboxLauncher=options.layout.platform==="win32"?{path:options.layout.helper_path,sha256:sha256Hex(await readFile(path.join(options.source,helperName)))}:await resolveManagedSandboxLauncherV1(options.layout.helper_path,options.layout.platform);const existingRequirements=await readFile(options.layout.requirements_file,"utf8").catch((error:NodeJS.ErrnoException)=>{if(error.code==="ENOENT")return"";throw error;});const mergedRequirements=mergeManagedRequirementsV1(existingRequirements,options.layout);
  const parent=path.dirname(options.layout.managed_dir);await mkdir(parent,{recursive:true});const staging=await mkdtemp(path.join(parent,".ty-context-install-"));const backup=`${options.layout.managed_dir}.backup-${process.pid}-${Date.now()}`;let swapped=false;
  try{
    await cp(options.source,staging,{recursive:true});const cliRuntimeManifest=await createManagedHostRuntimeManifestV1(cliPath);const config={schema_version:"ty-context-host-service-config-v1",state_root:options.layout.state_root,endpoint:options.layout.endpoint,managed_dir:options.layout.managed_dir,requirements_file:options.layout.requirements_file,node_path:nodePath,node_sha256:sha256Hex(await readFile(nodePath)),helper_path:options.layout.helper_path,sandbox_launcher_path:sandboxLauncher.path,sandbox_launcher_sha256:sandboxLauncher.sha256,admin_path:options.layout.admin_path,admin_sha256:sha256Hex(await readFile(path.join(staging,adminName))),installer_ui_path:options.layout.installer_ui_path,installer_ui_sha256:sha256Hex(await readFile(path.join(staging,installerUiName))),codex_launcher_path:codexLauncherPath,codex_launcher_sha256:sha256Hex(await readFile(codexLauncherPath)),cli_path:cliPath,cli_sha256:sha256Hex(await readFile(cliPath)),cli_worker_path:cliWorkerPath,cli_worker_sha256:sha256Hex(await readFile(cliWorkerPath)),cli_runtime_manifest:cliRuntimeManifest,cli_runtime_manifest_sha256:managedHostRuntimeManifestSha256V1(cliRuntimeManifest),hook_path:options.layout.hook_path,hook_sha256:sha256Hex(await readFile(path.join(staging,"long-task-hook.mjs"))),worker_path:options.layout.worker_path,worker_sha256:sha256Hex(await readFile(path.join(staging,"ty-context-host-worker.mjs"))),attestation_public_key_path:options.layout.attestation_public_key_path,managed_policy_sha256:sha256Hex(mergedRequirements),release_manifest_sha256:sha256Hex(manifestText),test_namespace:options.test_admin===true};if(sha256Hex(await readFile(path.join(staging,helperName)))!==manifestHash(JSON.parse(manifestText),helperName)||config.admin_sha256!==manifestHash(JSON.parse(manifestText),adminName)||config.installer_ui_sha256!==manifestHash(JSON.parse(manifestText),installerUiName))throw new Error("host_release_asset_mismatch:executable");await writeFile(path.join(staging,"host-service-config.json"),canonicalValueJson(config),{flag:"wx"});await syncTree(staging);
    await stopPlatformService(options.layout,options.test_admin);if(await exists(options.layout.managed_dir))await durableRename(options.layout.managed_dir,backup);await durableRename(staging,options.layout.managed_dir);swapped=true;await ensureStateLayout(options.layout.state_root);await atomic(options.layout.requirements_file,mergedRequirements);if(!options.test_admin){await securePaths(options.layout);await installPlatformService(options.layout,options.start_service!==false);}await rm(backup,{recursive:true,force:true});return {status:"installed",managed_dir:options.layout.managed_dir,service:options.test_admin?"configured_test_namespace":"started"};
  }catch(error){await rm(staging,{recursive:true,force:true});if(swapped){await rm(options.layout.managed_dir,{recursive:true,force:true});if(await exists(backup))await durableRename(backup,options.layout.managed_dir);await atomic(options.layout.requirements_file,existingRequirements).catch(()=>undefined);}throw error;}
}

export async function uninstallManagedHostReleaseV1(options:UninstallOptionsV1):Promise<{status:"uninstalled"}>{await assertAdmin(options.test_admin);if(await hasActiveRegistry(options.layout.state_root))throw new Error("active_registry_prevents_uninstall");await stopPlatformService(options.layout,options.test_admin,true);const requirements=await readFile(options.layout.requirements_file,"utf8").catch(()=>"");await atomic(options.layout.requirements_file,removeManagedRequirementsV1(requirements));await rm(options.layout.managed_dir,{recursive:true,force:true});return {status:"uninstalled"};}

async function ensureStateLayout(root:string):Promise<void>{for(const directory of ["keys","registry/active","registry/tombstones","journal","bundles","dependencies","browsers","staging","quarantine","audit","repositories"] )await mkdir(path.join(root,directory),{recursive:true});}
async function securePaths(layout:ManagedHostLayoutV1):Promise<void>{
  if(process.platform==="win32"){
    await run("icacls.exe",[layout.managed_dir,"/inheritance:r","/grant:r","*S-1-5-18:(OI)(CI)F","*S-1-5-32-544:(OI)(CI)F","*S-1-5-32-545:(OI)(CI)RX","/T","/C"]);
    await run("icacls.exe",[layout.state_root,"/inheritance:r","/grant:r","*S-1-5-18:(OI)(CI)F","*S-1-5-32-544:(OI)(CI)F","/T","/C"]);
    await run("icacls.exe",[layout.requirements_file,"/inheritance:r","/grant:r","*S-1-5-18:F","*S-1-5-32-544:F","*S-1-5-32-545:R"]);return;
  }
  await secureUnixManagedTree(layout.managed_dir);await chown(layout.state_root,0,0);await chmod(layout.state_root,0o700);await chown(layout.requirements_file,0,0);await chmod(layout.requirements_file,0o644);
  const socketDirectory=path.dirname(layout.endpoint);await mkdir(socketDirectory,{recursive:true});if(process.platform==="linux"){await run("groupadd",["--system","ty-context"],true);const group=await run("getent",["group","ty-context"]);const gid=Number(group.stdout.split(":")[2]);if(!Number.isInteger(gid))throw new Error("host_socket_group_invalid");await chown(socketDirectory,0,gid);await chmod(socketDirectory,0o2770);}else{await chown(socketDirectory,0,0);await chmod(socketDirectory,0o755);}
}
async function secureUnixManagedTree(root:string):Promise<void>{const executable=new Set(["ty-context-host-helper","ty-context-host-admin","ty-context-host-installer-ui"]);async function visit(file:string):Promise<void>{const info=await lstat(file);if(info.isSymbolicLink())throw new Error("managed_host_symlink_forbidden");await chown(file,0,0);if(info.isDirectory()){await chmod(file,0o755);for(const entry of await readdir(file))await visit(path.join(file,entry));}else if(info.isFile())await chmod(file,executable.has(path.basename(file))?0o755:0o644);else throw new Error("managed_host_file_type_invalid");}await visit(root);}

export function renderLinuxServiceUnitV1(layout:ManagedHostLayoutV1):string{return `[Unit]\nDescription=Tiny Context Managed Completion Gate\nAfter=local-fs.target\n\n[Service]\nType=simple\nUser=root\nGroup=ty-context\nUMask=0007\nExecStart=${systemd(layout.helper_path)} serve --config ${systemd(layout.service_config_path)}\nRestart=on-failure\nRestartSec=5s\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=full\nRestrictAddressFamilies=AF_UNIX AF_INET AF_INET6\n\n[Install]\nWantedBy=multi-user.target\n`;}
export function renderMacLaunchDaemonV1(layout:ManagedHostLayoutV1):string{return `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict><key>Label</key><string>com.openai.codex.ty-context-host-gate</string><key>UserName</key><string>root</string><key>GroupName</key><string>wheel</string><key>Umask</key><integer>7</integer><key>ProgramArguments</key><array><string>${xml(layout.helper_path)}</string><string>serve</string><string>--config</string><string>${xml(layout.service_config_path)}</string></array><key>RunAtLoad</key><true/><key>KeepAlive</key><true/><key>ThrottleInterval</key><integer>5</integer></dict></plist>\n`;}

async function installPlatformService(layout:ManagedHostLayoutV1,start:boolean):Promise<void>{if(process.platform==="win32"){const command=`"${layout.helper_path}" service --config "${layout.service_config_path}" --service-name "TyContextHostGate"`;const exists=await commandSucceeds("sc.exe",["query","TyContextHostGate"]);if(exists)await run("sc.exe",["config","TyContextHostGate","binPath=",command,"start=","auto","obj=","LocalSystem"]);else await run("sc.exe",["create","TyContextHostGate","binPath=",command,"start=","auto","obj=","LocalSystem","DisplayName=","Tiny Context Managed Completion Gate"]);await run("sc.exe",["sidtype","TyContextHostGate","unrestricted"]);await run("sc.exe",["failure","TyContextHostGate","reset=","86400","actions=","restart/5000/restart/30000/\"\"/0"]);if(start)await run("sc.exe",["start","TyContextHostGate"],true);return;}if(process.platform==="linux"){const unit="/etc/systemd/system/ty-context-host-gate.service";await atomic(unit,renderLinuxServiceUnitV1(layout));await run("systemctl",["daemon-reload"]);await run("systemctl",["enable","ty-context-host-gate.service"]);if(start)await run("systemctl",["restart","ty-context-host-gate.service"]);return;}const plist="/Library/LaunchDaemons/com.openai.codex.ty-context-host-gate.plist";await atomic(plist,renderMacLaunchDaemonV1(layout));await chmod(plist,0o644);if(start){await run("launchctl",["bootout","system/com.openai.codex.ty-context-host-gate"],true);await run("launchctl",["bootstrap","system",plist]);}}
async function stopPlatformService(layout:ManagedHostLayoutV1,testAdmin?:boolean,remove=false):Promise<void>{if(testAdmin)return;if(process.platform==="win32"){await run("sc.exe",["stop","TyContextHostGate"],true);if(remove)await run("sc.exe",["delete","TyContextHostGate"],true);return;}if(process.platform==="linux"){await run("systemctl",["stop","ty-context-host-gate.service"],true);if(remove){await run("systemctl",["disable","ty-context-host-gate.service"],true);await rm("/etc/systemd/system/ty-context-host-gate.service",{force:true});await run("systemctl",["daemon-reload"]);}return;}await run("launchctl",["bootout","system/com.openai.codex.ty-context-host-gate"],true);if(remove)await rm("/Library/LaunchDaemons/com.openai.codex.ty-context-host-gate.plist",{force:true});}

async function hasActiveRegistry(root:string):Promise<boolean>{async function visit(directory:string,active=false):Promise<boolean>{for(const entry of await readdir(directory,{withFileTypes:true}).catch(()=>[])){if(entry.isSymbolicLink())continue;const next=path.join(directory,entry.name);const isActive=active||(entry.isDirectory()&&entry.name==="active"&&path.basename(directory)==="registry");if(entry.isFile()&&isActive&&entry.name.endsWith(".json"))return true;if(entry.isDirectory()&&await visit(next,isActive))return true;}return false;}return visit(root);}
async function atomic(file:string,content:string):Promise<void>{await mkdir(path.dirname(file),{recursive:true});const temporary=`${file}.tmp-${process.pid}-${Date.now()}`;const handle=await open(temporary,"wx",0o644);try{await handle.writeFile(content);await handle.sync();}finally{await handle.close();}try{await durableRename(temporary,file);}catch(error){await rm(temporary,{force:true});throw error;}}
async function syncTree(root:string):Promise<void>{for(const entry of await readdir(root,{withFileTypes:true})){const file=path.join(root,entry.name);if(entry.isSymbolicLink())throw new Error("host_release_symlink_forbidden");if(entry.isDirectory())await syncTree(file);else if(entry.isFile()){const handle=await open(file,"r+");try{await handle.sync();}finally{await handle.close();}}else throw new Error("host_release_file_type_invalid");}await syncDirectory(root);}
async function durableRename(source:string,target:string):Promise<void>{await rename(source,target);await syncDirectory(path.dirname(target));}
async function syncDirectory(directory:string):Promise<void>{if(process.platform==="win32")return;const handle=await open(directory,"r");try{await handle.sync();}finally{await handle.close();}}
async function exists(file:string):Promise<boolean>{try{await stat(file);return true;}catch{return false;}}
async function assertAdmin(testAdmin?:boolean):Promise<void>{if(testAdmin)return;if(process.platform!=="win32"&&typeof process.getuid==="function"&&process.getuid()===0)return;if(process.platform==="win32"){const value=await run("whoami.exe",["/groups","/fo","csv","/nh"],true);if(/S-1-16-(?:12288|16384)/u.test(value.stdout))return;}throw new Error("host_installer_requires_administrator");}
async function run(file:string,args:string[],allowFailure=false):Promise<{stdout:string;stderr:string}>{try{const result=await execute(file,args,{windowsHide:true,maxBuffer:4*1024*1024});return {stdout:result.stdout,stderr:result.stderr};}catch(error){if(allowFailure)return {stdout:"",stderr:""};throw error;}}
async function commandSucceeds(file:string,args:string[]):Promise<boolean>{try{await execute(file,args,{windowsHide:true});return true;}catch{return false;}}
function manifestHash(manifest:{files?:Array<{path?:string;sha256?:string}>},name:string):string|undefined{return manifest.files?.find((item)=>item.path===name)?.sha256;}
function systemd(value:string):string{return `"${value.replace(/([\\"])/gu,"\\$1")}"`;}
function xml(value:string):string{return value.replace(/&/gu,"&amp;").replace(/</gu,"&lt;").replace(/>/gu,"&gt;").replace(/"/gu,"&quot;");}
