import { chmod, cp, lstat, mkdir, mkdtemp, open, readFile, readdir, rename, rm, stat, symlink, writeFile, copyFile, realpath } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import type { DependencyPlanV3 } from "./long-task-contract-schema.js";
import { nodePermissionOptions } from "./long-task-sandbox-node.js";
import { longTaskNodeRuntimeAdapterSourceV1 } from "./long-task-node-runtime-adapter.js";

const CACHE=path.join(os.tmpdir(),"project-tiny-context-harness-host-v3","dependencies");
export interface DependencyLayerFileV3 { path:string; type:"file"|"symlink"; mode:number; size:number; sha256?:string; target?:string }
export interface DependencyLayerManifestV3 { schema_version:"long-task-dependency-layer-v3"; key:string; node_modules_roots:string[]; workspace_links:Array<{link_path:string;target_path:string}>; binaries:Array<{name:string;path:string;package_name:string;version:string}>; packages:Array<{name:string;version:string;path:string}>; runtime_adapters:Array<{name:"node-runtime-v1";path:string;sha256:string;size:number}>; files:DependencyLayerFileV3[]; install:{exit_code:0;stdout_sha256:string;stderr_sha256:string}; created_at:string }
export interface DependencyLayerHandleV3 { key:string; root:string; manifest:DependencyLayerManifestV3 }

export async function prepareDependencyLayer(snapshotRoot:string,plan:DependencyPlanV3):Promise<DependencyLayerHandleV3|null>{if(!plan.required)return null;const layer=layerPath(plan.key);try{return await readLayer(layer,plan.key);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT"&&!message(error).startsWith("dependency_layer_corrupt")){throw error;}if((error as NodeJS.ErrnoException).code!=="ENOENT")await quarantine(layer,plan.key);}
  await mkdir(path.join(CACHE,"layers"),{recursive:true});await mkdir(path.join(CACHE,"building"),{recursive:true});await mkdir(path.join(CACHE,"locks"),{recursive:true});const lock=path.join(CACHE,"locks",`${plan.key}.lock`);const identity=lockOwnerIdentity();let owner=false;try{const handle=await open(lock,"wx");owner=true;await handle.writeFile(canonicalJson(lockRecord(identity)));await handle.close();}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;}
  if(!owner)return waitForLayer(snapshotRoot,plan,layer,lock);
  const renew=setInterval(()=>writeFile(lock,canonicalJson(lockRecord(identity))).catch(()=>undefined),60_000);renew.unref();try{return await buildLayer(snapshotRoot,plan,layer);}finally{clearInterval(renew);await rm(lock,{force:true});}}

export async function attachDependencyLayer(handle:DependencyLayerHandleV3,specRoot:string):Promise<void>{for(const relativeRoot of handle.manifest.node_modules_roots){const source=path.join(handle.root,"payload",...relativeRoot.split("/"));const target=path.join(specRoot,...relativeRoot.split("/"));await mkdir(target,{recursive:true});for(const entry of await readdir(source,{withFileTypes:true})){const from=path.join(source,entry.name);const to=path.join(target,entry.name);if(entry.name===".bin"){await cp(from,to,{recursive:true,verbatimSymlinks:true});continue;}if(entry.isDirectory()&&entry.name.startsWith("@")){await mkdir(to,{recursive:true});for(const child of await readdir(from,{withFileTypes:true}))await attachEntry(path.join(from,child.name),path.join(to,child.name),child);continue;}await attachEntry(from,to,entry);}}
  for(const link of handle.manifest.workspace_links){const target=inside(specRoot,link.target_path);const file=inside(specRoot,link.link_path);await rm(file,{recursive:true,force:true});await mkdir(path.dirname(file),{recursive:true});await symlink(target,file,process.platform==="win32"?"junction":"dir");}}
export function dependencyBinary(handle:DependencyLayerHandleV3,name:string,specRoot:string):string{const values=handle.manifest.binaries.filter((item)=>item.name===name).sort((a,b)=>a.path.length-b.path.length||a.path.localeCompare(b.path));if(values.length===0)throw new Error(`command_tool_invalid:unsealed_binary:${name}`);return inside(specRoot,values[0].path);}
export function dependencyRuntimeAdapter(handle:DependencyLayerHandleV3):string{const descriptor=handle.manifest.runtime_adapters.find((item)=>item.name==="node-runtime-v1");if(!descriptor)throw new Error("dependency_runtime_adapter_missing:node-runtime-v1");return inside(path.join(handle.root,"payload"),descriptor.path);}

async function buildLayer(snapshotRoot:string,plan:DependencyPlanV3,finalPath:string):Promise<DependencyLayerHandleV3>{if(!plan.manager)throw new Error("dependency_manager_unavailable:none");const temporary=await mkdtemp(path.join(CACHE,"building",`${plan.key}.`));const workspace=path.join(temporary,"workspace");const staged=path.join(temporary,"layer");const payload=path.join(staged,"payload");try{await cp(snapshotRoot,workspace,{recursive:true});const installed=await runInstall(plan,workspace,temporary);const roots=[...new Set(plan.package_manifests.map((item)=>{const dir=path.posix.dirname(item.path);return dir==="."?"node_modules":`${dir}/node_modules`;}))];const existing=[];for(const item of roots)if(await directory(path.join(workspace,...item.split("/"))))existing.push(item);if(existing.length===0)throw new Error("dependency_install_failed:node_modules_missing");const links=await workspaceLinks(workspace,existing);for(const item of existing){const target=path.join(payload,...item.split("/"));await mkdir(path.dirname(target),{recursive:true});await cp(path.join(workspace,...item.split("/")),target,{recursive:true,verbatimSymlinks:true});}for(const link of links)await rm(path.join(payload,...link.link_path.split("/")),{recursive:true,force:true});const adapterPath=".ty-context-runtime/node-runtime-adapter.cjs";const adapterBytes=Buffer.from(longTaskNodeRuntimeAdapterSourceV1());await mkdir(path.join(payload,".ty-context-runtime"),{recursive:true});await writeFile(path.join(payload,...adapterPath.split("/")),adapterBytes,{flag:"wx"});const runtimeAdapters=[{name:"node-runtime-v1" as const,path:adapterPath,sha256:sha256Hex(adapterBytes),size:adapterBytes.length}];const inventory=await packageInventory(payload);await makeReadonly(payload);const files=await merkle(payload);const manifest:DependencyLayerManifestV3={schema_version:"long-task-dependency-layer-v3",key:plan.key,node_modules_roots:existing.sort(),workspace_links:links.sort((a,b)=>a.link_path.localeCompare(b.link_path)),binaries:inventory.binaries,packages:inventory.packages,runtime_adapters:runtimeAdapters,files,install:installed,created_at:new Date().toISOString()};await mkdir(staged,{recursive:true});await writeFile(path.join(staged,"layer-manifest.json"),canonicalJson(manifest));await rename(staged,finalPath);return {key:plan.key,root:finalPath,manifest};}finally{await rm(temporary,{recursive:true,force:true});}}
async function runInstall(plan:DependencyPlanV3,workspace:string,temporary:string):Promise<DependencyLayerManifestV3["install"]>{const manager=plan.manager!;const argv=[...manager.invocation_prefix,...manager.install_argv];const env=minimalEnvironment(path.join(temporary,"home"),path.join(temporary,"tmp"),workspace,plan);await mkdir(env.HOME!,{recursive:true});await mkdir(env.TMP!,{recursive:true});const result=await run(manager.invocation_executable,argv,workspace,env,10*60_000);if(result.code!==0)throw new Error(`dependency_install_failed:${manager.name}:${result.code}:${sha256Hex(result.stderr)}`);return {exit_code:0,stdout_sha256:sha256Hex(result.stdout),stderr_sha256:sha256Hex(result.stderr)};}
async function readLayer(root:string,key:string):Promise<DependencyLayerHandleV3>{const manifest=JSON.parse(await readFile(path.join(root,"layer-manifest.json"),"utf8")) as DependencyLayerManifestV3;if(manifest.schema_version!=="long-task-dependency-layer-v3"||manifest.key!==key)throw new Error(`dependency_layer_corrupt:${key}:identity`);const current=await merkle(path.join(root,"payload"));if(canonicalJson(current)!==canonicalJson(manifest.files))throw new Error(`dependency_layer_corrupt:${key}:merkle`);return {key,root,manifest};}
export async function verifyDependencyLayerAtPath(root:string,key:string):Promise<DependencyLayerHandleV3>{return readLayer(root,key);}
async function waitForLayer(snapshotRoot:string,plan:DependencyPlanV3,root:string,lock:string):Promise<DependencyLayerHandleV3>{const deadline=Date.now()+10*60_000;while(Date.now()<deadline){try{return await readLayer(root,plan.key);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT"&&message(error).startsWith("dependency_layer_corrupt"))throw error;}if(!await regularFile(lock))return prepareDependencyLayer(snapshotRoot,plan) as Promise<DependencyLayerHandleV3>;await new Promise((resolve)=>setTimeout(resolve,200+Math.floor(Math.random()*200)));}throw new Error(`dependency_cache_timeout:${plan.key}`);}
async function workspaceLinks(workspace:string,roots:string[]):Promise<Array<{link_path:string;target_path:string}>>{const result=[];for(const relativeRoot of roots){const root=path.join(workspace,...relativeRoot.split("/"));for(const entry of await topLevelEntries(root)){const info=await lstat(entry.absolute);if(!info.isSymbolicLink())continue;const target=await realpath(entry.absolute);if(target===workspace||target.startsWith(`${workspace}${path.sep}`)){const relativeTarget=path.relative(workspace,target).replace(/\\/g,"/");if(!relativeTarget.includes("node_modules/"))result.push({link_path:`${relativeRoot}/${entry.relative}`,target_path:relativeTarget});}}}return result;}
async function topLevelEntries(root:string):Promise<Array<{absolute:string;relative:string}>>{const result=[];for(const entry of await readdir(root,{withFileTypes:true})){if(entry.name.startsWith("@")&&entry.isDirectory())for(const child of await readdir(path.join(root,entry.name)))result.push({absolute:path.join(root,entry.name,child),relative:`${entry.name}/${child}`});else result.push({absolute:path.join(root,entry.name),relative:entry.name});}return result;}
async function packageInventory(payload:string):Promise<{packages:Array<{name:string;version:string;path:string}>;binaries:Array<{name:string;path:string;package_name:string;version:string}>}>{const packages=[];const binaries=[];for(const file of await findNamed(payload,"package.json")){try{const value=JSON.parse(await readFile(file,"utf8")) as {name?:string;version?:string;bin?:string|Record<string,string>};if(!value.name||!value.version)continue;const relative=path.relative(payload,path.dirname(file)).replace(/\\/g,"/");packages.push({name:value.name,version:value.version,path:relative});const bin=typeof value.bin==="string"?{[value.name.split("/").pop()!]:value.bin}:value.bin??{};for(const [name,target] of Object.entries(bin))binaries.push({name,path:`${relative}/${target}`.replace(/\/+/g,"/"),package_name:value.name,version:value.version});}catch{}}return {packages:packages.sort((a,b)=>a.path.localeCompare(b.path)),binaries:binaries.sort((a,b)=>a.name.localeCompare(b.name)||a.path.localeCompare(b.path))};}
async function merkle(root:string):Promise<DependencyLayerFileV3[]>{const files:DependencyLayerFileV3[]=[];async function visit(dir:string,relative=""):Promise<void>{for(const entry of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){const rel=relative?`${relative}/${entry.name}`:entry.name;const file=path.join(dir,entry.name);const info=await lstat(file);if(info.isSymbolicLink()){const target=await readFileLink(file);const resolved=path.resolve(path.dirname(file),target);if(path.isAbsolute(target)||resolved!==path.resolve(root)&&!resolved.startsWith(`${path.resolve(root)}${path.sep}`))throw new Error(`dependency_layer_corrupt:symlink:${rel}`);files.push({path:rel,type:"symlink",mode:info.mode,size:0,target});}else if(entry.isDirectory())await visit(file,rel);else if(entry.isFile()){if(info.nlink>1)throw new Error(`dependency_layer_corrupt:hardlink:${rel}`);const bytes=await readFile(file);files.push({path:rel,type:"file",mode:info.mode,size:bytes.length,sha256:sha256Hex(bytes)});}else throw new Error(`dependency_layer_corrupt:special:${rel}`);}}await visit(root);return files;}
async function makeReadonly(root:string):Promise<void>{for(const entry of await readdir(root,{withFileTypes:true})){const file=path.join(root,entry.name);if(entry.isDirectory())await makeReadonly(file);if(!entry.isSymbolicLink())await chmod(file,entry.isDirectory()?0o555:0o444);}}
async function attachEntry(from:string,to:string,entry:{isDirectory():boolean;isFile():boolean;isSymbolicLink():boolean}):Promise<void>{if(entry.isDirectory()){await symlink(from,to,process.platform==="win32"?"junction":"dir");return;}if(entry.isFile()){await copyFile(from,to);await chmod(to,0o444);return;}if(entry.isSymbolicLink()){const target=await realpath(from);await symlink(target,to,process.platform==="win32"?"junction":undefined);return;}throw new Error(`dependency_layer_corrupt:attach:${from}`);}
async function findNamed(root:string,name:string):Promise<string[]>{const result:string[]=[];async function visit(dir:string):Promise<void>{for(const entry of await readdir(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())await visit(file);else if(entry.isFile()&&entry.name===name)result.push(file);}}await visit(root);return result;}
function minimalEnvironment(home:string,temp:string,workspace:string,plan:DependencyPlanV3):NodeJS.ProcessEnv{const manager=plan.manager!;const managerCache=path.join(CACHE,"manager-cache");const profile={read_paths:[workspace,home,temp,managerCache,path.dirname(process.execPath),path.dirname(manager.executable_path)],write_paths:[workspace,home,temp,managerCache],allow_child_process:true,allow_worker:true,allow_addons:true};const values:NodeJS.ProcessEnv={PATH:path.dirname(process.execPath),Path:path.dirname(process.execPath),PATHEXT:process.env.PATHEXT,SYSTEMROOT:process.env.SYSTEMROOT,WINDIR:process.env.WINDIR,ComSpec:process.env.ComSpec,HOME:home,USERPROFILE:home,TMP:temp,TEMP:temp,CI:"1",LANG:"C.UTF-8",npm_config_cache:managerCache,npm_config_audit:"false",npm_config_fund:"false",PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD:"1",...(plan.workspace_descriptors.length===0?{NODE_OPTIONS:nodePermissionOptions(profile)}:{})};for(const key of ["HTTP_PROXY","HTTPS_PROXY","NO_PROXY","http_proxy","https_proxy","no_proxy"])if(process.env[key])values[key]=process.env[key];return values;}
async function run(executable:string,argv:string[],cwd:string,env:NodeJS.ProcessEnv,timeout:number):Promise<{code:number;stdout:Buffer;stderr:Buffer}>{return new Promise((resolve,reject)=>{const child=spawn(executable,argv,{cwd,env,shell:false,windowsHide:true});const stdout:Buffer[]=[];const stderr:Buffer[]=[];let size=0;const capture=(target:Buffer[])=>(chunk:Buffer)=>{size+=chunk.length;if(size>16*1024*1024){child.kill();reject(new Error("dependency_install_output_limit"));return;}target.push(Buffer.from(chunk));};child.stdout.on("data",capture(stdout));child.stderr.on("data",capture(stderr));child.on("error",reject);const timer=setTimeout(()=>{child.kill();reject(new Error("dependency_install_timeout"));},timeout);child.on("close",(code)=>{clearTimeout(timer);resolve({code:code??-1,stdout:Buffer.concat(stdout),stderr:Buffer.concat(stderr)});});});}
async function readFileLink(file:string):Promise<string>{return (await import("node:fs/promises")).readlink(file);}
async function directory(file:string):Promise<boolean>{try{return (await stat(file)).isDirectory();}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return false;throw error;}}
async function regularFile(file:string):Promise<boolean>{try{return (await lstat(file)).isFile();}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return false;throw error;}}
async function quarantine(layer:string,key:string):Promise<void>{await mkdir(path.join(CACHE,"quarantine"),{recursive:true});await rename(layer,path.join(CACHE,"quarantine",`${key}.${Date.now()}`));}
function layerPath(key:string):string{return path.join(CACHE,"layers",key);}
function inside(root:string,relative:string):string{const resolved=path.resolve(root,...relative.split("/"));if(resolved!==path.resolve(root)&&!resolved.startsWith(`${path.resolve(root)}${path.sep}`))throw new Error(`dependency_layer_path_escape:${relative}`);return resolved;}
function message(error:unknown):string{return error instanceof Error?error.message:String(error);}
function lockOwnerIdentity():Record<string,unknown>{return {pid:process.pid,process_started_at:new Date(Date.now()-process.uptime()*1000).toISOString(),service_boot_id:sha256Hex(`${os.hostname()}\0${Math.floor(Date.now()/1000-os.uptime())}`),started_at:new Date().toISOString()};}
function lockRecord(identity:Record<string,unknown>):Record<string,unknown>{return {...identity,lease_expires_at:new Date(Date.now()+30*60_000).toISOString()};}
