import { spawn } from "node:child_process";
import { mkdtemp, readFile, realpath, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalValueJson, sha256Hex } from "./composite-campaign-codec.js";
import { managedHostLayout } from "./long-task-managed-host-layout.js";
import { nodePermissionArgv, type NodePermissionProfileV3 } from "./long-task-sandbox-node.js";
import { LONG_TASK_SANDBOX_POLICY } from "./long-task-sandbox-policy.js";
import type { LongTaskRedactorV3 } from "./long-task-redaction.js";

const DIAGNOSTIC_LIMIT=2*1024*1024;const PROTOCOL_LIMIT=16*1024*1024;
export interface OracleProcessResultV3 { exit_code:number; argv:string[]; protocol:Buffer; stdout:Buffer; stderr:Buffer; started_at:string; completed_at:string }
export interface OracleSandboxLaunchOptionsV3 { helper_path?:string; control_root?:string;sandbox_launcher_path?:string;sandbox_launcher_sha256?:string }
export interface HostSandboxCommandLaunchOptionsV1 extends OracleSandboxLaunchOptionsV3 { network?:"none"|"loopback";process_kind?:"command";isolation_group?:string;node_preload?:string }
export interface HostSandboxCommandResultV1 { exit_code:number;stdout:Buffer;stderr:Buffer }
export interface HostSandboxProcessV1 { completion:Promise<HostSandboxCommandResultV1>;terminate():void }

export async function runSealedOracle(executable:string,bundlePath:string,cwd:string,timeoutMs:number,environment:NodeJS.ProcessEnv,profile:NodePermissionProfileV3,redactor:LongTaskRedactorV3,options:OracleSandboxLaunchOptionsV3={}):Promise<OracleProcessResultV3>{
  const started_at=new Date().toISOString();const canonicalExecutable=await realpath(executable);const canonicalBundle=await realpath(bundlePath);const canonicalCwd=await realpath(cwd);const canonicalProfile:NodePermissionProfileV3={...profile,read_paths:await canonicalPaths(profile.read_paths),write_paths:await canonicalPaths(profile.write_paths)};const controlRoot=await selectControlRoot(options.control_root,canonicalProfile.write_paths);const sandboxRoot=await mkdtemp(path.join(controlRoot,".ty-context-oracle-host-"));const policyPath=path.join(sandboxRoot,"sandbox-policy.json");const protocolOutput=path.join(sandboxRoot,"protocol.json");const diagnosticOutput=path.join(sandboxRoot,"diagnostic.txt");const innerArgv=["--preserve-symlinks-main",...nodePermissionArgv(canonicalProfile),canonicalBundle];const helper=await resolveHelper(options.helper_path);
  const policy={schema_version:"ty-context-host-sandbox-v1",executable:canonicalExecutable,cwd:canonicalCwd,read_paths:canonicalProfile.read_paths,write_paths:canonicalProfile.write_paths,protocol_output:protocolOutput,diagnostic_output:diagnosticOutput,timeout_ms:timeoutMs,network:"none",allow_child_process:false};
  try{
    await writeFile(policyPath,canonicalValueJson(policy),{flag:"wx"});const launcher=await sandboxLauncher(helper,options);const result=await launchHelper(helper,["sandbox","--policy",policyPath,...launcher,"--",canonicalExecutable,...innerArgv],canonicalCwd,timeoutMs,sanitizeHelperEnvironment(environment),redactor);return {...result,argv:innerArgv,started_at,completed_at:new Date().toISOString()};
  }finally{await rm(sandboxRoot,{recursive:true,force:true});}
}

export async function runHostSandboxCommandV1(executable:string,argv:string[],cwd:string,timeoutMs:number,environment:NodeJS.ProcessEnv,profile:NodePermissionProfileV3,redactor:LongTaskRedactorV3,options:HostSandboxCommandLaunchOptionsV1={}):Promise<HostSandboxCommandResultV1>{const process=await startHostSandboxCommandV1(executable,argv,cwd,timeoutMs,environment,profile,redactor,options);return process.completion;}

export async function startHostSandboxCommandV1(executable:string,argv:string[],cwd:string,timeoutMs:number,environment:NodeJS.ProcessEnv,profile:NodePermissionProfileV3,redactor:LongTaskRedactorV3,options:HostSandboxCommandLaunchOptionsV1={}):Promise<HostSandboxProcessV1>{const canonicalExecutable=await realpath(executable);const canonicalCwd=await realpath(cwd);const canonicalProfile:NodePermissionProfileV3={...profile,read_paths:await canonicalPaths(profile.read_paths),write_paths:await canonicalPaths(profile.write_paths)};const nodePreload=await commandPreload(options.node_preload,canonicalProfile.read_paths);const controlRoot=await selectControlRoot(options.control_root,canonicalProfile.write_paths);const sandboxRoot=await mkdtemp(path.join(controlRoot,".ty-context-command-host-"));const policyPath=path.join(sandboxRoot,"sandbox-policy.json");const helper=await resolveHelper(options.helper_path);const policy={schema_version:"ty-context-host-sandbox-v1",process_kind:options.process_kind??"command",isolation_group:options.isolation_group??null,node_preload:nodePreload,executable:canonicalExecutable,cwd:canonicalCwd,read_paths:canonicalProfile.read_paths,write_paths:canonicalProfile.write_paths,protocol_output:null,diagnostic_output:null,timeout_ms:timeoutMs,network:options.network??"none",allow_child_process:profile.allow_child_process===true,allow_worker:profile.allow_worker===true,allow_addons:profile.allow_addons===true,process_limit:profile.allow_child_process===true?128:1};try{await writeFile(policyPath,canonicalValueJson(policy),{flag:"wx"});const launcher=await sandboxLauncher(helper,options);const running=startHelper(helper,["sandbox","--policy",policyPath,...launcher,"--",canonicalExecutable,...argv],canonicalCwd,timeoutMs,sanitizeHelperEnvironment(environment),redactor);return {terminate:running.terminate,completion:running.completion.then(({protocol,stderr,exit_code})=>({exit_code,stdout:protocol,stderr})).finally(()=>rm(sandboxRoot,{recursive:true,force:true}))};}catch(error){await rm(sandboxRoot,{recursive:true,force:true});throw error;}}

async function launchHelper(helper:string,args:string[],cwd:string,timeoutMs:number,environment:NodeJS.ProcessEnv,redactor:LongTaskRedactorV3):Promise<{exit_code:number;protocol:Buffer;stdout:Buffer;stderr:Buffer}>{
  return startHelper(helper,args,cwd,timeoutMs,environment,redactor).completion;
}
function startHelper(helper:string,args:string[],cwd:string,timeoutMs:number,environment:NodeJS.ProcessEnv,redactor:LongTaskRedactorV3):{completion:Promise<{exit_code:number;protocol:Buffer;stdout:Buffer;stderr:Buffer}>;terminate():void}{
  let terminate=()=>{};const completion=new Promise<{exit_code:number;protocol:Buffer;stdout:Buffer;stderr:Buffer}>((resolve,reject)=>{
    const child=spawn(helper,args,{cwd,shell:false,env:environment,windowsHide:true,stdio:["ignore","pipe","pipe"]});const protocol:Buffer[]=[];const stderr:Buffer[]=[];const protocolRedactor=redactor.stream();const stderrRedactor=redactor.stream();let protocolSize=0;let diagnosticSize=0;let settled=false;
    const fail=(error:Error)=>{if(settled)return;settled=true;clearTimeout(timer);child.kill();reject(error);};
    terminate=()=>fail(new Error("command_terminated"));
    const capture=(target:Buffer[],kind:"protocol"|"diagnostic",stream:ReturnType<LongTaskRedactorV3["stream"]>)=>(chunk:Buffer)=>{const raw=Buffer.from(chunk);if(kind==="protocol"){protocolSize+=raw.length;if(protocolSize>PROTOCOL_LIMIT){fail(new Error("oracle_protocol_output_limit_exceeded"));return;}}else{diagnosticSize+=raw.length;if(diagnosticSize>DIAGNOSTIC_LIMIT){fail(new Error("command_output_limit_exceeded"));return;}}const value=stream.push(raw);if(value.length)target.push(value);};
    child.stdout.on("data",capture(protocol,"protocol",protocolRedactor));child.stderr.on("data",capture(stderr,"diagnostic",stderrRedactor));child.on("error",(error)=>fail(error));const timer=setTimeout(()=>fail(new Error("command_timeout")),timeoutMs+5000);timer.unref();
    child.on("close",(code)=>{if(settled)return;settled=true;clearTimeout(timer);protocol.push(protocolRedactor.finish());stderr.push(stderrRedactor.finish());resolve({exit_code:code??-1,protocol:Buffer.concat(protocol),stdout:Buffer.alloc(0),stderr:Buffer.concat(stderr)});});
  });return {completion,terminate:()=>terminate()};
}

async function commandPreload(requested:string|undefined,readPaths:string[]):Promise<string|null>{if(!requested)return null;const preload=await realpath(requested);if(!readPaths.some((root)=>inside(root,preload)))throw new Error("node_runtime_adapter_outside_read_roots");if(sha256Hex(await readFile(preload))!==LONG_TASK_SANDBOX_POLICY.node_runtime_adapter_sha256)throw new Error("node_runtime_adapter_identity");return preload;}

async function canonicalPaths(values:string[]):Promise<string[]>{const result:string[]=[];for(const value of values){try{result.push(await realpath(value));}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}return [...new Set(result)].sort(pathCompare);}
async function selectControlRoot(requested:string|undefined,writePaths:string[]):Promise<string>{if(writePaths.length===0)throw new Error("sandbox_control_root_missing");const value=await realpath(requested??writePaths[writePaths.length-1]);if(!writePaths.some((root)=>inside(root,value)))throw new Error("sandbox_control_root_outside_write_root");return value;}
async function resolveHelper(injected:string|undefined):Promise<string>{const expected=injected??managedHostLayout().helper_path;try{return await realpath(expected);}catch{throw new Error(`host_completion_gate_unavailable:managed_helper_missing:${expected}`);}}
async function sandboxLauncher(helper:string,options:OracleSandboxLaunchOptionsV3):Promise<string[]>{const injected=options.sandbox_launcher_path!==undefined||options.sandbox_launcher_sha256!==undefined;if(injected){if(!options.sandbox_launcher_path||!options.sandbox_launcher_sha256)throw new Error("sandbox_launcher_identity_incomplete");const resolved=await realpath(options.sandbox_launcher_path);if(sha256Hex(await readFile(resolved))!==options.sandbox_launcher_sha256)throw new Error("sandbox_launcher_identity_changed");return ["--launcher",resolved,"--launcher-sha256",options.sandbox_launcher_sha256];}const {resolveManagedSandboxLauncherV1}=await import("./long-task-host-runtime-identity.js");const identity=await resolveManagedSandboxLauncherV1(helper);return ["--launcher",identity.path,"--launcher-sha256",identity.sha256];}
function sanitizeHelperEnvironment(environment:NodeJS.ProcessEnv):NodeJS.ProcessEnv{const result={...environment};for(const key of ["NODE_OPTIONS","NODE_PATH","TY_CONTEXT_HOST_MAINTAINER_DEBUG","TY_CONTEXT_ORACLE_PROTOCOL_FILE","TY_CONTEXT_ORACLE_DIAGNOSTIC_FILE","TY_CONTEXT_ORACLE_PROTOCOL_FD"])delete result[key];return result;}
function inside(root:string,candidate:string):boolean{const left=normalized(root);const right=normalized(candidate);return right===left||right.startsWith(`${left}${path.sep}`);}
function normalized(value:string):string{const resolved=path.resolve(value).replace(/^\\\\\?\\/u,"");return process.platform==="win32"?resolved.toLocaleLowerCase("en-US"):resolved;}
function pathCompare(left:string,right:string):number{return normalized(left).localeCompare(normalized(right));}
