import { chmod, mkdir, readFile, realpath, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { FrozenVerificationSpecV3, CommandStepV3, DependencyPlanV3 } from "./long-task-contract-schema.js";
import type { DependencyLayerHandleV3 } from "./long-task-dependency-layer.js";
import { dependencyBinary, dependencyRuntimeAdapter } from "./long-task-dependency-layer.js";
import { nodeModuleEntrypointArgv, nodePermissionArgv as rawNodePermissionArgv, nodePermissionOptions as rawNodePermissionOptions, type NodePermissionProfileV3 } from "./long-task-sandbox-node.js";
import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import { isSandboxAccessError } from "./long-task-sandbox-node.js";
import { declaredLongTaskEnvironment } from "./long-task-environment.js";
import type { LongTaskRedactorV3 } from "./long-task-redaction.js";
import { runHostSandboxCommandV1, type HostSandboxCommandLaunchOptionsV1, type OracleSandboxLaunchOptionsV3 } from "./long-task-oracle-runner.js";

export interface CommandStepRunV3 { id:string; tool:CommandStepV3["tool"]; executable:string; argv:string[]; exit_code:number; sandbox_denied:boolean; stdout_path:string; stdout_sha256:string; stderr_path:string; stderr_sha256:string; started_at:string; completed_at:string }
export interface CommandStepsResultV3 { steps:CommandStepRunV3[]; exit_code:number }
export async function runLongTaskCommandSteps(spec:FrozenVerificationSpecV3,specRoot:string,artifactRoot:string,commandRoot:string,tempRoot:string,plan:DependencyPlanV3,layer:DependencyLayerHandleV3|null,browserRoot:string|null,baseEnvironment:NodeJS.ProcessEnv,declaredEnvironment:Readonly<Record<string,string>>,redactor:LongTaskRedactorV3,sandbox:OracleSandboxLaunchOptionsV3={}):Promise<CommandStepsResultV3>{
  const results:CommandStepRunV3[]=[];
  for(const step of spec.command_steps){
    const descriptor=resolveStep(step,specRoot,plan,layer);
    const managerBin=step.tool==="package_script"?await writePackageManagerShim(tempRoot,plan):null;
    const effectiveArgv=step.tool==="playwright_test"?[...descriptor.argv,"--output",path.join(artifactRoot,"playwright-output",step.id)]:descriptor.argv;
    for(const root of descriptor.adapter_write_roots)await mkdir(root,{recursive:true});
    const profile={read_paths:[specRoot,artifactRoot,tempRoot,...(layer?[layer.root]:[]),...(browserRoot?[browserRoot]:[]),...descriptor.identity_roots],write_paths:[artifactRoot,tempRoot,...descriptor.adapter_write_roots],allow_child_process:step.tool!=="node_script",allow_worker:step.tool==="project_binary"||step.tool==="playwright_test",allow_addons:step.tool!=="node_script"};
    const permission=nodePermissionArgv(profile);
    const argv=descriptor.node?["--preserve-symlinks","--preserve-symlinks-main",...permission,...nodeModuleEntrypointArgv(descriptor.target,effectiveArgv)]:effectiveArgv;
    const commandEnvironment=managerBin?prependPath(baseEnvironment,managerBin):baseEnvironment;
    const env=declaredLongTaskEnvironment({...commandEnvironment,NODE_OPTIONS:`--preserve-symlinks ${nodePermissionOptions(profile)}`},step.environment_refs,declaredEnvironment);
    const output=path.join(commandRoot,"steps",step.id);
    await mkdir(output,{recursive:true});
    const started_at=new Date().toISOString();
    const timeout=Math.min(step.timeout_ms,spec.timeout_ms);
    const launch={...sandbox,control_root:sandbox.control_root??tempRoot,node_preload:descriptor.node&&layer?dependencyRuntimeAdapter(layer):undefined,preserve_symlinks_main:step.tool==="project_binary"||step.tool==="playwright_test"};
    const run=step.tool==="playwright_test"
      ?await executePlaywright(descriptor.executable,argv,descriptor.cwd,env,timeout,redactor,profile,{...sandbox,control_root:sandbox.control_root??tempRoot},specRoot,artifactRoot,commandRoot,step.id,layer,browserRoot)
      :await execute(descriptor.executable,argv,descriptor.cwd,env,timeout,redactor,profile,{...launch,network:"none"});
    const stdoutPath=path.join(output,"stdout.txt");
    const stderrPath=path.join(output,"stderr.txt");
    await writeFile(stdoutPath,run.stdout);
    await writeFile(stderrPath,run.stderr);
    results.push({id:step.id,tool:step.tool,executable:descriptor.executable,argv,exit_code:run.code,sandbox_denied:isSandboxAccessError(run.stderr),stdout_path:stdoutPath,stdout_sha256:sha256Hex(run.stdout),stderr_path:stderrPath,stderr_sha256:sha256Hex(run.stderr),started_at,completed_at:new Date().toISOString()});
    if(run.code!==0)return {steps:results,exit_code:run.code};
  }
  return {steps:results,exit_code:0};
}
function resolveStep(step:CommandStepV3,specRoot:string,plan:DependencyPlanV3,layer:DependencyLayerHandleV3|null):{executable:string;target:string;argv:string[];cwd:string;node:boolean;identity_roots:string[];adapter_write_roots:string[]}{const cwd=step.cwd==="."?specRoot:inside(specRoot,step.cwd);if(step.tool==="node_script")return {executable:process.execPath,target:inside(specRoot,step.target),argv:[...step.argv],cwd,node:true,identity_roots:[],adapter_write_roots:[]};if(!layer||!plan.manager)throw new Error(`dependency_layer_missing:${step.id}`);if(step.tool==="package_script"){const manager=plan.manager;const node=normalized(manager.invocation_executable)===normalized(process.execPath);const [target="",...prefix]=manager.invocation_prefix;return {executable:manager.invocation_executable,target:node?target:"",argv:node?[...prefix,"run",step.target,...(step.argv.length?["--",...step.argv]:[])]:[...manager.invocation_prefix,"run",step.target,...(step.argv.length?["--",...step.argv]:[])],cwd,node,identity_roots:[path.resolve(path.dirname(manager.executable_path),"..")],adapter_write_roots:[]};}const name=step.tool==="playwright_test"?"playwright":step.target;const binary=dependencyBinary(layer,name,specRoot);return {executable:process.execPath,target:binary,argv:step.tool==="playwright_test"?["test",step.target,...step.argv]:[...step.argv],cwd,node:true,identity_roots:name==="vitest"||step.tool==="playwright_test"?workspaceProbeFiles(specRoot):[],adapter_write_roots:name==="vitest"?[path.join(specRoot,"node_modules",".vite-temp")]:[]};}
async function execute(executable:string,argv:string[],cwd:string,env:NodeJS.ProcessEnv,timeout:number,redactor:LongTaskRedactorV3,profile:NodePermissionProfileV3,sandbox:HostSandboxCommandLaunchOptionsV1&{network:"none"|"loopback"}):Promise<{code:number;stdout:Buffer;stderr:Buffer}>{const result=await runHostSandboxCommandV1(executable,argv,cwd,timeout,env,profile,redactor,sandbox);return {code:result.exit_code,stdout:result.stdout,stderr:result.stderr};}
async function executePlaywright(executable:string,argv:string[],cwd:string,env:NodeJS.ProcessEnv,timeout:number,redactor:LongTaskRedactorV3,profile:NodePermissionProfileV3,sandbox:OracleSandboxLaunchOptionsV3,specRoot:string,artifactRoot:string,commandRoot:string,stepId:string,layer:DependencyLayerHandleV3|null,browserRoot:string|null):Promise<{code:number;stdout:Buffer;stderr:Buffer}>{
  if(!layer||!browserRoot)throw new Error("playwright_browser_unsealed:browser_layer_missing");
  const hostRoot=path.join(commandRoot,"host-playwright",stepId);const browserProfile=path.join(hostRoot,"browser-profile");const bridgeRoot=path.join(hostRoot,"bridge");
  await Promise.all([mkdir(browserProfile,{recursive:true}),mkdir(bridgeRoot,{recursive:true})]);
  const browserExecutable=await browserExecutablePath(browserRoot);const workerAdapter=await playwrightWorkerAdapterPath(browserRoot);const supervisor=await realpath(fileURLToPath(new URL("./long-task-playwright-supervisor.js",import.meta.url)));const bridge=await realpath(fileURLToPath(new URL("./long-task-playwright-bridge.js",import.meta.url)));const coreBundle=await realpath(path.join(specRoot,"node_modules","playwright-core","lib","coreBundle.js"));
  const ready=path.join(bridgeRoot,"ready.json");const done=path.join(bridgeRoot,"done");const configPath=path.join(hostRoot,"supervisor.json");
  const browserArgs=["--headless=new","--no-sandbox","--disable-breakpad","--disable-crash-reporter","--noerrdialogs","--disable-gpu","--no-first-run","--no-default-browser-check","--disable-background-networking","--disable-component-update","--disable-default-apps","--disable-extensions","--disable-sync","--metrics-recording-only","--remote-debugging-address=127.0.0.1","--remote-debugging-port=0",`--user-data-dir=${browserProfile}`,"about:blank"];
  const config={schema_version:"long-task-playwright-supervisor-v1",timeout_ms:timeout,browser:{executable:browserExecutable,argv:browserArgs,cwd:path.dirname(browserExecutable),profile:browserProfile},bridge:{entry:bridge,core_bundle:coreBundle,root:bridgeRoot,ready,done},test:{executable,argv, cwd,worker_adapter:workerAdapter}};
  const configBytes=Buffer.from(canonicalJson(config));await writeFile(configPath,configBytes,{flag:"wx"});
  const supervisorProfile={read_paths:[...profile.read_paths,browserRoot,layer.root,supervisor,bridge,coreBundle,workerAdapter],write_paths:[...profile.write_paths,hostRoot],allow_child_process:true,allow_worker:true,allow_addons:true};
  const supervisorArgv=["--preserve-symlinks","--preserve-symlinks-main",...nodePermissionArgv(supervisorProfile),...nodeModuleEntrypointArgv(supervisor,[configPath])];
  return execute(process.execPath,supervisorArgv,path.dirname(supervisor),{...env,TY_CONTEXT_PLAYWRIGHT_SUPERVISOR_CONFIG_SHA256:sha256Hex(configBytes)},timeout,redactor,supervisorProfile,{...sandbox,control_root:hostRoot,network:"loopback",process_kind:"command",node_preload:dependencyRuntimeAdapter(layer),preserve_symlinks_main:true});
}
async function browserExecutablePath(browserRoot:string):Promise<string>{const manifest=JSON.parse(await readFile(path.join(path.dirname(browserRoot),"layer-manifest.json"),"utf8")) as {schema_version?:unknown;executables?:Array<{path?:unknown}>};if(manifest.schema_version!=="long-task-browser-layer-v3"||!Array.isArray(manifest.executables))throw new Error("playwright_browser_unsealed:manifest_invalid");const paths=manifest.executables.flatMap((item)=>typeof item.path==="string"?[item.path.replace(/\\/gu,"/")]:[]);const relative=paths.find((value)=>/(^|\/)chrome-headless-shell(?:\.exe)?$/iu.test(value))??paths.find((value)=>/(^|\/)chrome(?:\.exe)?$/iu.test(value));if(!relative||path.isAbsolute(relative)||relative.split("/").includes(".."))throw new Error("playwright_browser_unsealed:executable_missing");const executable=await realpath(path.join(browserRoot,...relative.split("/")));const root=normalized(browserRoot);const candidate=normalized(executable);if(candidate!==root&&!candidate.startsWith(`${root}${path.sep}`))throw new Error("playwright_browser_unsealed:executable_escape");return executable;}
async function playwrightWorkerAdapterPath(browserRoot:string):Promise<string>{const manifest=JSON.parse(await readFile(path.join(path.dirname(browserRoot),"layer-manifest.json"),"utf8")) as {schema_version?:unknown;node_runtime?:{worker_adapter?:{target?:unknown;size?:unknown;sha256?:unknown}}};const descriptor=manifest.node_runtime?.worker_adapter;if(manifest.schema_version!=="long-task-browser-layer-v3"||typeof descriptor?.target!=="string"||typeof descriptor.size!=="number"||typeof descriptor.sha256!=="string"||path.isAbsolute(descriptor.target)||descriptor.target.split(/[\\/]/u).includes(".."))throw new Error("playwright_worker_adapter_invalid");const adapter=await realpath(path.join(browserRoot,...descriptor.target.replace(/\\/gu,"/").split("/")));const root=normalized(browserRoot);if(normalized(adapter)!==root&&!normalized(adapter).startsWith(`${root}${path.sep}`))throw new Error("playwright_worker_adapter_escape");const bytes=await readFile(adapter);if(bytes.length!==descriptor.size||sha256Hex(bytes)!==descriptor.sha256)throw new Error("playwright_worker_adapter_changed");return adapter;}
function inside(root:string,relative:string):string{const resolved=path.resolve(root,...relative.replace(/\\/g,"/").split("/"));if(resolved!==path.resolve(root)&&!resolved.startsWith(`${path.resolve(root)}${path.sep}`))throw new Error(`wrong_cwd:${relative}`);return resolved;}
function normalized(value:string):string{const resolved=path.resolve(value).replace(/^\\\\\?\\/u,"");return process.platform==="win32"?resolved.toLocaleLowerCase("en-US"):resolved;}
function workspaceProbeFiles(root:string):string[]{const values=[];let current=path.resolve(root);while(true){for(const name of ["package.json","pnpm-workspace.yaml","lerna.json","deno.json","deno.jsonc","tsconfig.json","jsconfig.json"])values.push(path.join(current,name));const parent=path.dirname(current);if(parent===current)break;current=parent;}return values;}
function nodePermissionArgv(profile:NodePermissionProfileV3):string[]{return rawNodePermissionArgv(commandPermissionProfile(profile));}
function nodePermissionOptions(profile:NodePermissionProfileV3):string{return rawNodePermissionOptions(commandPermissionProfile(profile));}
function commandPermissionProfile(profile:NodePermissionProfileV3):NodePermissionProfileV3{return {...profile,read_paths:[...profile.read_paths,...profile.write_paths]};}
async function writePackageManagerShim(tempRoot:string,plan:DependencyPlanV3):Promise<string>{const manager=plan.manager;if(!manager)throw new Error("dependency_manager_unavailable:none");const root=path.join(tempRoot,"manager-bin");await mkdir(root,{recursive:true});if(process.platform==="win32"){const target=path.join(root,`${manager.name}.cmd`);const command=[manager.invocation_executable,...manager.invocation_prefix].map(cmdQuote).join(" ");await writeFile(target,`@echo off\r\n${command} %*\r\n`);return root;}const target=path.join(root,manager.name);const command=[manager.invocation_executable,...manager.invocation_prefix].map(shellQuote).join(" ");await writeFile(target,`#!/bin/sh\nexec ${command} "$@"\n`);await chmod(target,0o555);return root;}
function prependPath(environment:NodeJS.ProcessEnv,directory:string):NodeJS.ProcessEnv{const current=environment.PATH??environment.Path??"";const value=current?`${directory}${path.delimiter}${current}`:directory;return {...environment,PATH:value,Path:value};}
function shellQuote(value:string):string{return `'${value.replaceAll("'","'\"'\"'")}'`;}
function cmdQuote(value:string):string{return `"${value.replaceAll("%","%%").replaceAll('"','""')}"`;}
