import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import type { CompiledContractV3, ExternalBlockerReasonCode, FrozenEnvironmentProbeV3 } from "./long-task-contract-schema.js";
import type { EnvironmentProbeResultV3, EnvironmentProbeRunV3, LongTaskFindingV2, VerificationRunResultV2 } from "./long-task-run-result.js";

export interface ExternalBlockerClassificationV3 { externally_blocked:boolean;findings:LongTaskFindingV2[];minimal_user_action?:string;blocked_spec_ids:string[];failed_spec_ids:string[];environment_requirement_ids:string[];reason_codes:string[];probe_result_ids:string[] }

export function classifyExternalBlocker(run:VerificationRunResultV2,contract:CompiledContractV3,probeRun?:EnvironmentProbeRunV3,supplementalFailures:LongTaskFindingV2[]=[]):ExternalBlockerClassificationV3{
  const requirements=contract.verification_specs.flatMap((spec)=>spec.environment_requirements.map((requirement)=>({spec,requirement})));const findings:LongTaskFindingV2[]=[...(probeRun?.findings??[])];const candidates:Array<{spec_id:string;requirement_id:string;reason_code:string;action:string;result_ids:string[]}>=[];
  if(run.spec_results.some((result)=>result.status==="blocked"||result.external_blocker))findings.push(finding("environment_probe_failed","Harness probe records only","legacy Oracle-authored blocker"));
  if(requirements.length===0)return empty(findings);
  if(!probeRun){for(const {spec} of requirements)findings.push(attributed("environment_probe_failed",spec.id,"current Harness probe run","missing"));return empty(findings);}
  const environmentHash=sha256Hex(canonicalJson(run.environment));if(probeRun.run_id!==run.run_id||probeRun.snapshot_sha256!==run.snapshot.snapshot_sha256||probeRun.environment_manifest_sha256!==environmentHash)findings.push(finding("environment_probe_failed",{run_id:run.run_id,snapshot:run.snapshot.snapshot_sha256,environment:environmentHash},{run_id:probeRun.run_id,snapshot:probeRun.snapshot_sha256,environment:probeRun.environment_manifest_sha256}));
  for(const {spec,requirement} of requirements){
    const primary=findResult(probeRun,spec.id,requirement.id,"primary",requirement.probe_spec_id);const alternatives=requirement.local_alternative_probe_ids.map((id)=>findResult(probeRun,spec.id,requirement.id,"alternative",id));
    if(!primary){findings.push(attributed("environment_probe_failed",spec.id,"current primary probe result",requirement.probe_spec_id));continue;}
    const primaryProbe=contract.environment_probes.find((item)=>item.id===requirement.probe_spec_id);const primaryValidity=primaryProbe?resultValidity(primary,primaryProbe,probeRun,requirement.reason_code):"invalid";if(primaryValidity!=="valid"){findings.push(attributed(primaryValidity==="service_not_persistent"?"external_service_not_persistent":"environment_probe_failed",spec.id,"valid current primary probe result",primary));continue;}
    const missing=requirement.local_alternative_probe_ids.filter((_,index)=>!alternatives[index]);if(missing.length){findings.push(attributed("external_blocker_alternatives_not_run",spec.id,requirement.local_alternative_probe_ids,missing));continue;}
    let alternativesValid=true;for(let index=0;index<alternatives.length;index+=1){const result=alternatives[index]!;const probe=contract.environment_probes.find((item)=>item.id===requirement.local_alternative_probe_ids[index]);if(!probe||resultValidity(result,probe,probeRun,requirement.reason_code)!=="valid"){alternativesValid=false;findings.push(attributed("environment_probe_failed",spec.id,"valid current alternative probe result",result));}}
    if(!alternativesValid)continue;
    const primaryCompleted=Math.max(...primary.attempts.map((item)=>Date.parse(item.completed_at)));if(alternatives.some((result)=>result!.attempts.some((item)=>Date.parse(item.started_at)<primaryCompleted))){findings.push(attributed("external_blocker_alternatives_not_run",spec.id,"alternatives start after the final primary attempt",alternatives.map((result)=>result!.attempts[0]?.started_at)));continue;}
    const successful=alternatives.find((result)=>result?.satisfied);if(primary.satisfied||successful)continue;
    if(!reasonMatches(requirement.reason_code,primary)){findings.push(attributed("external_blocker_reason_mismatch",spec.id,requirement.reason_code,primary.attempts.map((item)=>item.error_code)));continue;}
    candidates.push({spec_id:spec.id,requirement_id:requirement.id,reason_code:requirement.reason_code,action:requirement.minimal_user_action,result_ids:[primary.result_id,...alternatives.map((item)=>item!.result_id)]});
  }
  const productFailures=[...run.findings,...supplementalFailures];const productFailure=productFailures.length>0||run.spec_results.some((result)=>result.status==="failed");if(candidates.length&&productFailure)findings.push(finding("implementation_failure_with_blocker","no implementation/assertion/binding/integrity failure",productFailures.map((item)=>item.category)));
  if(findings.length||candidates.length===0)return empty(findings);
  const actions=[...new Set(candidates.map((item)=>item.action))];return {externally_blocked:true,findings:[],minimal_user_action:actions.join("; "),blocked_spec_ids:unique(candidates.map((item)=>item.spec_id)),failed_spec_ids:[],environment_requirement_ids:unique(candidates.map((item)=>item.requirement_id)),reason_codes:unique(candidates.map((item)=>item.reason_code)),probe_result_ids:unique(candidates.flatMap((item)=>item.result_ids))};
}

function resultValidity(result:EnvironmentProbeResultV3,probe:FrozenEnvironmentProbeV3,run:EnvironmentProbeRunV3,reason:ExternalBlockerReasonCode):"valid"|"invalid"|"service_not_persistent"{
  if(result.probe_id!==probe.id||result.reason_code!==reason||result.attempts.length===0||result.satisfied!==result.attempts.some((item)=>item.satisfied))return "invalid";const descriptor=sha256Hex(canonicalJson(probe.descriptor));const prefix=`runs/${run.run_id}/environment-probes/`;
  if(result.attempts.some((item)=>item.probe_id!==probe.id||canonicalJson(item.descriptor)!==canonicalJson(probe.descriptor)||item.run_id!==run.run_id||item.snapshot_sha256!==run.snapshot_sha256||item.environment_manifest_sha256!==run.environment_manifest_sha256||item.descriptor_sha256!==descriptor||item.duration_ms<0||!validTime(item.started_at,item.completed_at,item.duration_ms)||!validOutcome(item)||!validEvidencePath(item.stdout_path,prefix)||!validEvidencePath(item.stderr_path,prefix)||!hash(item.stdout_sha256)||!hash(item.stderr_sha256)||item.artifact_refs.some((artifact)=>!validEvidencePath(artifact.path,prefix)||!hash(artifact.sha256)||!Number.isInteger(artifact.size)||artifact.size<0)||(probe.artifact_globs.length>0&&item.artifact_refs.length===0)))return "invalid";
  const expected=result.role==="primary"&&reason==="external_service_persistently_unavailable"?[0,5_000,20_000]:[0];if(result.attempts.length!==expected.length||result.attempts.some((item,index)=>item.attempt!==index+1||item.scheduled_offset_ms!==expected[index]))return result.role==="primary"&&reason==="external_service_persistently_unavailable"?"service_not_persistent":"invalid";
  if(expected.length===3){const origin=Date.parse(result.attempts[0].started_at);const offsets=result.attempts.map((item)=>Date.parse(item.started_at)-origin);if(offsets.some((value,index)=>value<expected[index]-1_000||value>expected[index]+10_000))return "service_not_persistent";}
  return "valid";
}
function validTime(started:string,completed:string,duration:number):boolean{const left=Date.parse(started);const right=Date.parse(completed);return Number.isFinite(left)&&Number.isFinite(right)&&right>=left&&Math.abs(right-left-duration)<=5;}
function validOutcome(item:EnvironmentProbeResultV3["attempts"][number]):boolean{return (item.exit_code===null||(Number.isInteger(item.exit_code)&&item.exit_code>=0&&item.exit_code<=255))&&(item.signal===null||/^[A-Z][A-Z0-9_-]{0,31}$/u.test(item.signal))&&(item.error_code===null||/^[A-Za-z][A-Za-z0-9_.-]{0,127}$/u.test(item.error_code));}
function validEvidencePath(value:string,prefix:string):boolean{return value.replace(/\\/gu,"/").startsWith(prefix)&&!value.split(/[\\/]/u).includes("..");}
function hash(value:string):boolean{return /^[a-f0-9]{64}$/u.test(value);}
function reasonMatches(reason:ExternalBlockerReasonCode,result:EnvironmentProbeResultV3):boolean{const codes=result.attempts.map((item)=>item.error_code).filter((value):value is string=>!!value);if(codes.length===0)return false;return codes.every((code)=>matches(reason,code));}
function matches(reason:ExternalBlockerReasonCode,code:string):boolean{const lower=code.toLocaleLowerCase("en-US");if(reason==="mfa_required")return ["mfa_required","aadsts50076","aadsts50079"].includes(lower);if(reason==="credential_unavailable")return ["credential_unavailable","not_authenticated","cli_auth_failed"].includes(lower);if(reason==="permission_denied")return ["eacces","eperm","permission_denied","http_403"].includes(lower);if(reason==="user_contract_decision_required")return ["user_contract_decision_required","active_contract_revision_requires_user_authorization"].includes(lower);if(reason==="external_approval_required")return ["external_approval_required","approval_pending"].includes(lower);if(reason==="platform_or_legal_restriction")return ["platform_or_legal_restriction","platform_unsupported","legal_restriction"].includes(lower);return ["econnrefused","etimedout","enetunreach","ehostunreach","econnreset","external_service_persistently_unavailable","http_429"].includes(lower)||/^http_5\d\d$/u.test(lower);}
function findResult(run:EnvironmentProbeRunV3,spec:string,requirement:string,role:"primary"|"alternative",probe:string):EnvironmentProbeResultV3|undefined{const id=`${spec}:${requirement}:${role}:${probe}`;return Object.values(run.results).find((item)=>item.result_id===id&&item.verification_spec_id===spec&&item.environment_requirement_id===requirement&&item.role===role&&item.probe_id===probe);}
function empty(findings:LongTaskFindingV2[]):ExternalBlockerClassificationV3{return {externally_blocked:false,findings,blocked_spec_ids:[],failed_spec_ids:unique(findings.flatMap((item)=>item.verification_spec_id?[item.verification_spec_id]:[])),environment_requirement_ids:[],reason_codes:[],probe_result_ids:[]};}
function finding(category:string,expected:unknown,actual:unknown):LongTaskFindingV2{return {category,expected,actual,evidence_path:"latest environment-probes.json",next_action:"Run every frozen primary and local-alternative probe and repair the reported condition",reverify_command:"ty-context composite-long-task final-gate"};}
function attributed(category:string,spec:string,expected:unknown,actual:unknown):LongTaskFindingV2{return {...finding(category,expected,actual),verification_spec_id:spec};}
function unique(values:string[]):string[]{return [...new Set(values)].sort();}
