import { realpath } from "node:fs/promises";
import path from "node:path";
import { compileLongTaskContract, writeCompiledLongTaskContract } from "./long-task-contract-compiler.js";
import { writeLongTaskRegistryMirror } from "./long-task-active-task.js";
import { LongTaskHostRegistryServiceV1, type AuthorityReservationHandleV1 } from "./long-task-host-service.js";
import { runLongTaskFinalGate } from "./long-task-final-gate.js";
import { writeLongTaskStatus } from "./long-task-status.js";
import { verifyLongTask } from "./long-task-verifier.js";
import { stopCheckLongTask } from "./long-task-stop-check.js";
import { evaluateLongTaskBindings } from "./long-task-binding-evaluator.js";
import { readCanonicalJsonV3 } from "./long-task-durable-json.js";
import type { FinalResultEnvelopeV3 } from "./long-task-run-result.js";

export interface ManagedHostWorkerConfigV1 { schema_version:"ty-context-host-service-config-v1"; state_root:string; helper_path:string; sandbox_launcher_path:string;sandbox_launcher_sha256:string;cli_worker_path:string; cli_worker_sha256:string }
export interface ManagedHostWorkerRequestV1 { schema_version:"ty-context-host-worker-request-v1"; method:string; repository_hint:string; params:Record<string,unknown> }

export async function runManagedHostWorkerRequestV1(request:ManagedHostWorkerRequestV1,config:ManagedHostWorkerConfigV1):Promise<unknown>{
  if(!request||request.schema_version!=="ty-context-host-worker-request-v1"||!request.params||typeof request.params!=="object"||Array.isArray(request.params))throw new Error("host_worker_request_invalid");const repository=await realpath(request.repository_hint);const service=await serviceFor(repository,config.state_root);
  if(request.method==="reserve_authority"){const workdir=await workdirParam(request.params,repository);return service.reserveAuthority(repository,workdir);}
  if(request.method==="compile_and_seal"){const workdir=await workdirParam(request.params,repository);const reservation=reservationParam(request.params);try{const contract=await compileLongTaskContract(workdir,repository,{write:false});const registry=await service.sealAuthority(reservation,contract);await writeCompiledLongTaskContract(workdir,contract);await writeLongTaskRegistryMirror(registry);return {schema_version:"ty-context-host-compile-result-v1",contract_sha256:contract.contract_sha256,registry_id:registry.registry_id,counts:{requirements:contract.requirements.length,plan_items:contract.plan_items.length,obligations:contract.obligations.length,bindings:contract.bindings.length,acceptance_criteria:contract.acceptance_criteria.length,proof_requirements:contract.proof_requirements.length,verification_specs:contract.verification_specs.length}};}catch(error){await service.abandonReservation(reservation).catch(()=>undefined);throw error;}}
  if(request.method==="verify"){const authority=await requiredAuthority(service,repository);const workdir=authority.registry.workdir_identity.canonical_path;assertOptionalWorkdir(request.params,workdir);const specIds=stringArray(request.params.spec_ids,"spec_ids",true);const run=await verifyLongTask(workdir,specIds.length?specIds:undefined,{contract:authority.contract,host_service:service,oracle_sandbox:sandbox(config)});const binding=evaluateLongTaskBindings(authority.contract,run.snapshot,run,workdir);const status=await writeLongTaskStatus(workdir,run,binding);return {schema_version:"ty-context-host-verify-result-v1",contract_sha256:run.contract_sha256,run_id:run.run_id,workflow_status:status.workflow_status,findings_count:status.findings.length,spec_results:Object.fromEntries(run.spec_results.map((item)=>[item.spec_id,item.status]))};}
  if(request.method==="final_gate"){const authority=await requiredAuthority(service,repository);const workdir=authority.registry.workdir_identity.canonical_path;assertOptionalWorkdir(request.params,workdir);const result=await runLongTaskFinalGate(workdir,{contract:authority.contract,host_service:service,oracle_sandbox:sandbox(config)});return finalSummary(result,workdir);}
  if(request.method==="handle_hook_event"){const authority=await requiredAuthority(service,repository);const event=text(request.params.hook_event_name,"hook_event_name");if(event!=="Stop")throw new Error("host_worker_hook_event_invalid");const workdir=authority.registry.workdir_identity.canonical_path;const message=typeof request.params.last_assistant_message==="string"?request.params.last_assistant_message:"";const outcome=await stopCheckLongTask(workdir,message,{contract:authority.contract,host_service:service,oracle_sandbox:sandbox(config)});if(outcome.decision==="block")return block(outcome.reason??"Final verification needs work; continue implementation.");const envelope=(await readCanonicalJsonV3<FinalResultEnvelopeV3>(path.join(workdir,"final-result.json"))).value;await service.releaseTerminal(repository,envelope.payload as unknown as Record<string,unknown>,text(request.params.turn_id,"turn_id"));return {};}
  throw new Error("host_worker_method_forbidden");
}

async function serviceFor(repository:string,stateRoot:string):Promise<LongTaskHostRegistryServiceV1>{const shard=await import("./composite-campaign-codec.js").then(({sha256Hex})=>sha256Hex(process.platform==="win32"?repository.toLocaleLowerCase("en-US"):repository));return new LongTaskHostRegistryServiceV1({stateRoot:path.join(await realpath(stateRoot),"repositories",shard),keyRoot:await realpath(stateRoot)});}
async function requiredAuthority(service:LongTaskHostRegistryServiceV1,repository:string){const value=await service.readActiveAuthority(repository);if(!value)throw new Error("host_active_registry_missing");return value;}
async function workdirParam(params:Record<string,unknown>,repository:string):Promise<string>{const candidate=await realpath(text(params.workdir,"workdir"));if(!inside(repository,candidate))throw new Error("host_worker_workdir_outside_repository");return candidate;}
function reservationParam(params:Record<string,unknown>):AuthorityReservationHandleV1{const value=params.reservation;if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("host_authority_reservation_missing");const record=value as Record<string,unknown>;for(const key of ["kind","repository_identity_hash","workdir_identity_hash"])if(typeof record[key]!=="string")throw new Error("host_authority_reservation_invalid");return value as AuthorityReservationHandleV1;}
function assertOptionalWorkdir(params:Record<string,unknown>,expected:string):void{if(params.workdir!==undefined&&normalized(text(params.workdir,"workdir"))!==normalized(expected))throw new Error("active_contract_revision_requires_user_authorization");}
function stringArray(value:unknown,name:string,optional=false):string[]{if(value===undefined&&optional)return[];if(!Array.isArray(value)||value.some((item)=>typeof item!=="string"||!item))throw new Error(`host_worker_${name}_invalid`);return [...new Set(value)].sort();}
function text(value:unknown,name:string):string{if(typeof value!=="string"||!value)throw new Error(`host_worker_${name}_invalid`);return value;}
function finalSummary(result:Awaited<ReturnType<typeof runLongTaskFinalGate>>,workdir:string){return {schema_version:"ty-context-host-final-result-summary-v1",contract_sha256:result.contract_sha256,run_id:result.run_id,workflow_status:result.workflow_status,findings_count:result.findings.length,final_result_path:path.join(workdir,"final-result.json"),...(result.external_blocker?{external_blocker:{environment_requirement_ids:result.external_blocker.environment_requirement_ids,reason_codes:result.external_blocker.reason_codes,minimal_user_action:result.external_blocker.minimal_user_action}}:{})};}
function block(reason:string){return {decision:"block",reason};}
function sandbox(config:ManagedHostWorkerConfigV1){return {helper_path:config.helper_path,sandbox_launcher_path:config.sandbox_launcher_path,sandbox_launcher_sha256:config.sandbox_launcher_sha256};}
function inside(root:string,candidate:string):boolean{const left=normalized(root);const right=normalized(candidate);return right===left||right.startsWith(`${left}${path.sep}`);}
function normalized(value:string):string{const resolved=path.resolve(value).replace(/^\\\\\?\\/u,"");return process.platform==="win32"?resolved.toLocaleLowerCase("en-US"):resolved;}
