import { chmod, copyFile, lstat, mkdir, mkdtemp, open, readFile, readdir, readlink, realpath, rename, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import type { DependencyPlanV3, FrozenVerificationSpecV3 } from "./long-task-contract-schema.js";
import type { DependencyLayerHandleV3 } from "./long-task-dependency-layer.js";
import { nodePermissionOptions } from "./long-task-sandbox-node.js";
import { resolveWindowsPeRuntimeV1 } from "./long-task-windows-pe-runtime.js";
import { playwrightWorkerThreadAdapterSourceV1 } from "./long-task-playwright-worker-adapter.js";

const CACHE=path.join(os.tmpdir(),"project-tiny-context-harness-host-v3","browsers");
const POLICY={schema_version:"long-task-browser-install-policy-v3",browser:"chromium",install_deps:false,network:"playwright_cdn_only",mount:"read_only"} as const;
export const LONG_TASK_BROWSER_INSTALL_POLICY_SHA256=sha256Hex(canonicalJson(POLICY));

export interface BrowserLayerFileV3 { path:string; type:"file"|"symlink"; mode:number; size:number; sha256?:string; target?:string }
export interface BrowserLayerExecutableV3 { path:string; sha256:string; size:number }
export interface BrowserLayerManifestV3 {
  schema_version:"long-task-browser-layer-v3";
  key:string;
  request_key:string;
  dependency_layer_key:string;
  playwright_package:{name:string;version:string;integrity:string;browsers_json_sha256:string};
  browser_components:Array<{name:string;revision:string;browser_version:string|null;descriptor_sha256:string}>;
  platform:{platform:NodeJS.Platform;release:string;arch:string;libc_abi:string};
  install_policy_sha256:string;
  system_runtime:Array<{source:string;target:string;size:number;sha256:string}>;
  node_runtime:{version:string;executable:{target:string;size:number;sha256:string};worker_adapter:{target:string;size:number;sha256:string};libraries:Array<{source:string;target:string;size:number;sha256:string}>}|null;
  executables:BrowserLayerExecutableV3[];
  files:BrowserLayerFileV3[];
  install:{exit_code:0;stdout_sha256:string;stderr_sha256:string};
  created_at:string;
}
export interface BrowserLayerHandleV3 { key:string; root:string; payload_root:string; manifest:BrowserLayerManifestV3 }

export async function prepareBrowserLayer(plan:DependencyPlanV3,dependency:DependencyLayerHandleV3|null,specs:FrozenVerificationSpecV3[]):Promise<BrowserLayerHandleV3|null>{
  if(!specs.some((spec)=>spec.command_steps.some((step)=>step.tool==="playwright_test")))return null;
  if(!dependency)throw new Error("browser_layer_corrupt:dependency_layer_missing");
  const request=await browserRequest(plan,dependency);await ensureCache();
  const pointer=path.join(CACHE,"requests",`${request.key}.json`);
  const existing=await readPointer(pointer,request.key);
  if(existing){try{return await readLayer(path.join(CACHE,"layers",existing),existing,request.key);}catch(error){if(!message(error).startsWith("browser_layer_corrupt"))throw error;await quarantine(path.join(CACHE,"layers",existing),existing);await rm(pointer,{force:true});}}
  const lock=path.join(CACHE,"locks",`${request.key}.lock`);let owner=false;
  try{const handle=await open(lock,"wx");owner=true;await handle.writeFile(canonicalJson({pid:process.pid,process_started_at:new Date(Date.now()-process.uptime()*1000).toISOString(),service_boot_id:sha256Hex(`${os.hostname()}\0${Math.floor(Date.now()/1000-os.uptime())}`),started_at:new Date().toISOString(),lease_expires_at:new Date(Date.now()+30*60_000).toISOString()}));await handle.close();}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;}
  if(!owner)return waitForLayer(pointer,request.key,lock);
  const renew=setInterval(()=>writeFile(lock,canonicalJson({pid:process.pid,process_started_at:new Date(Date.now()-process.uptime()*1000).toISOString(),started_at:new Date().toISOString(),lease_expires_at:new Date(Date.now()+30*60_000).toISOString()})).catch(()=>undefined),60_000);renew.unref();
  try{const raced=await readPointer(pointer,request.key);if(raced)return await readLayer(path.join(CACHE,"layers",raced),raced,request.key);return await buildLayer(request,dependency,pointer);}finally{clearInterval(renew);await rm(lock,{force:true});}
}

interface NodeRuntimeSourceV1 { source_path?:string;bytes?:Buffer;target:string;size:number;sha256:string }
async function browserRequest(plan:DependencyPlanV3,dependency:DependencyLayerHandleV3):Promise<{key:string;packageIdentity:{name:string;version:string;integrity:string;browsers_json_sha256:string};components:BrowserLayerManifestV3["browser_components"];platform:DependencyPlanV3["platform"];systemRuntime:BrowserLayerManifestV3["system_runtime"];nodeRuntime:BrowserLayerManifestV3["node_runtime"];nodeRuntimeSources:NodeRuntimeSourceV1[]}>{
  const planned=plan.playwright_packages.find((item)=>item.name==="playwright")??plan.playwright_packages.find((item)=>item.name==="@playwright/test");if(!planned?.integrity)throw new Error("browser_layer_corrupt:playwright_integrity_missing");
  const installed=dependency.manifest.packages.find((item)=>item.name===planned.name);if(!installed||installed.version!==planned.version)throw new Error("browser_layer_corrupt:playwright_package_identity");
  const core=dependency.manifest.packages.find((item)=>item.name==="playwright-core");if(!core)throw new Error("browser_layer_corrupt:playwright_core_missing");
  const browsersPath=inside(dependency.root,path.posix.join("payload",core.path,"browsers.json"));const bytes=await readFile(browsersPath);const parsed=JSON.parse(bytes.toString("utf8")) as {browsers?:Array<Record<string,unknown>>};if(!Array.isArray(parsed.browsers))throw new Error("browser_layer_corrupt:browsers_json_invalid");
  const selected=new Set(["chromium","chromium-headless-shell","ffmpeg",...(process.platform==="win32"?["winldd"]:[])]);const rows=parsed.browsers.filter((item)=>selected.has(String(item.name)));if(!rows.some((item)=>item.name==="chromium")||!rows.some((item)=>item.name==="chromium-headless-shell"))throw new Error("browser_layer_corrupt:chromium_descriptor_missing");
  const components=rows.map((item)=>({name:String(item.name),revision:String(item.revision),browser_version:typeof item.browserVersion==="string"?item.browserVersion:null,descriptor_sha256:sha256Hex(canonicalJson(item))})).sort((a,b)=>a.name.localeCompare(b.name));
  const packageIdentity={name:planned.name,version:planned.version,integrity:planned.integrity,browsers_json_sha256:sha256Hex(bytes)};const systemRuntime=await systemBrowserRuntime();const {manifest:nodeRuntime,sources:nodeRuntimeSources}=await nodeRuntimeRequest();const unsigned={dependency_layer_key:dependency.key,playwright_package:packageIdentity,browser_components:components,platform:plan.platform,install_policy_sha256:LONG_TASK_BROWSER_INSTALL_POLICY_SHA256,system_runtime:systemRuntime,node_runtime:nodeRuntime};return {key:sha256Hex(canonicalJson(unsigned)),packageIdentity,components,platform:plan.platform,systemRuntime,nodeRuntime,nodeRuntimeSources};
}

async function buildLayer(request:Awaited<ReturnType<typeof browserRequest>>,dependency:DependencyLayerHandleV3,pointer:string):Promise<BrowserLayerHandleV3>{
  const temporary=await mkdtemp(path.join(CACHE,"building",`${request.key}.`));const staged=path.join(temporary,"layer");const payload=path.join(staged,"payload");await mkdir(payload,{recursive:true});
  try{
    const pkg=dependency.manifest.packages.find((item)=>item.name==="playwright");if(!pkg)throw new Error("browser_layer_corrupt:playwright_cli_missing");const cli=inside(dependency.root,path.posix.join("payload",pkg.path,"cli.js"));
    const home=path.join(temporary,"home");const temp=path.join(temporary,"tmp");await mkdir(home,{recursive:true});await mkdir(temp,{recursive:true});
    const permissionAdapter=path.join(temporary,"canonical-realpath-adapter.cjs");const canonicalPaths=pathAncestors(await realpath(payload));
    await writeFile(permissionAdapter,canonicalRealpathAdapter());
    const env=minimalEnvironment(home,temp,payload,dependency.root,permissionAdapter,canonicalPaths);const installed=await run(process.execPath,[cli,"install","chromium"],temporary,env,10*60_000);if(installed.code!==0)throw new Error(`browser_install_failed:${installed.code}:${sha256Hex(installed.stdout)}:${sha256Hex(installed.stderr)}`);await attachSystemRuntime(payload,request.systemRuntime);await attachNodeRuntime(payload,request.nodeRuntimeSources);
    const before=await inventory(payload);const executables=before.filter((item)=>item.type==="file"&&isExecutable(item.path,item.mode)).map((item)=>({path:item.path,sha256:item.sha256!,size:item.size})).sort((a,b)=>a.path.localeCompare(b.path));if(executables.length===0)throw new Error("browser_layer_corrupt:browser_executable_missing");
    await makeReadonly(payload);const files=await inventory(payload);const executableHashes=executables.map((item)=>({path:item.path,sha256:files.find((file)=>file.path===item.path)?.sha256??item.sha256}));const key=sha256Hex(canonicalJson({request_key:request.key,executable_hashes:executableHashes}));
    const manifest:BrowserLayerManifestV3={schema_version:"long-task-browser-layer-v3",key,request_key:request.key,dependency_layer_key:dependency.key,playwright_package:request.packageIdentity,browser_components:request.components,platform:request.platform,install_policy_sha256:LONG_TASK_BROWSER_INSTALL_POLICY_SHA256,system_runtime:request.systemRuntime,node_runtime:request.nodeRuntime,executables:executables.map((item)=>({...item,sha256:executableHashes.find((value)=>value.path===item.path)!.sha256})),files,install:{exit_code:0,stdout_sha256:sha256Hex(installed.stdout),stderr_sha256:sha256Hex(installed.stderr)},created_at:new Date().toISOString()};
    await writeFile(path.join(staged,"layer-manifest.json"),canonicalJson(manifest));const final=path.join(CACHE,"layers",key);try{await rename(staged,final);}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;await readLayer(final,key,request.key);}
    await atomicPointer(pointer,{schema_version:"long-task-browser-pointer-v3",request_key:request.key,key});return await readLayer(final,key,request.key);
  }finally{await rm(temporary,{recursive:true,force:true});}
}

async function readLayer(root:string,key:string,requestKey:string):Promise<BrowserLayerHandleV3>{const manifest=JSON.parse(await readFile(path.join(root,"layer-manifest.json"),"utf8")) as BrowserLayerManifestV3;if(manifest.schema_version!=="long-task-browser-layer-v3"||manifest.key!==key||manifest.request_key!==requestKey||manifest.install_policy_sha256!==LONG_TASK_BROWSER_INSTALL_POLICY_SHA256)throw new Error(`browser_layer_corrupt:${key}:identity`);const files=await inventory(path.join(root,"payload"));if(canonicalJson(files)!==canonicalJson(manifest.files))throw new Error(`browser_layer_corrupt:${key}:merkle`);const executableHashes=manifest.executables.map((item)=>({path:item.path,sha256:files.find((file)=>file.path===item.path)?.sha256}));if(executableHashes.some((item)=>!item.sha256)||sha256Hex(canonicalJson({request_key:requestKey,executable_hashes:executableHashes}))!==key)throw new Error(`browser_layer_corrupt:${key}:executable`);return {key,root,payload_root:path.join(root,"payload"),manifest};}
export async function verifyBrowserLayerAtPath(root:string,key:string,requestKey:string):Promise<BrowserLayerHandleV3>{return readLayer(root,key,requestKey);}
async function readPointer(file:string,requestKey:string):Promise<string|null>{try{const value=JSON.parse(await readFile(file,"utf8")) as {schema_version?:string;request_key?:string;key?:string};return value.schema_version==="long-task-browser-pointer-v3"&&value.request_key===requestKey&&typeof value.key==="string"?value.key:null;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return null;throw error;}}
async function waitForLayer(pointer:string,requestKey:string,lock:string):Promise<BrowserLayerHandleV3>{const deadline=Date.now()+10*60_000;while(Date.now()<deadline){const key=await readPointer(pointer,requestKey);if(key)return readLayer(path.join(CACHE,"layers",key),key,requestKey);try{await lstat(lock);}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return prepareFromWait(pointer,requestKey);throw error;}await new Promise((resolve)=>setTimeout(resolve,200+Math.floor(Math.random()*300)));}throw new Error(`browser_cache_timeout:${requestKey}`);}
async function prepareFromWait(pointer:string,requestKey:string):Promise<BrowserLayerHandleV3>{const key=await readPointer(pointer,requestKey);if(key)return readLayer(path.join(CACHE,"layers",key),key,requestKey);throw new Error(`browser_cache_timeout:${requestKey}:builder_disappeared`);}
async function atomicPointer(file:string,value:unknown):Promise<void>{const temporary=`${file}.${process.pid}.${Date.now()}.tmp`;await writeFile(temporary,canonicalJson(value));await rename(temporary,file);}
async function ensureCache():Promise<void>{for(const name of ["requests","layers","building","locks","quarantine"])await mkdir(path.join(CACHE,name),{recursive:true});}
async function quarantine(root:string,key:string):Promise<void>{try{await rename(root,path.join(CACHE,"quarantine",`${key}.${Date.now()}`));}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}

async function systemBrowserRuntime():Promise<BrowserLayerManifestV3["system_runtime"]>{if(process.platform!=="win32")return [];const root=process.env.SystemRoot??process.env.WINDIR;if(!root)throw new Error("browser_layer_corrupt:system_root_missing");const source=path.join(root,"System32","version.dll");const bytes=await readFile(source);return [{source:"system32/version.dll",target:"version.dll",size:bytes.length,sha256:sha256Hex(bytes)}];}
async function nodeRuntimeRequest():Promise<{manifest:BrowserLayerManifestV3["node_runtime"];sources:NodeRuntimeSourceV1[]}>{if(process.platform!=="win32")return {manifest:null,sources:[]};const executable=await realpath(process.execPath);const executableBytes=await readFile(executable);const runtime=await resolveWindowsPeRuntimeV1(executable);const executableTarget="node-runtime/node.exe";const adapterTarget="node-runtime/playwright-worker-adapter.cjs";const adapterBytes=Buffer.from(playwrightWorkerThreadAdapterSourceV1());const libraries=runtime.map((item)=>({source:`system32/${path.basename(item.path).toLocaleLowerCase("en-US")}`,target:`node-runtime/${path.basename(item.path)}`,size:item.size,sha256:item.sha256}));const targets=new Set<string>();for(const item of [{target:executableTarget},{target:adapterTarget},...libraries]){const key=item.target.toLocaleLowerCase("en-US");if(targets.has(key))throw new Error(`browser_layer_corrupt:node_runtime_collision:${item.target}`);targets.add(key);}return {manifest:{version:process.version,executable:{target:executableTarget,size:executableBytes.length,sha256:sha256Hex(executableBytes)},worker_adapter:{target:adapterTarget,size:adapterBytes.length,sha256:sha256Hex(adapterBytes)},libraries},sources:[{source_path:executable,target:executableTarget,size:executableBytes.length,sha256:sha256Hex(executableBytes)},{bytes:adapterBytes,target:adapterTarget,size:adapterBytes.length,sha256:sha256Hex(adapterBytes)},...runtime.map((item)=>({source_path:item.path,target:`node-runtime/${path.basename(item.path)}`,size:item.size,sha256:item.sha256}))]};}
async function attachNodeRuntime(payload:string,sources:NodeRuntimeSourceV1[]):Promise<void>{for(const item of sources){const bytes=item.bytes??await readFile(item.source_path!);if(bytes.length!==item.size||sha256Hex(bytes)!==item.sha256)throw new Error(`browser_layer_corrupt:node_runtime_changed:${item.target}`);const target=inside(payload,item.target);await mkdir(path.dirname(target),{recursive:true});if(item.source_path)await copyFile(item.source_path,target);else await writeFile(target,bytes,{flag:"wx"});const copied=await readFile(target);if(copied.length!==item.size||sha256Hex(copied)!==item.sha256)throw new Error(`browser_layer_corrupt:node_runtime_copy:${item.target}`);}}
async function attachSystemRuntime(payload:string,runtime:BrowserLayerManifestV3["system_runtime"]):Promise<void>{if(runtime.length===0)return;const root=process.env.SystemRoot??process.env.WINDIR;if(!root)throw new Error("browser_layer_corrupt:system_root_missing");const executables=await findBrowserExecutables(payload);if(executables.length===0)throw new Error("browser_layer_corrupt:browser_executable_missing");for(const item of runtime){const source=item.source==="system32/version.dll"?path.join(root,"System32","version.dll"):null;if(!source)throw new Error(`browser_layer_corrupt:system_runtime_source:${item.source}`);const bytes=await readFile(source);if(bytes.length!==item.size||sha256Hex(bytes)!==item.sha256)throw new Error(`browser_layer_corrupt:system_runtime_changed:${item.source}`);for(const executable of executables){const target=path.join(path.dirname(executable),item.target);await copyFile(source,target);const copied=await readFile(target);if(copied.length!==item.size||sha256Hex(copied)!==item.sha256)throw new Error(`browser_layer_corrupt:system_runtime_copy:${item.target}`);}}}
async function findBrowserExecutables(root:string):Promise<string[]>{const result:string[]=[];async function visit(directory:string):Promise<void>{for(const entry of await readdir(directory,{withFileTypes:true})){const file=path.join(directory,entry.name);if(entry.isDirectory())await visit(file);else if(entry.isFile()&&/^(?:chrome|chrome-headless-shell)\.exe$/iu.test(entry.name))result.push(file);}}await visit(root);return result.sort();}

async function inventory(root:string):Promise<BrowserLayerFileV3[]>{const result:BrowserLayerFileV3[]=[];const rootReal=await realpath(root);async function visit(directory:string,relative=""):Promise<void>{for(const entry of await readdir(directory,{withFileTypes:true})){const rel=relative?`${relative}/${entry.name}`:entry.name;const file=path.join(directory,entry.name);const info=await lstat(file);if(info.isSymbolicLink()){const target=await readlink(file);if(path.isAbsolute(target))throw new Error(`browser_layer_corrupt:absolute_symlink:${rel}`);const resolved=await realpath(file);if(resolved!==rootReal&&!resolved.startsWith(`${rootReal}${path.sep}`))throw new Error(`browser_layer_corrupt:symlink_escape:${rel}`);result.push({path:rel,type:"symlink",mode:info.mode,size:info.size,target:target.replace(/\\/g,"/")});continue;}if(entry.isDirectory()){await visit(file,rel);continue;}if(!entry.isFile()||info.nlink>1)throw new Error(`browser_layer_corrupt:special_file:${rel}`);result.push({path:rel,type:"file",mode:info.mode,size:info.size,sha256:sha256Hex(await readFile(file))});}}await visit(root);return result.sort((a,b)=>a.path.localeCompare(b.path));}
async function makeReadonly(root:string):Promise<void>{async function visit(directory:string):Promise<void>{for(const entry of await readdir(directory,{withFileTypes:true})){const file=path.join(directory,entry.name);if(entry.isDirectory()){await visit(file);await chmod(file,0o555);}else if(entry.isFile())await chmod(file,0o444);}}await visit(root);await chmod(root,0o555);}
function isExecutable(relative:string,mode:number):boolean{return process.platform==="win32"?/\.(?:exe|cmd)$/iu.test(relative):Boolean(mode&0o111);}
function minimalEnvironment(home:string,temp:string,browserRoot:string,dependencyRoot:string,permissionAdapter:string,canonicalPaths:string[]):NodeJS.ProcessEnv{const profile={read_paths:[dependencyRoot,browserRoot,home,temp,permissionAdapter],write_paths:[browserRoot,home,temp],allow_child_process:true,allow_worker:true,allow_addons:true};const values:NodeJS.ProcessEnv={PATH:path.dirname(process.execPath),Path:path.dirname(process.execPath),PATHEXT:process.env.PATHEXT,SYSTEMROOT:process.env.SYSTEMROOT,WINDIR:process.env.WINDIR,ComSpec:process.env.ComSpec,HOME:home,USERPROFILE:home,TMP:temp,TEMP:temp,CI:"1",PLAYWRIGHT_BROWSERS_PATH:browserRoot,PLAYWRIGHT_SKIP_BROWSER_GC:"1",TY_CONTEXT_CANONICAL_PATHS_B64:Buffer.from(JSON.stringify(canonicalPaths)).toString("base64url"),NODE_OPTIONS:`${nodePermissionOptions(profile)} --require=${JSON.stringify(permissionAdapter)}`};for(const key of ["HTTP_PROXY","HTTPS_PROXY","NO_PROXY","http_proxy","https_proxy","no_proxy"])if(process.env[key])values[key]=process.env[key];return values;}
function pathAncestors(value:string):string[]{const result=[];let current=path.resolve(value);while(true){result.push(current);const parent=path.dirname(current);if(parent===current)break;current=parent;}return result;}
function canonicalRealpathAdapter():string{return `const fs=require("node:fs"),path=require("node:path");const canonical=new Set(JSON.parse(Buffer.from(process.env.TY_CONTEXT_CANONICAL_PATHS_B64,"base64url").toString("utf8")).map(value=>path.resolve(value)));const hit=value=>{try{const resolved=path.resolve(Buffer.isBuffer(value)?value.toString():value instanceof URL?require("node:url").fileURLToPath(value):String(value));return canonical.has(resolved)?resolved:null}catch{return null}};const encode=(value,options)=>options==="buffer"||options?.encoding==="buffer"?Buffer.from(value):value;const asyncOriginal=fs.realpath;fs.realpath=function(value,...args){const resolved=hit(value);if(!resolved)return asyncOriginal.call(this,value,...args);const callback=args.at(-1),options=typeof args[0]==="function"?undefined:args[0];process.nextTick(callback,null,encode(resolved,options))};fs.realpath.native=fs.realpath;const syncOriginal=fs.realpathSync;fs.realpathSync=function(value,options){const resolved=hit(value);return resolved?encode(resolved,options):syncOriginal.call(this,value,options)};fs.realpathSync.native=fs.realpathSync;const promiseOriginal=fs.promises.realpath;fs.promises.realpath=async function(value,options){const resolved=hit(value);return resolved?encode(resolved,options):promiseOriginal.call(this,value,options)};`;}
async function run(executable:string,argv:string[],cwd:string,env:NodeJS.ProcessEnv,timeout:number):Promise<{code:number;stdout:Buffer;stderr:Buffer}>{return new Promise((resolve,reject)=>{const child=spawn(executable,argv,{cwd,env,shell:false,windowsHide:true});const stdout:Buffer[]=[];const stderr:Buffer[]=[];let size=0;let settled=false;const fail=(error:Error)=>{if(settled)return;settled=true;clearTimeout(timer);child.kill();reject(error);};const capture=(target:Buffer[])=>(chunk:Buffer)=>{size+=chunk.length;if(size>16*1024*1024){fail(new Error("browser_install_output_limit"));return;}target.push(Buffer.from(chunk));};child.stdout.on("data",capture(stdout));child.stderr.on("data",capture(stderr));child.on("error",fail);const timer=setTimeout(()=>fail(new Error("browser_install_timeout")),timeout);child.on("close",(code)=>{if(settled)return;settled=true;clearTimeout(timer);resolve({code:code??-1,stdout:Buffer.concat(stdout),stderr:Buffer.concat(stderr)});});});}
function inside(root:string,relative:string):string{const resolved=path.resolve(root,...relative.replace(/\\/g,"/").split("/"));const base=path.resolve(root);if(resolved!==base&&!resolved.startsWith(`${base}${path.sep}`))throw new Error(`browser_layer_corrupt:path_escape:${relative}`);return resolved;}
function message(error:unknown):string{return error instanceof Error?error.message:String(error);}
