import { access, realpath, stat } from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import { longTaskGitArgs } from "./long-task-git.js";

export interface ResolvedLongTaskSecretsV3 { values:Record<string,string>; refs:Array<{name:string;provider:string;present:boolean;fingerprint:string|null}> }
export async function repositorySecretId(root:string):Promise<string>{const canonical=await realpath(root);const identity=await stat(canonical,{bigint:true});const git=await gitIdentity(canonical);return sha256Hex(canonicalJson({canonical_path:process.platform==="win32"?canonical.toLocaleLowerCase("en-US"):canonical,platform:process.platform,volume_or_device:String(identity.dev),root_file_id:String(identity.ino),birth_identity:String(identity.birthtimeNs),git}));}
export function windowsCredentialTarget(repositoryId:string,ref:string):string{assertRef(ref);return `ty-context/${repositoryId}/${ref}`;}
export async function resolveLongTaskSecrets(repositoryRoot:string,refs:string[],salt:string):Promise<ResolvedLongTaskSecretsV3>{const repositoryId=await repositorySecretId(repositoryRoot);const values:Record<string,string>={};const manifest:ResolvedLongTaskSecretsV3["refs"]=[];for(const ref of [...new Set(refs)].sort()){assertRef(ref);const resolved=await readSecret(repositoryId,ref);if(resolved.value!==null){if(Buffer.byteLength(resolved.value,"utf8")<4)throw new Error(`secret_value_too_short:${ref}`);values[ref]=resolved.value;}manifest.push({name:ref,provider:resolved.provider,present:resolved.value!==null,fingerprint:resolved.value===null?null:sha256Hex(`long-task-secret-v3\0${salt}\0${resolved.value}`)});}return {values,refs:manifest};}

async function readSecret(repositoryId:string,ref:string):Promise<{provider:string;value:string|null}>{if(process.platform==="win32")return {provider:"windows-credential-manager",value:await readWindowsCredential(windowsCredentialTarget(repositoryId,ref))};if(process.platform==="darwin")return {provider:"macos-keychain",value:await readMacSecret(repositoryId,ref)};return {provider:"secret-service",value:await readLinuxSecret(repositoryId,ref)};}
async function readWindowsCredential(target:string):Promise<string|null>{let run:ProcessResult;try{run=await powershell(WINDOWS_READ,{TY_CONTEXT_CREDENTIAL_TARGET:target});}catch{throw new Error("secret_provider_unavailable:windows:provider_missing");}if(run.code===44)return null;if(run.code!==0)throw new Error(`secret_provider_unavailable:windows:${run.code}`);const bytes=Buffer.from(run.stdout.toString("utf8").trim(),"base64");try{return new TextDecoder("utf-8",{fatal:true}).decode(bytes);}catch{throw new Error("secret_provider_unavailable:windows:invalid_utf8");}}
async function readLinuxSecret(repositoryId:string,ref:string):Promise<string|null>{let run:ProcessResult;try{run=await execute("secret-tool",["lookup","schema","ty-context","repository-id",repositoryId,"env-ref",ref],{});}catch{throw new Error("secret_provider_unavailable:secret-service:provider_missing");}if(run.code===1)return null;if(run.code!==0)throw new Error(`secret_provider_unavailable:secret-service:${run.code}`);return run.stdout.toString("utf8").replace(/\r?\n$/u,"");}
async function readMacSecret(repositoryId:string,ref:string):Promise<string|null>{let run:ProcessResult;try{run=await execute("security",["find-generic-password","-s","ty-context","-a",`${repositoryId}:${ref}`,"-w"],{});}catch{throw new Error("secret_provider_unavailable:macos-keychain:provider_missing");}if(run.code===44)return null;if(run.code!==0)return null;return run.stdout.toString("utf8").replace(/\r?\n$/u,"");}

export async function __writeWindowsCredentialForTest(target:string,value:string):Promise<void>{if(process.platform!=="win32")throw new Error("windows_only");const run=await powershell(WINDOWS_WRITE,{TY_CONTEXT_CREDENTIAL_TARGET:target,TY_CONTEXT_CREDENTIAL_B64:Buffer.from(value,"utf8").toString("base64")});if(run.code!==0)throw new Error(`windows_credential_write_failed:${run.code}`);}
export async function __deleteWindowsCredentialForTest(target:string):Promise<void>{if(process.platform!=="win32")return;const run=await powershell(WINDOWS_DELETE,{TY_CONTEXT_CREDENTIAL_TARGET:target});if(run.code!==0&&run.code!==44)throw new Error(`windows_credential_delete_failed:${run.code}`);}

async function gitIdentity(root:string):Promise<Record<string,string>|null>{const common=await execute("git",longTaskGitArgs(root,["rev-parse","--git-common-dir"]),{},root);if(common.code!==0)return null;const raw=common.stdout.toString("utf8").trim();const commonPath=await realpath(path.resolve(root,raw));const info=await stat(commonPath,{bigint:true});const format=await execute("git",longTaskGitArgs(root,["rev-parse","--show-object-format"]),{},root);return {common_path:process.platform==="win32"?commonPath.toLocaleLowerCase("en-US"):commonPath,volume_or_device:String(info.dev),file_id:String(info.ino),birth_identity:String(info.birthtimeNs),object_format:format.code===0?format.stdout.toString("utf8").trim():"sha1"};}
async function powershell(script:string,extra:Record<string,string>):Promise<ProcessResult>{const executable=await findPowerShell();return execute(executable,["-NoLogo","-NoProfile","-NonInteractive","-EncodedCommand",Buffer.from(script,"utf16le").toString("base64")],extra);}
async function findPowerShell():Promise<string>{const names=["pwsh.exe","powershell.exe"];for(const directory of (process.env.PATH??process.env.Path??"").split(path.delimiter))for(const name of names){const candidate=path.resolve(directory||".",name);try{await access(candidate);return candidate;}catch{}}const fallback=path.join(process.env.SystemRoot??"C:\\Windows","System32","WindowsPowerShell","v1.0","powershell.exe");await access(fallback);return fallback;}
interface ProcessResult { code:number; stdout:Buffer; stderr:Buffer }
async function execute(executable:string,argv:string[],extra:Record<string,string>,cwd?:string):Promise<ProcessResult>{const env:NodeJS.ProcessEnv={PATH:process.env.PATH,Path:process.env.Path,PATHEXT:process.env.PATHEXT,SYSTEMROOT:process.env.SYSTEMROOT,WINDIR:process.env.WINDIR,ComSpec:process.env.ComSpec,...extra};return new Promise((resolve,reject)=>{const child=spawn(executable,argv,{cwd,env,shell:false,windowsHide:true});const stdout:Buffer[]=[];const stderr:Buffer[]=[];let size=0;const capture=(target:Buffer[])=>(chunk:Buffer)=>{size+=chunk.length;if(size>1024*1024){child.kill();reject(new Error("secret_provider_output_limit"));return;}target.push(Buffer.from(chunk));};child.stdout.on("data",capture(stdout));child.stderr.on("data",capture(stderr));child.on("error",reject);child.on("close",(code)=>resolve({code:code??-1,stdout:Buffer.concat(stdout),stderr:Buffer.concat(stderr)}));});}
function assertRef(ref:string):void{if(!/^[A-Z][A-Z0-9_]{0,127}$/u.test(ref))throw new Error(`undeclared_environment_ref:invalid:${ref}`);}

const WINDOWS_TYPES=[
  "using System; using System.Runtime.InteropServices;",
  "public static class TyContextCredential {",
  "[StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] public struct Credential { public uint Flags; public uint Type; public IntPtr TargetName; public IntPtr Comment; public long LastWritten; public uint CredentialBlobSize; public IntPtr CredentialBlob; public uint Persist; public uint AttributeCount; public IntPtr Attributes; public IntPtr TargetAlias; public IntPtr UserName; }",
  "[StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] public struct WritableCredential { public uint Flags; public uint Type; [MarshalAs(UnmanagedType.LPWStr)] public string TargetName; [MarshalAs(UnmanagedType.LPWStr)] public string Comment; public long LastWritten; public uint CredentialBlobSize; public IntPtr CredentialBlob; public uint Persist; public uint AttributeCount; public IntPtr Attributes; [MarshalAs(UnmanagedType.LPWStr)] public string TargetAlias; [MarshalAs(UnmanagedType.LPWStr)] public string UserName; }",
  "[DllImport(\"advapi32.dll\", EntryPoint=\"CredReadW\", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool Read(string target, uint type, uint flags, out IntPtr credential);",
  "[DllImport(\"advapi32.dll\", EntryPoint=\"CredWriteW\", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool Write(ref WritableCredential credential, uint flags);",
  "[DllImport(\"advapi32.dll\", EntryPoint=\"CredDeleteW\", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool Delete(string target, uint type, uint flags);",
  "[DllImport(\"advapi32.dll\", EntryPoint=\"CredFree\")] public static extern void Free(IntPtr credential);",
  "}"
].join("\n");
const WINDOWS_HEADER=["$ErrorActionPreference='Stop'",`Add-Type -TypeDefinition @'\n${WINDOWS_TYPES}\n'@`].join("\n");
const WINDOWS_READ=[WINDOWS_HEADER,"$pointer=[IntPtr]::Zero","if(![TyContextCredential]::Read($env:TY_CONTEXT_CREDENTIAL_TARGET,1,0,[ref]$pointer)){if([Runtime.InteropServices.Marshal]::GetLastWin32Error() -eq 1168){exit 44};exit 45}","try{$credential=[Runtime.InteropServices.Marshal]::PtrToStructure($pointer,[type][TyContextCredential+Credential]);$bytes=New-Object byte[] $credential.CredentialBlobSize;if($credential.CredentialBlobSize -gt 0){[Runtime.InteropServices.Marshal]::Copy($credential.CredentialBlob,$bytes,0,$credential.CredentialBlobSize)};[Console]::Out.Write([Convert]::ToBase64String($bytes))}finally{[TyContextCredential]::Free($pointer)}"].join("\n");
const WINDOWS_WRITE=[WINDOWS_HEADER,"$bytes=[Convert]::FromBase64String($env:TY_CONTEXT_CREDENTIAL_B64)","$blob=[Runtime.InteropServices.Marshal]::AllocHGlobal($bytes.Length)","try{[Runtime.InteropServices.Marshal]::Copy($bytes,0,$blob,$bytes.Length);$credential=New-Object TyContextCredential+WritableCredential;$credential.Type=1;$credential.TargetName=$env:TY_CONTEXT_CREDENTIAL_TARGET;$credential.CredentialBlobSize=$bytes.Length;$credential.CredentialBlob=$blob;$credential.Persist=2;$credential.UserName='ty-context';if(![TyContextCredential]::Write([ref]$credential,0)){exit 45}}finally{[Runtime.InteropServices.Marshal]::FreeHGlobal($blob)}"].join("\n");
const WINDOWS_DELETE=[WINDOWS_HEADER,"if(![TyContextCredential]::Delete($env:TY_CONTEXT_CREDENTIAL_TARGET,1,0)){if([Runtime.InteropServices.Marshal]::GetLastWin32Error() -eq 1168){exit 44};exit 45}"].join("\n");
