import { readFile } from "node:fs/promises";
import type { FrozenVerificationSpecV3 } from "./long-task-contract-schema.js";
import type { CommandRunV2, LongTaskFindingV2, VerificationSpecResultV2 } from "./long-task-run-result.js";
import { parseStrictJson } from "./composite-campaign-codec.js";

interface Observation { schema_version: "ty-context-observation-v1"; checks: Record<string, { passed: boolean; actual?: unknown }>; external_blocker?: { environment_requirement_id: string; reason_code: string; actual?: unknown; attempted_local_alternatives: string[] } }
export async function evaluateFrozenAssertions(spec: FrozenVerificationSpecV3, command: CommandRunV2, evidencePath: string, reverifyCommand: string): Promise<VerificationSpecResultV2> {
  const findings: LongTaskFindingV2[] = []; const assertion_results: Record<string, boolean> = {}; let observation: Observation | undefined;
  try { const stdout = await readFile(command.stdout_path, "utf8"); const line = stdout.split(/\r?\n/).reverse().find((entry: string) => entry.trim().startsWith("{")); observation = parseStrictJson(line ?? "") as Observation; if (observation.schema_version !== "ty-context-observation-v1" || !observation.checks || typeof observation.checks !== "object" || Array.isArray(observation.checks)) throw new Error("invalid observation shape"); } catch (error) { findings.push(finding("oracle_protocol_invalid", spec.id, "valid ty-context-observation-v1 JSON", String(error), evidencePath, reverifyCommand)); }
  if (observation?.external_blocker) { const reported = observation.external_blocker; const requirement = spec.environment_requirements.find((item) => item.required && item.id === reported.environment_requirement_id && item.reason_code === reported.reason_code); if (!requirement) findings.push(finding("forged_externally_blocked", spec.id, "a frozen required environment requirement and matching reason code", reported, evidencePath, reverifyCommand)); else { const attempted = new Set(reported.attempted_local_alternatives); const allAttempted = requirement.local_alternatives.every((item) => attempted.has(item)); if (!allAttempted) findings.push(finding("external_blocker_alternatives_not_attempted", spec.id, requirement.local_alternatives, reported.attempted_local_alternatives, evidencePath, reverifyCommand)); else return { spec_id: spec.id, status: "blocked", assertion_results, findings: [], external_blocker: { environment_requirement_id: requirement.id, reason_code: requirement.reason_code, actual: reported.actual, attempted_local_alternatives: [...reported.attempted_local_alternatives], minimal_user_action: requirement.minimal_user_action } }; } }
  const declared = [...spec.positive_assertions, ...spec.negative_assertions];
  for (const assertion of declared) { const check = observation?.checks[assertion.oracle_check_id]; const passed = command.exit_code === 0 && check?.passed === true; assertion_results[assertion.id] = passed; if (!passed) { const item=finding("runtime_behavior_failed", spec.id, assertion.expected ?? `forbidden value absent: ${JSON.stringify(assertion.forbidden)}`, check?.actual ?? `exit_code=${command.exit_code}`, evidencePath, reverifyCommand); if(assertion.source_forbidden_shortcut_ids?.length)item.forbidden_shortcut=assertion.source_forbidden_shortcut_ids.join(","); findings.push(item); } }
  if (observation) for (const id of Object.keys(observation.checks)) if (!declared.some((assertion) => assertion.oracle_check_id === id)) findings.push(finding("undeclared_oracle_check", spec.id, "declared oracle_check_id", id, evidencePath, reverifyCommand));
  return { spec_id: spec.id, status: findings.length === 0 ? "passed" : "failed", assertion_results, findings };
}
function finding(category: string, spec: string, expected: unknown, actual: unknown, evidence_path: string, reverify_command: string): LongTaskFindingV2 { return { category, verification_spec_id: spec, expected, actual, evidence_path, next_action: `Fix ${spec} and rerun its frozen verifier`, reverify_command }; }
