import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { FrozenVerificationSpecV3, OracleBundleV3, DependencyPlanV3 } from "./long-task-contract-schema.js";
import type { CommandRunV2 } from "./long-task-run-result.js";
import type { DependencyLayerHandleV3 } from "./long-task-dependency-layer.js";
import { canonicalJson, sha256Hex } from "./composite-campaign-codec.js";
import { verifyStoredOracleBundle } from "./long-task-oracle-bundle-store.js";
import { runSealedOracle } from "./long-task-oracle-runner.js";
import { buildLongTaskEnvironment, declaredLongTaskEnvironment } from "./long-task-environment.js";
import { runLongTaskCommandSteps } from "./long-task-command-step-runner.js";
import { isSandboxAccessError } from "./long-task-sandbox-node.js";
import { sanitizeLongTaskArtifacts, type LongTaskRedactorV3 } from "./long-task-redaction.js";

export async function runFrozenCommand(spec:FrozenVerificationSpecV3,bundle:OracleBundleV3,oracleInput:Record<string,unknown>,snapshotRoot:string,outputRoot:string,artifactRoot:string,environmentOverrides:Readonly<Record<string,string>>,dependencyPlan:DependencyPlanV3,dependencyLayer:DependencyLayerHandleV3|null,browserRoot:string|null,secretValues:Readonly<Record<string,string>>,redactor:LongTaskRedactorV3):Promise<CommandRunV2>{
  const cwd=spec.cwd==="repo_root"?snapshotRoot:path.resolve(snapshotRoot,spec.cwd);if(cwd!==snapshotRoot&&!cwd.startsWith(`${snapshotRoot}${path.sep}`))throw new Error(`wrong_cwd:${spec.id}`);for(const key of Object.keys(environmentOverrides)){if(!spec.environment_refs.includes(key))throw new Error(`undeclared_environment_ref:${spec.id}:${key}`);if(Object.prototype.hasOwnProperty.call(secretValues,key))throw new Error(`counterfactual_secret_override_forbidden:${spec.id}:${key}`);}const declared={...secretValues,...environmentOverrides};
  await mkdir(outputRoot,{recursive:true});const tempRoot=path.join(outputRoot,"temp");await mkdir(tempRoot,{recursive:true});const environment=buildLongTaskEnvironment(snapshotRoot,artifactRoot,tempRoot,dependencyLayer,browserRoot);const steps=await runLongTaskCommandSteps(spec,snapshotRoot,artifactRoot,outputRoot,tempRoot,dependencyPlan,dependencyLayer,browserRoot,environment.values,declared,redactor);await writeFile(path.join(outputRoot,"steps.json"),canonicalJson(steps));
  const present=spec.environment_refs.filter((ref)=>Object.prototype.hasOwnProperty.call(declared,ref)).sort();const input={...oracleInput,command_steps:steps.steps.map((value)=>({id:value.id,exit_code:value.exit_code,signal:null,stdout_artifact_id:`command:${value.id}:stdout`,stderr_artifact_id:`command:${value.id}:stderr`,output_artifact_ids:spec.command_steps.find((item)=>item.id===value.id)?.output_artifact_ids??[]})),environment_refs_present:present};const stdoutPath=path.join(outputRoot,"stdout.txt");const diagnosticPath=path.join(outputRoot,"diagnostic-stdout.txt");const stderrPath=path.join(outputRoot,"stderr.txt");const bundlePath=await verifyStoredOracleBundle(bundle);const oracleEnvironment=declaredLongTaskEnvironment({...environment.values,TY_CONTEXT_ORACLE_PROTOCOL:"ty-context-observation-v2",TY_CONTEXT_ORACLE_INPUT_B64:Buffer.from(canonicalJson(input),"utf8").toString("base64url")},spec.environment_refs,declared);const oracle=await runSealedOracle(spec.executable_path,bundlePath,cwd,spec.timeout_ms,oracleEnvironment,{read_paths:[snapshotRoot,artifactRoot,bundlePath],write_paths:[artifactRoot,tempRoot]},redactor);if(isSandboxAccessError(oracle.stderr)||steps.steps.some((item)=>item.sandbox_denied))throw new Error(`sandbox_access_denied:${spec.id}`);await sanitizeLongTaskArtifacts(artifactRoot,path.join(outputRoot,"quarantine"),redactor);
  await writeFile(stdoutPath,oracle.protocol);await writeFile(diagnosticPath,oracle.stdout);await writeFile(stderrPath,oracle.stderr);const exitCode=steps.exit_code||oracle.exit_code;return {spec_id:spec.id,executable:spec.executable_path,argv:oracle.argv,cwd,exit_code:exitCode,stdout_path:stdoutPath,stdout_sha256:sha256Hex(oracle.protocol),stderr_path:stderrPath,stderr_sha256:sha256Hex(oracle.stderr),started_at:steps.steps[0]?.started_at??oracle.started_at,completed_at:oracle.completed_at};
}
