import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const cliPath = fileURLToPath(new URL("../../packages/sdlc-harness/dist/cli.js", import.meta.url));

test("check-modularity warns for over-limit touched files without failing by default", async () => {
  const root = await createGitFixture();
  try {
    await writeFile(path.join(root, "src/large.ts"), lines(["one", "two", "three"]), "utf8");
    const result = runCli(root, ["check-modularity", "--touched", "--limit", "2"]);
    assert.equal(result.status, 0, output(result));
    assert.match(result.stdout, /check-modularity audited=1 warning=1 limit=2/);
    assert.match(result.stdout, /over-limit: src\/large\.ts 3 lines/);
    assert.match(result.stderr, /warning: src\/large\.ts: 3 physical lines exceeds limit 2/);
    assert.match(result.stderr, /Modularity: exception documented/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("check-modularity can opt into failing on warnings", async () => {
  const root = await createGitFixture();
  try {
    await writeFile(path.join(root, "src/large.ts"), lines(["one", "two", "three"]), "utf8");
    const result = runCli(root, ["check-modularity", "--touched", "--limit", "2", "--fail-on-warning"]);
    assert.equal(result.status, 1, output(result));
    assert.match(result.stdout, /warning=1/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("check-modularity audits explicit files without git state", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "sdlc-harness-modularity-file-"));
  try {
    await mkdir(path.join(root, "src"), { recursive: true });
    await writeFile(path.join(root, "src/explicit.ts"), lines(["one", "two", "three"]), "utf8");
    const result = runCli(root, ["check-modularity", "--file", "src/explicit.ts", "--limit", "2"]);
    assert.equal(result.status, 0, output(result));
    assert.match(result.stdout, /over-limit: src\/explicit\.ts 3 lines/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("check-modularity excludes generated and non-source paths", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "sdlc-harness-modularity-exclude-"));
  try {
    await mkdir(path.join(root, "src"), { recursive: true });
    await mkdir(path.join(root, "dist"), { recursive: true });
    await writeFile(path.join(root, "src/generated.ts"), lines(["// Code generated by tool. DO NOT EDIT.", "one", "two"]), "utf8");
    await writeFile(path.join(root, "dist/large.ts"), lines(["one", "two", "three"]), "utf8");
    await writeFile(path.join(root, "package-lock.json"), lines(["one", "two", "three"]), "utf8");
    const result = runCli(root, [
      "check-modularity",
      "--file",
      "src/generated.ts",
      "--file",
      "dist/large.ts",
      "--file",
      "package-lock.json",
      "--limit",
      "1"
    ]);
    assert.equal(result.status, 0, output(result));
    assert.match(result.stdout, /check-modularity audited=0 warning=0 limit=1/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("check-modularity audits files changed from a base ref", async () => {
  const root = await createGitFixture();
  try {
    const base = run("git", ["rev-parse", "HEAD"], root).stdout.trim();
    await writeFile(path.join(root, "src/large.ts"), lines(["one", "two", "three"]), "utf8");
    const result = runCli(root, ["check-modularity", "--base", base, "--limit", "2"]);
    assert.equal(result.status, 0, output(result));
    assert.match(result.stdout, /over-limit: src\/large\.ts 3 lines/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

async function createGitFixture() {
  const root = await mkdtemp(path.join(os.tmpdir(), "sdlc-harness-modularity-git-"));
  await mkdir(path.join(root, "src"), { recursive: true });
  await writeFile(path.join(root, "src/large.ts"), lines(["one", "two"]), "utf8");
  run("git", ["init"], root);
  run("git", ["config", "user.name", "Codex"], root);
  run("git", ["config", "user.email", "codex@example.local"], root);
  run("git", ["add", "."], root);
  run("git", ["commit", "-m", "initial"], root);
  return root;
}

function runCli(cwd, args) {
  return spawnSync(process.execPath, [cliPath, ...args], { cwd, encoding: "utf8" });
}

function run(command, args, cwd) {
  const result = spawnSync(command, args, { cwd, encoding: "utf8" });
  assert.equal(result.status, 0, output(result));
  return result;
}

function lines(values) {
  return `${values.join("\n")}\n`;
}

function output(result) {
  return `${result.stdout}\n${result.stderr}`;
}
